src/dxvk/dxvk_context.cpp
vkCmdBlitImage and vkCmdResolveImage need to be called outside a render
pass. flatten logic.
this fixes mipmap generation with Trackmania.
=> [dxvk] fix missing renderPassEnd calls

src/d3d11/d3d11_query.cpp
Trackmania was freezing on this query when clicking on "Connect".
=> [d3d11] mock D3D11_QUERY_TIMESTAMP

wine_utils/dlls_setup.sh.in, wine_utils/meson.build
=> Add an option to set up dxvk through overrides

wine_utils/setup_dxvk.sh.in
I mentioned this in #57.
It could help troubleshooting when things go wrong. Not really necessary, hopefully will be handy.
=> Setup script: added an option to check status

wine_utils/setup_dxvk.sh.in
While I was working on adding colours for setup and reset outputs, I noticed errors in error handling:
- Added colours to all commands output
- Corrected some error checking.
- Added a check to stop the script when winepath returns with error.
=> Setup script: improvements to error handling

src/dxvk/dxvk_compute.cpp
This will make it easier to figure which compute shaders are failing.
=> Debug logging for compute shaders

src/dxgi/dxgi_main.cpp
Allows to launch some games (e.g. World of Tanks) on Windows 10.
=> [dxgi] implement CreateDXGIFactory2

tests/dxbc/test_dxbc_disasm.cpp
* Avoid buggy wstring conversion
* Native `D3DReadFileToBlob()` and `D3DWriteBlobToFile()` used
* Extended to be able write to file directly
=> [tests] Simplified dxbc disasm test

src/dxbc/dxbc_compiler.cpp, src/dxbc/dxbc_compiler.h
Attempt to implement `retc` instruction.
https://msdn.microsoft.com/en-us/library/windows/desktop/hh447215(v=vs.85).aspx
=> [dxbc] implemented retc instructions

src/dxgi/dxgi_output.cpp, tests/dxgi/test_dxgi_factory.cpp
looks like some Frostbite titles requires it.
should help with #86 #16
=> [dxgi] implement DxgiOutput::FindClosestMatchingMode()

src/d3d11/d3d11_blend.cpp, src/d3d11/d3d11_buffer.cpp, src/d3d11/d3d11_class_linkage.cpp, src/d3d11/d3d11_cmdlist.cpp, src/d3d11/d3d11_depth_stencil.cpp, src/d3d11/d3d11_input_layout.cpp, src/d3d11/d3d11_query.cpp, src/d3d11/d3d11_rasterizer.cpp, src/d3d11/d3d11_sampler.cpp, src/d3d11/d3d11_texture.cpp, src/d3d11/d3d11_view_dsv.cpp, src/d3d11/d3d11_view_rtv.cpp, src/d3d11/d3d11_view_srv.cpp, src/d3d11/d3d11_view_uav.cpp, src/dxgi/dxgi_adapter.cpp, src/dxgi/dxgi_device.cpp, src/dxgi/dxgi_factory.cpp, src/dxgi/dxgi_output.cpp, src/dxgi/dxgi_swapchain.cpp
This will provide additional information which may be useful for troubleshooting.
=> [dxgi,d3d11] log unknown interfaces GUID

src/dxgi/dxgi_output.cpp
* remove useless checks
* fixed refresh rate matching
* fixed unspecified refresh rate detection
=> [dxgi] fix DxgiOutput::FindClosestMatchingMode() implementation

src/dxvk/dxvk_compute.cpp, src/dxvk/dxvk_device.cpp, src/dxvk/dxvk_graphics.cpp, src/dxvk/dxvk_pipecache.cpp, src/dxvk/dxvk_pipecache.h, src/util/util_env.cpp, src/util/util_env.h
Implements on-disk pipeline caching. Never compiled or tested it. People on discord say it works.
=> Shader cache

src/dxgi/dxgi_adapter.cpp, src/dxgi/dxgi_factory.cpp
Changed according to wine's tests.
=> [dxgi] Fix some argument checks

src/dxgi/dxgi_factory.cpp, src/dxgi/dxgi_main.cpp, src/dxgi/dxgi_swapchain.cpp
=> [dxgi] More argument handling improvements

src/d3d11/d3d11_blend.cpp, src/d3d11/d3d11_blend.h, src/d3d11/d3d11_depth_stencil.cpp, src/d3d11/d3d11_depth_stencil.h, src/d3d11/d3d11_rasterizer.cpp, src/d3d11/d3d11_sampler.cpp, src/d3d11/d3d11_sampler.h
Implement d3d11 stateblock normalization to match what d3d11 does in state object creation.
=> [d3d11] implement stateblock normalization

src/dxvk/dxvk_pipecompiler.cpp, src/dxvk/dxvk_pipecompiler.h
Obsoleted in 79a1703aea52d7b48558d391ad81b7fbb872086b
=> [dxvk] Remove unnecessary Parameter

build-wine64.txt, meson.build, src/d3d11/d3d11.spec, src/d3d11/d3d11_context_imm.cpp, src/d3d11/d3d11_context_imm.h, src/d3d11/meson.build, src/dxgi/dxgi.spec, src/dxgi/meson.build, src/dxvk/dxvk_cs.h, src/dxvk/dxvk_pipecache.h, src/dxvk/dxvk_pipecompiler.cpp, src/dxvk/dxvk_pipecompiler.h, src/dxvk/dxvk_queue.h, src/util/sync/sync_spinlock.h, src/util/thread.h, src/util/util_env.cpp, src/util/util_env.h, src/util/util_string.h, tests/d3d11/meson.build, tests/d3d11/test_d3d11_triangle.cpp, tests/dxbc/meson.build, tests/dxgi/meson.build
This pull request is partially based on https://github.com/doitsujin/dxvk/pull/268
With those patches I'm able to do a working 64-bit winelib builds. 32-bit builds need some more work.
Tests can be built as well, but Wine needs to be patched to provide d3dcompiler_47 importlib by adding:
IMPORTLIB = d3dcompiler_47
to dlls/d3dcompiler_47/Makefile.in. I till take care of that on Wine side once this is merged.
=> Winelib build

src/d3d10/d3d10_main.cpp
Fixes compilation with Microsoft's header files.
=> [d3d10] added missing __stdcall

src/dxbc/dxbc_analysis.cpp, src/dxbc/dxbc_analysis.h, src/dxbc/dxbc_chunk_shex.cpp, src/dxbc/dxbc_chunk_shex.h, src/dxbc/dxbc_common.cpp, src/dxbc/dxbc_common.h, src/dxbc/dxbc_compiler.cpp, src/dxbc/dxbc_compiler.h, src/dxbc/dxbc_module.cpp, src/dxbc/dxbc_module.h
=> clean up DxbcProgramVersion

LICENSE
Fix year in license (simple commit)
=> Fix year in License

README.md
I thought I would add the info about D3D10 too as mentioned in the release notes. From what I know these restrictions still apply, though please correct me if I'm wrong.
=> [meta] Update README with 'api' option for the HUD

src/spirv/spirv_module.cpp, src/spirv/spirv_module.h
=> [spirv] Implement proj sample variants

src/d3d11/d3d11_state_object.h
=> [d3d11] Fix MSVC 2017 compilation

meson_options.txt, src/d3d11/meson.build, src/dxgi/meson.build, src/meson.build
Supported following combinations:
* d3d11
* d3d11, dxgi
* d3d11, d3d10
* d3d11, d3d10, dxgi
* tests
Closes #1040
=> [build] Add options to disable dxgi/d3d* build

setup_dxvk.sh
Same goal as https://github.com/doitsujin/dxvk/pull/1064 but touching only setup_dxvk.sh.
I can think of one instance this is going to silently fail. If the user already has dxvk installed in a prefix, with more dlls than their new build includes, it won't remove the missing ones. It is a side-effect of trying to make partially-built dxvk and d9vk co-exist under the same prefix without trying to remove each other. Is it something that should be handled?
=> [utils] Don't try to install or remove missing dlls

src/vulkan/vulkan_util.h
=> [vulkan] Add operator overloads for VkOffset3D/2D

src/spirv/spirv_module.cpp, src/spirv/spirv_module.h
Backported from d9vk fixed function impl
=> [spirv] Some missing things

src/dxbc/dxbc_chunk_isgn.cpp, src/dxbc/dxbc_chunk_isgn.h, src/dxbc/dxbc_compiler.cpp, src/dxbc/dxbc_decoder.h, src/dxbc/dxbc_names.cpp, src/dxbc/dxbc_names.h
=> Add Debug Logging for Shader Signatures

src/spirv/spirv_module.cpp, src/spirv/spirv_module.h
=> [spirv] Implement opFMix and opCross

src/util/config/config.cpp
Fixes character flickering on Nvidia (https://streamable.com/bvrgk).
=> [util] Enable constant buffer range check for Saints Row games

README.md
https://github.com/doitsujin/dxvk/commit/7dc449a
=> [meta] Adding `compiler` to `DXVK_HUD`

src/dxvk/dxvk_image.h, src/dxvk/dxvk_memory.h, src/dxvk/dxvk_shader_key.h, src/dxvk/dxvk_unbound.cpp, src/spirv/spirv_module.cpp, src/spirv/spirv_module.h, src/util/com/com_object.h, src/util/meson.build, src/util/util_bit.h, src/util/util_math.h, src/util/util_matrix.cpp, src/util/util_matrix.h, src/util/util_misc.h, src/util/util_ratio.h, src/util/util_vector.h
Upstreaming some shared-code changes/additions in D9VK.
=> D9VK Shared Changes

src/d3d9/d3d9_stateblock.cpp, src/d3d9/d3d9_stateblock.h, src/util/util_bit.h
This touches shared code a little bit
=> [d3d9] Optimize State Blocks

LICENSE
=> [meta] Happy New Year 🎉💃🎊

src/d3d9/d3d9_constant_layout.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_spec_constants.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h, src/dxso/dxso_isgn.h, src/util/config/config.cpp
Massively increases GPU-bound performance in games which do ``if (bool from constant set)``
=> [d3d9] Use bools for spec constants

src/d3d11/d3d11_device.cpp, src/d3d11/d3d11_device.h, src/dxvk/dxvk_device.cpp, src/dxvk/dxvk_device.h, src/dxvk/dxvk_memory.cpp, src/dxvk/dxvk_memory.h
May improve perf on some broken notebooks where the APU only gets 256 MB of dedicated system memory *wink wink*
=> Force allocation limits on UMA systems

src/d3d9/d3d9_util.h, src/dxso/dxso_compiler.cpp
=> [d3d9] Fix GCC warnings

src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_subresource.h
=> [d3d9] Fix depth hazard case for write + read

src/dxbc/dxbc_compiler.cpp
UDiv is defined as having 0xffffffff as both the quotient and remainder value when the divisor is 0
This fixes vertex corruption on the water bottles in Half-Life: Alyx
https://github.com/ValveSoftware/Proton/issues/3681
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/udiv--sm4---asm-
=> [dxbc] Handle 0 divisors in UDiv

README.md
this makes things a bit easier to understand if you're not on a debian based distro
=> [documentation] improve README.md with regards to mingw64

src/util/config/config.cpp
See https://github.com/ValveSoftware/Proton/issues/350#issuecomment-605420176.
=> [util] Spoof AMD GPU for GTA IV

src/dxvk/hud/dxvk_hud_renderer.cpp, src/dxvk/hud/shaders/hud_text_frag.frag
I'm totally unfamiliar with this code base, so please make sure that I didn't frog something up.
=> [hud] remove unused texture

src/d3d9/d3d9_subresource.h, tests/d3d9/test_d3d9_triangle.cpp
=> Fix D3D9 compiler warnings

src/util/config/config.cpp
=> [util] Enable d3d9.invariantPosition for Halo/Hale CE

src/d3d11/d3d11_context.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_texture.h, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h
=> [dxvk] Add filter type to generateMipmaps

src/d3d9/d3d9_device.cpp
This fixes a stupid oversight by me.
The mapping/locking code for buffers and images is slightly different and the buffer code initialized physSlice later than the equivalent one for images.
Fixes #1664
~~This wouldn't have happened in Rust, time to rewrite.~~
=> [d3d9] Fix uninitialized BufferHandle when discarding mapped buffer

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_shader.cpp, src/d3d9/d3d9_shader.h, src/dxso/dxso_module.cpp, src/dxvk/dxvk_shader_key.h
Fixes a crash with a weird nGlide demo.
=> Fix a crash when calling Create*Shader with limited stack space

src/util/config/config.cpp
Fixes flickering on GFX10.3 with RADV/ACO.
=> [util] Set invariantPosition for Monster Hunter World

src/d3d9/d3d9_swapchain.cpp
Some fullscreen games such as `Heroes of Might and Magic V' have a black screen when restored from being minimized (out of focus). The patch has the same behavior that wined3d does here. With this patch the game restores properly even with DXVK, not just wined3d.
=> d3d9: Send necessary messages for full-screen windows during WM_ACTIVATEAPP

src/d3d11/d3d11_swapchain.cpp, src/d3d11/d3d11_texture.cpp, src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_swapchain.cpp, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h, src/dxvk/dxvk_image.h
=> some image stuff that affects d3d9

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_swapchain.cpp, src/dxvk/dxvk_context.cpp
=> D3D9 image layout stuff

src/d3d9/d3d9_device.cpp
As discussed on Discord.
Closes #1947
=> [d3d9] Fix various issues in UpdateTexture

src/vulkan/vulkan_presenter.cpp
Only warn if it's actually available.
=> [vulkan] relax warning about exclusive fullscreen

src/dxgi/dxgi_factory.cpp, src/dxgi/dxgi_swapchain_dispatcher.h
Some overlays and hooks check if the vtable funcs reside in the dxgi.dll module.
Fixes: #1996
=> [dxgi] Implement swapchain dispatcher

src/util/config/config.cpp
Fix the issue in #2003 out of the box.
=> [util] Enable memory track test for Dragon Nest

src/d3d11/d3d11_device.cpp, src/d3d9/d3d9_device.cpp, src/dxvk/dxvk_sampler.cpp
This + some lavapipe bug fixes + the pending Vulkan 1.1 MR should allow DXVK to run on that, at least to a degree.
=> Adjust required features for lavapipe

meson.build
Reduces stdout spam during build.
=> [build] conditionally enable --quiet for glslang

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix offset in UpdateSurface

src/dxgi/dxgi_output.cpp, src/dxgi/dxgi_swapchain.cpp, src/dxgi/dxgi_swapchain.h
=> Report reasonable values from DXGI GetFrameStatistics and GetLastPresentCount

src/dxvk/dxvk_state_cache.cpp, src/util/log/log.cpp, src/util/util_env.cpp, src/util/util_env.h
Fixes #2079.
Supersedes #2080.
=> Handle upper-case file extensions correctly

README.md, dxvk.conf, src/d3d11/d3d11_options.cpp, src/d3d11/d3d11_options.h, src/d3d11/d3d11_swapchain.cpp, src/d3d11/d3d11_swapchain.h, src/d3d9/d3d9_options.cpp, src/d3d9/d3d9_options.h, src/d3d9/d3d9_swapchain.cpp, src/d3d9/d3d9_swapchain.h, src/dxgi/dxgi_interfaces.h, src/dxgi/dxgi_swapchain.cpp, src/dxgi/dxgi_swapchain.h, src/util/config/config.cpp, src/util/meson.build, src/util/util_fps_limiter.cpp, src/util/util_fps_limiter.h, src/vulkan/vulkan_presenter.cpp, src/vulkan/vulkan_presenter.h
Turns out that stalling the queue thread works significantly better than stalling the app thread.
Supersedes #2091.
=> Frame rate limiter (v2)

src/util/config/config.cpp
=> [util] force 60fps for Demon Stone

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix FlushImage extent

src/d3d9/d3d9_device.cpp
Supersedes #2153
Based on Joshs findings.
=> Handle UpdateSurface edge case with compressed mip levels 2

src/d3d9/d3d9_device.cpp
First commit is the equivalent to 5f1629f2cbd93ae48930836237feb0ead1f1034c
Second commit: Fixes #2164.
Third commit: Fixes #2168.
Fourth commit: Fixes parts of #2171
=> [d3d9] Texture upload bug fixes

src/d3d9/d3d9_device.cpp
=> [d3d9] Ignore clear with Count == 0 and non-NULL rect

src/d3d9/d3d9_adapter.cpp, src/d3d9/d3d9_adapter.h, src/d3d9/d3d9_buffer.cpp, src/d3d9/d3d9_buffer.h, src/d3d9/d3d9_common_buffer.cpp, src/d3d9/d3d9_common_buffer.h, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_subresource.h, src/d3d9/d3d9_texture.h
A set of small optimizations and code cleanup for d3d9.
=> Misc. set of D3D9 optimizations and cleanup (part 1)

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_stateblock.cpp, src/d3d9/d3d9_stateblock.h, src/d3d9/d3d9_swapchain.cpp, src/d3d9/d3d9_swapchain.h
More stuff to make more tests not crash.
=> [d3d9] Wine test fixes 1

src/d3d9/d3d9_fixed_function.cpp
=> [d3d9] Implement D3DTOP_BLENDTEXTUREALPHAPM

src/d3d9/d3d9_device.cpp
=> [d3d9] Mark mips as dirty on Clear if needed

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix upload race with default image mapping

src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
=> [dxso] Implement TexDepth

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix parital DS clears with full RT clear

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_swapchain.cpp
Please make it stop. :(
Fixes #2246
=> Latest batch of texture upload fixes

src/d3d9/d3d9_swapchain.cpp
=> [d3d9] Brain-dead gamma ramp validation

src/d3d9/d3d9_adapter.h, src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_format.cpp, src/d3d9/d3d9_format.h
=> [d3d9] Support unsupported formats in LockRect

src/util/config/config.cpp
=> [util] Force 60 fps for Sine Mora EX

src/d3d9/d3d9_adapter.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_fixed_function.cpp, src/d3d9/d3d9_include.h, src/util/util_misc.h
They do the same thing, so why have a custom version.
=> [util] Replace countof with std::size

src/d3d9/d3d9_device.cpp
Fixes shadows in Black Mesa.
Black Mesa clears with RT | Depth. The depth buffer is 4096x4096 and the RT is 2048x2048.
It used to work by accident because DXVK mistakenly did a fast full clear.
@DadSchoorse added a check for the DS size which broke it. https://github.com/doitsujin/dxvk/commit/a75cf2f39d3ee134406e06b6d6e2e7f54f81dc9b
=> [d3d9] Don't clamp clears to the size of RT 0

src/d3d9/d3d9_device.cpp
Small thing I noticed after yesterdays PR.
=> [d3d9] Fix lenient clears

src/dxvk/dxvk_barrier.h
Fix for a *possible* problem. I'm not 100% sure.
=> [dxvk] fix barrier tracking code

src/dxso/dxso_compiler.cpp
=> [dxso] Fix constant buffer debug names

src/d3d9/d3d9_caps.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_shader.cpp, src/d3d9/d3d9_shader.h, src/d3d9/d3d9_state.h, src/d3d9/d3d9_stateblock.cpp, src/d3d9/d3d9_util.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h, src/dxso/dxso_module.cpp, src/dxso/dxso_module.h, src/dxso/dxso_options.cpp, src/dxso/dxso_options.h, src/dxso/dxso_util.h
And some cleanup to texture bind slots and constant buffer uploads.
Fixes #2361
Fixes #2369
=> Copy shader defined constants into UBO

src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_texture.cpp
=> [d3d9] Always upload all managed texture mips after AddDirtyBox call

src/d3d9/d3d9_device.cpp
=> [d3d9] Update FFVS when D3DFVF_PSIZE is specified.

src/d3d9/d3d9_options.cpp
=> [d3d9] Fix float emulation detection.

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp
=> Only enable FETCH4 for single channel texture formats

.github/workflows/test-build-windows.yml, src/dxvk/dxvk_barrier.h, src/dxvk/dxvk_framebuffer.h
Based on https://github.com/HansKristian-Work/vkd3d-proton/pull/969. All credits to @Saancreed.
=> [build] MSVC CI

meson.build, src/d3d11/d3d11_swapchain.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_swapchain.cpp, src/dxbc/dxbc_compiler.cpp, src/dxso/dxso_compiler.cpp, src/dxvk/dxvk_image.cpp
Enables Wimplicit-fallthrough too.
=> Fix some bad switch case fallthroughs

src/dxvk/dxvk_image.cpp
[This didn't age well.](https://github.com/doitsujin/dxvk/pull/2516#discussion_r814787735) :P
=> [dxvk] Force dedicated allocation for exportable images

src/d3d9/d3d9_device.cpp
Fixes #2541.
I seriously have no idea how I managed to miss this.
=> [d3d9] Update buffer seq number in FlushBuffer

src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
=> [dxso] Implement zerowins for Lerp.

meson.build, src/d3d10/meson.build, src/d3d11/meson.build, src/d3d9/meson.build, src/dxbc/meson.build, src/dxgi/meson.build, src/dxso/meson.build, src/dxvk/meson.build, src/spirv/meson.build, src/util/meson.build, src/vulkan/meson.build, tests/d3d11/meson.build, tests/d3d9/meson.build, tests/dxbc/meson.build, tests/dxgi/meson.build
No changes except dropping support for msvc before 15.3.
Didn't initially plan to open a PR for this, I just wanted to see what the result looks like. But especially the compiler arguments section was pretty messy and it's nicer this way. So if you want I can only keep those changes and remove the others.
=> [build] Cleanup build system.

dxvk.conf, src/d3d11/d3d11_annotation.cpp, src/d3d11/d3d11_annotation.h, src/d3d11/d3d11_context.cpp, src/d3d11/d3d11_context.h, src/d3d9/d3d9.def, src/d3d9/d3d9_annotation.cpp, src/d3d9/d3d9_annotation.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_main.cpp, src/d3d9/d3d9_util.h, src/d3d9/meson.build, src/dxvk/dxvk_annotation.h, src/dxvk/dxvk_instance.cpp, src/dxvk/dxvk_options.cpp, src/dxvk/dxvk_options.h, src/util/util_misc.h
fixed global annotations based on WIP branch by Joshua-Ashton 
fixed visual studio build
added config option to enable debug utils in addition to DXVK_PERF_EVENTS=1
=> Global annotations

src/d3d9/d3d9_device.cpp
Fixes an issue with Beyond Good and Evil. (Mentioned in #1545)
Fixes #2559
Thanks @Riesi & @CME42
=> [d3d9] UpdateTexture: Respect automatic mip gen

src/d3d9/d3d9_util.cpp
=> [d3d9] Disable culling when the app passes an invalid value

src/d3d11/d3d11_resource.cpp
=> Fix exported handle types from ::GetSharedHandle and ::CreateSharedHandle to match the respective method

src/util/config/config.cpp
=> [util] Limit Limbo to 60 fps

src/d3d11/d3d11_shader.cpp, src/d3d11/d3d11_video.cpp, src/d3d9/d3d9_fixed_function.cpp, src/d3d9/d3d9_format_helpers.cpp, src/d3d9/d3d9_swvp_emu.cpp, src/dxbc/dxbc_compiler.cpp, src/dxbc/dxbc_compiler.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_device.cpp, src/dxvk/dxvk_device.h, src/dxvk/dxvk_graphics.cpp, src/dxvk/dxvk_shader.cpp, src/dxvk/dxvk_shader.h, src/dxvk/dxvk_swapchain_blitter.cpp, src/dxvk/hud/dxvk_hud_renderer.cpp
Long overdue cleanup of some of the DxvkShader mess. May need some testing.
=> Refactor shader creation

src/util/config/config.cpp
Same issue as with the Warhammer RoR launcher
Closes #2456
=> [util] Force SM1 for the Halo CE SPV3 launcher

src/util/config/config.cpp
Fixes some missing effects for Supreme Commander and it's expansion.
Closes #2638
=> [util] Strict float emulation for Supreme Commander

src/util/util_luid.cpp
Provides at least something here for an adapter.
=> [util] Implement LUID helpers for non-Windows platforms

src/util/config/config.cpp
=> [util] Enable disableMsaa option for Mary Skelter 2

src/util/config/config.cpp
=> [util] enable dialog mode for NFS 3 modern patch

src/util/config/config.cpp
=> [util] enable alphaTestWiggleRoom for Ninja Blade

src/util/config/config.cpp
=> [util] set maxFrameLatency to 1 for YS Origin

src/d3d9/d3d9_device.cpp
The recent rework didn't handle this case.
=> [d3d9] Handle very large Up draws

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_fixed_function.cpp, src/d3d9/d3d9_fixed_function.h, src/d3d9/d3d9_spec_constants.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
Part of a series of work for GPL refactoring.
=> [d3d9, dxso] Refactor spec constants to use a bitfield layout 

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h
=> [d3d9] Clean up fetch4 handling

src/util/config/config.cpp, src/util/log/log.cpp, src/util/util_gdi.cpp, src/util/util_shared_res.cpp, src/util/util_string.h, src/vulkan/vulkan_loader.h
Gets everything building on non-Windows (aside from fps limiter + wsi to come later)
=> [util] Bringup of utils on non-Windows platforms

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_options.cpp, src/d3d9/d3d9_options.h, src/util/config/config.cpp
=> [d3d9+util] Always ignore D3DLOCK_DONOTWAIT

src/util/config/config.cpp
=> [util] Limit Beyond Good and Evil FPS to 60

src/dxso/dxso_compiler.cpp
=> [dxso] normalize 0 to 0 with strict float emulation

src/d3d9/d3d9_fixed_function.cpp, src/dxso/dxso_compiler.cpp
May enable additional compiler optimizations.
=> [d3d9,dxso] Use DemoteToHelperInvocation for alpha test

src/dxgi/dxgi_adapter.cpp, src/dxgi/dxgi_adapter.h, src/dxgi/dxgi_output.cpp
=> [dxgi] Remove leftovers from WSI port

src/d3d11/d3d11_options.cpp, src/d3d11/meson.build, src/dxvk/dxvk_instance.cpp, src/meson.build
These commits are really trivial, and are not worthy of their own PRs.
=> [native] Collection of misc. commits not worthy of their own PRs

src/dxvk/meson.build, src/dxvk/platform/dxvk_sdl2_exts.cpp, src/wsi/meson.build, src/wsi/sdl2/wsi_monitor_sdl2.cpp, src/wsi/sdl2/wsi_platform_sdl2.h, src/wsi/sdl2/wsi_window_sdl2.cpp, src/wsi/wsi_platform.h
=> [wsi] Add SDL2 implementation

meson.build, src/d3d11/d3d11_device.cpp
=> [build] Enable building natively for non-Windows

dxvk.conf
Missed in https://github.com/doitsujin/dxvk/pull/2815
=> [util] remove allowDoNotWait from example config

src/dxso/dxso_compiler.cpp
=> [dxso] Fix write mask for nrm

dxvk.conf
Supersedes https://github.com/doitsujin/dxvk/pull/2878
=> [util] Add missing feature level in example config

include/native/windows/windows_base.h, src/d3d11/d3d11_swapchain.cpp, src/d3d11/d3d11_swapchain.h, src/util/util_win32_compat.h
Mirrors https://github.com/HansKristian-Work/vkd3d-proton/pull/1208.
=> Duplicate frame latency event handle

src/dxvk/meson.build
Fixes build under Steam Runtime Sniper
=> [build] Link against dl for native builds

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h
=> [d3d9] Force D3DTADDRESS_CLAMP for cubes.

meson.build, src/d3d11/d3d11_sampler.cpp, src/d3d11/d3d11_video.h, src/d3d9/d3d9_util.h, src/dxbc/dxbc_compiler.cpp, src/dxvk/dxvk_framebuffer.h
Found something valid earlier today... so lets enable this and clean up some other stuff along the way.
=> Enable warning_level 2 + warning fixes

src/d3d11/d3d11_device.cpp, src/d3d9/d3d9_device.cpp, src/dxbc/dxbc_chunk_isgn.cpp, src/dxbc/dxbc_chunk_isgn.h, src/dxgi/dxgi_swapchain_dispatcher.h, src/util/config/config.cpp
Cherries.
Please check that it is correct.
https://github.com/doitsujin/dxvk/commit/59441b1ff568c181afcf0cc3bdd854df21e1f885 from https://github.com/doitsujin/dxvk/pull/2810
https://github.com/doitsujin/dxvk/commit/5540df955cd8a0963de014fe3b09234b28cea644 & https://github.com/doitsujin/dxvk/commit/3edb0ef11405bf908efcde821d206a28b91901b8 for https://github.com/doitsujin/dxvk/issues/2809
https://github.com/doitsujin/dxvk/commit/8f24093864339edd511ee3cbbf667d4877f5604a from https://github.com/doitsujin/dxvk/pull/2867
https://github.com/doitsujin/dxvk/commit/bfd47ec8767e7589f86ce4b54372669da2963907 from https://github.com/doitsujin/dxvk/pull/2873
https://github.com/doitsujin/dxvk/commit/c49b1ee3909fd48bde7598de9c60c3b53916d9dd for https://github.com/doitsujin/dxvk/issues/2879 …
=> Various cherry picks for 1.10.x

src/util/sync/sync_spinlock.h, src/util/util_bit.h, src/util/util_vector.h
=> Support for ARM64

src/dxso/dxso_compiler.cpp
=> [dxso] Use a * (y - x) + x for lerp.

README.md
=> [meta] remove --with-d3d10 from readme

src/d3d9/d3d9_swapchain.cpp, src/dxgi/dxgi_swapchain.cpp, src/wsi/sdl2/wsi_window_sdl2.cpp, src/wsi/win32/wsi_window_win32.cpp, src/wsi/wsi_window.h
=> [d3d9] Do not set window size and position when restoring from fullscreen state

src/d3d11/d3d11_context_imm.cpp, src/d3d11/d3d11_context_imm.h, src/d3d11/d3d11_context_state.h
Fixes refcount asserts causing crashes in BGFX applications.
=> [d3d11] Refcount fixes

src/d3d9/d3d9_fixed_function.cpp
Backport https://github.com/doitsujin/dxvk/pull/2930
=> Backport precise matrix ops for pico park

src/dxso/dxso_compiler.cpp, src/util/config/config.cpp
https://github.com/doitsujin/dxvk/pull/2932
https://github.com/doitsujin/dxvk/pull/2936
https://github.com/doitsujin/dxvk/pull/2939
=> a few 1.10.x backports

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_interface.cpp, src/d3d9/d3d9_interface.h, src/d3d9/d3d9_interfaces.h, src/d3d9/d3d9_interop.cpp, src/d3d9/d3d9_interop.h, src/d3d9/d3d9_surface.cpp, src/d3d9/d3d9_texture.cpp, src/d3d9/d3d9_texture.h, src/d3d9/d3d9_volume.cpp, src/d3d9/meson.build
Should provide everything needed for VR.
=> [d3d9] Add VkInterop interfaces

src/d3d9/d3d9_device.cpp
Fixes #2946
I tested Stalker and couldn't reproduce the issue that made us revert it back then.
=> Bring back degenerate viewport commit

src/d3d9/d3d9_vertex_declaration.cpp, src/d3d9/d3d9_vertex_declaration.h
Fixes #2969
(The last commit fixes it.)
I need to verify that this is what actually happens on Windows.
cc @kdobrowo
=> Vertex declaration fixes

.github/workflows/artifacts.yml, .github/workflows/test-build-windows.yml
Fixes Node.js 12 deprecation warning.
=> [build] Update github actions

VP_DXVK_requirements.json
Profiles Schema 0.8.1 allows having a single section for history and contributors.
Simplifying things toward something which should probably have been the design from start...
=> Profiles: Factorize history and contributors sections using schema 0.8.1

src/dxgi/dxgi_factory.cpp, src/dxgi/dxgi_swapchain_dispatcher.h
=> [dxgi] Store device pointer in DxgiSwapChainDispatcher

src/d3d9/d3d9_common_texture.cpp
We kind of need dcc on GFX8/9.
=> [d3d9] Fix OptimizeLayout with feedback loop usage.

src/util/config/config.cpp
Fixes https://github.com/doitsujin/dxvk/issues/3029
=> [util] Set Fallout 3 to Nvidia vendor id

src/util/config/config.cpp
Add support for h1-mod.exe
Read more: https://github.com/h1-mod/h1-mod
=> Support for MW:R H1-Mod

src/d3d9/d3d9_format.cpp, src/d3d9/d3d9_format.h, src/d3d9/d3d9_format_helpers.cpp, src/d3d9/meson.build, src/d3d9/shaders/d3d9_convert_w11v11u10.comp
Used in D3D8 games. (#1498 and Indiana Jones)
=> [d3d9] Implement converter for W11V11U10

src/util/config/config.cpp
Closes https://github.com/doitsujin/dxvk/issues/3024
Will make a note to check if the couple individual games in the collection behave the same.
=> [util] Limit fps to 60 for some WayForward games

src/util/config/config.cpp
Temporary (maybe) workaround for https://github.com/doitsujin/dxvk/issues/3038 until devs have looked into it more.
=> [util] Enable apitraceMode for Sonic & All-Stars Racing Transformed

src/util/config/config.cpp
https://github.com/ValveSoftware/Proton/issues/6318
Props to @Blisto91 for noticing it.
=> [util] Disable DC Single Use Mode for Cardfight!! Vanguard Dear Days

src/util/config/config.cpp
Closes https://github.com/doitsujin/dxvk/issues/3061
=> [util] Set Black Mesa customVendorId to Nvidia

src/util/util_bit.h
=> Couple of MSVC warning fixes

src/util/config/config.cpp
Closes https://github.com/doitsujin/dxvk/issues/3078
=> [util] disable floatControls for Bad Company 2

src/d3d9/d3d9_device.cpp
=> [d3d9] Handle DS texture uploads

src/wsi/wsi_edid.cpp
If info is null then we shouldn't pass it around.
Also improve formatting a bit.
Found by @K0bin .
=> [wsi] Fix crash when parsing EDID fails

src/util/config/config.cpp
Closes https://github.com/doitsujin/dxvk/issues/3118
=> [util] Set TRAHA Global to Intel vendor id

VP_DXVK_requirements.json, src/d3d11/d3d11_swapchain.cpp, src/d3d11/d3d11_swapchain.h, src/dxvk/dxvk_adapter.cpp, src/dxvk/dxvk_device_info.h, src/dxvk/dxvk_extensions.h, src/vulkan/vulkan_loader.h, src/vulkan/vulkan_presenter.cpp, src/vulkan/vulkan_presenter.h
Implements CheckColorSpaceSupport, SetColorSpace and SetHDRMetadata.
=> [d3d11] Implement HDR swapchain features

src/util/config/config.cpp
Redo of https://github.com/doitsujin/dxvk/pull/3114 cuz i suck at git.
=> [util] Set Secret World Legends launcher to SM 2

src/dxgi/dxgi_options.cpp
Unreal Engine 4 titles use AGS/NVAPI to try and enable HDR globally.
They can key this off IDXGIOutput::GetDesc1's ColorSpace being HDR10.
Many of these UE4 games statically link against AGS.
This is a problem as when UE4 tries to enable HDR via AGS, it does not check if AGSContext, and the display info etc are nullptr unlike the rest of the code using AGS. So we need to special-case UE4 titles to disable reporting a HDR when they are in DX11 mode.
The simplest way to do this is to key off the fact that all UE4 titles have an executable ending with "-Win64-Shipping".
We check if d3d12.dll is present, to determine what path in UE4 we are on, as there are some games that ship both and support HDR. (eg. The Dark Pictures: House of Ashes, 1281590)
Luckily for us, they only load d3d12.dll on …
=> [dxgi] Workaround UE4 DX11 + HDR crashes

src/dxvk/dxvk_memory.cpp
=> Sekiro memory workaround thingy

src/dxbc/dxbc_compiler.cpp, src/dxvk/dxvk_compute.cpp, src/dxvk/dxvk_compute.h, src/dxvk/dxvk_graphics.cpp, src/dxvk/dxvk_pipemanager.cpp, src/dxvk/dxvk_pipemanager.h, src/dxvk/dxvk_shader.cpp, src/dxvk/dxvk_shader.h, src/dxvk/dxvk_state_cache.cpp, src/dxvk/dxvk_state_cache.h, src/dxvk/dxvk_state_cache_types.h
Reusing an existing fragment shader should reduce stutter in these situations.
=> Use pipeline libraries for tess/geom pipelines

src/d3d11/d3d11_context.cpp, src/d3d9/d3d9_adapter.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_query.cpp, src/d3d9/d3d9_util.h, src/util/config/config.cpp
Well this was a bit more than i anticipated.
If there is anything you think should be added or removed just say so
=> Final backports (hopefully)

src/d3d9/d3d9_device.cpp
=> Backport RE4 fix

src/util/config/config.cpp
Closes https://github.com/doitsujin/dxvk/issues/3145
Verified ingame
=> [util] Limit Battle Fantasia Revisited Edition to 60fps

src/d3d9/d3d9_state.h, src/d3d9/d3d9_stateblock.h
=> [d3d9] Fix capturing lights in state block

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix SWVP performance regression

src/util/config/config.cpp
Closes #3336
This was thought to be the best work around after all
=> [util] Disable allowDirectBufferMapping for Dark Romance: Vampire in Love

src/d3d9/d3d9_device.cpp
Fixes #3351
https://github.com/doitsujin/dxvk/commit/af0009c5debe33cffd5e412d0ff3d8adcd064c55 caused us to use the wrong aspectMask for the texture converter target imge view. This fixes that.
Additionally, Unravel ended up trying reading back data from the image to the staging buffer. The texture converter only handles uploads, so the data it used to get out of it, was wrong. Thankfully it doesn't care about the data in the buffer and also uses DISCARD.
I changed it so we respect DISCARD. (we have logic to remove the flag in some cases but didn't do anything with it after that.)
I also made it keep the mapping buffer around for textures that go through the texture converter. The clean fix would be to write compute shaders that unpack multiplane and macro pixel formats but given that no …
=> [d3d9] Handle a bunch of texture converter edge cases

src/util/config/config.cpp
I suspect the change for Nioh 1 should also be applied to Nioh 2, but I don't have this game to test.
=> Update some app configs for Tecmo Koei games

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_swapchain.cpp, src/d3d9/d3d9_swapchain.h
=> [d3d9] Handle swapchain OOM and other errors more gracefully

src/d3d9/d3d9_swapchain.cpp, src/d3d9/d3d9_swapchain.h
=> [d3d9] Fix stupid variable name

src/util/config/config.cpp
=> [util] Set floatEmulation to Strict for Halo Online

src/wsi/win32/wsi_monitor_win32.cpp
Fixes wrong monitor order in the Witcher 3 and maybe somewhere else (introduced with "[dxgi] Only enumerate outputs which belong to the adapter or associated iGPU") observed on some dual gpu / dual monitor setups.
=> [dxgi] Preserve system monitor sort order in enumMonitors()

src/d3d9/d3d9_device.cpp
Otherwise we can end up with feedback loops on RTs with a 0 color mask.
Closes: #3447
=> [d3d9] Unbind RTs which are unwritten by a PS

src/dxso/dxso_module.cpp
=> [dxso] Fix RT mask for SM1

README.md
A picked and condensed version of https://github.com/doitsujin/dxvk/pull/3216 and https://github.com/doitsujin/dxvk/pull/3101 that should hopefully be good enough for everyone.
=> [meta] Clarify readme setup instructions

src/util/util_string.cpp
=> [util] Fix UTF8 encodeTypedChar for 4 byte chars

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_swapchain.cpp
Fixes #3489
I didn't intend #3486 to get merged yet. The plan was to get a review (which is why it wasn't a draft) and do more testing. Anyway, shit happens, lets fix it.
=> Reset cleanup & bugfix

src/util/config/config.cpp
The message you get before the change
https://www.protondb.com/app/1237980
=> [util] Report NVIDIA for Star Wars Battlefront as it errors out on AMD

src/d3d11/d3d11_context.cpp, src/d3d11/d3d11_device.cpp, src/d3d11/d3d11_view_dsv.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_util.h, src/dxvk/dxvk_adapter.cpp, src/dxvk/dxvk_cmdlist.h, src/dxvk/dxvk_constant_state.h, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h, src/dxvk/dxvk_context_state.h, src/dxvk/dxvk_device_info.h, src/dxvk/dxvk_extensions.h, src/vulkan/vulkan_loader.h
Marked as draft as have not tested yet, but should be there.
=> Implement depth bias control

src/d3d9/d3d9_device.cpp
=> Make m_activeHazardsRT refer to texture and not rt/surface

src/util/config/config.cpp
=> [util] Fix Modern Warfare 2 Campaign Remastered config

src/util/config/config.cpp
Works out of the box now since either https://github.com/doitsujin/dxvk/pull/3486 or https://github.com/doitsujin/dxvk/pull/3490
Closes https://github.com/doitsujin/dxvk/issues/3116
=> [util] Remove Secret World Legends config

src/util/config/config.cpp
Improves CPU bound performance
=> [util] Set Cached Dynamic Resources for d3d11 Vindictus

README.md, src/dxvk/dxvk_instance.cpp
Being more direct here might lead to less confusion and questions. Also moved driver note in readme up into the How to use section so it's near the top and more visible.
=> Make driver requirements slightly more visible

src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h
=> [dxso] Don't assume 32 registers.

README.md
=> [meta] Document DXVK_CONFIG in readme

src/util/config/config.cpp
=> [util] Fix incorrect config option name

src/util/sync/sync_signal.h
I found a possible micro-optimization opportunity in the fence code. When a fence has been missed, we can avoid locking *most* of the time via the double-checked locking pattern. We still lock before a second check in case the scheduler caused us to miss the fence. If the scheduler did cause us to miss the fence, we can drop the lock prior to executing the callback function, as a second micro-optimization.
It compiles. I have not tried running it. I figured I would post this here to get feedback before trying to figure out what a sane runtime test would be.
=> Micro-optimize locking in fences

src/util/util_bit.h
Ref: https://en.wikipedia.org/wiki/Elbrus_(computer)
=> [util] Fix e2k build

dxvk.conf, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_options.cpp, src/d3d9/d3d9_options.h, src/util/config/config.cpp
=> Add config option to disable rejecting Reset if theres still losable resources alive

src/dxso/dxso_compiler.cpp
=> Fix float issue in Gujian 2

src/d3d9/d3d9_device.cpp, src/util/config/config.cpp
=> Operation Flashpoint: Red River fixes

src/d3d9/d3d9_device.cpp
=> [d3d9] Handle null IBO when uploading data for draw

src/d3d9/d3d9_device.cpp
Tests show that D3D9 does this, so it's probably not a bad idea if we do it too, in order to avoid leaks.
=> [d3d9] Unbind buffers in EndScene & Reset

src/d3d9/d3d9_device.cpp
I messed up. Spotted by WinterSnowfall.
=> [d3d9] Fix stream count in Reset

src/d3d11/d3d11_device.cpp
Not sure if this is entirely accurate, but works fine in my limited testing. Please let me know if this is correct or if there is any changes I should make.
=> Implement D3D11DXGIDevice::EnqueueSetEvent

src/dxgi/dxgi_swapchain.cpp, src/dxgi/dxgi_swapchain.h
=> Implicitly set HDR color space for RGBA16_FLOAT swap chains

src/util/config/config.cpp
=> Support for MW:R H2M-Mod

src/util/config/config.cpp
Prevents the games from black screening on Alt-Tab
=> [util] Add configs for Delta Force Xtreme 1 & 2

src/d3d9/d3d9_device.cpp
=> [d3d9] Handle mismatching vertex layout and vbo strides

.github/workflows/artifacts.yml, .github/workflows/test-build-windows.yml
Silences the CI deprecation warnings
=> [CI] Update CI actions

src/util/config/config.cpp
Works around flickering on character faces
closes #4045
=> [util] Set longMad for Ghostbusters Remastered

src/util/config/config.cpp
New Vegas: Fixes various visual issues with some effects in mods such as New Vegas Reloaded. White spots/shapes, black streaks across the screen (rain?) and probably more.
Dragonshard: Works around massive FPS decreases in some scenes
=> [util] Add configs for Fallout New Vegas and DnD Dragonshard

meson.build
Addresses #4025.
CC @smcv @flibitijibibo
=> [build] Zero-pad soversion components as necessary

src/d3d9/d3d9_cursor.cpp, src/d3d9/d3d9_cursor.h
A few hardware cursor nits, cherry picked from #3841.
=> [d3d9] Hardware cursor fixes

LICENSE
As suggested by Misyl on Discord
=> [meta] Add Robin Kertels to LICENSE file

dxvk.conf
Somehow ~~Palapa~~... I mean, I missed to remove this bit.
=> [util] dxvk.conf cleanup

dxvk.conf, src/dxgi/dxgi_adapter.cpp, src/dxgi/dxgi_options.cpp, src/dxgi/dxgi_options.h, src/util/config/config.cpp
=> GTA IV VRAM fix

src/d3d9/d3d9_mem.cpp
Issue: https://github.com/doitsujin/dxvk/issues/4183
=> [build] added <algorithm> header for failed subcommand fix - `remove_if`

README.md
see https://github.com/doitsujin/dxvk/issues/4265
=> [meta] Note DLLs need native override in readme

src/util/util_small_vector.h
=> [util] Fix small_vector move constructor

src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_common_texture.h
=> [d3d9] Only add meta image usage after determining layout

src/util/config/config.cpp
Game can get stuck when loading at framerates above 1000
Edit: Changed to 240fps
=> [util] Cap Prince of Persia (2008) max fps

src/util/config/config.cpp
Visual glitches can occur at very high fps
=> [util] Cap fps for F.E.A.R 1 & expansions

src/d3d8/d3d8_device.cpp
Technically shouldn't be needed, but it addresses some problems @Blisto91 has been having with Rainbow Six 3 (in windowed mode), which sets the viewport a whole pixel wider than the render target, after some window resize shenanigans cause the swapchain to be reset like 3 times and end up with a width of 1 pixel less than the initial size that the game sets it to.
I have no idea why this happens, but this workaround should be pretty harmless.
=> [d3d8] Relax viewport validation in windowed mode

src/d3d9/d3d9_device.cpp
=> [d3d9] Resolve whole image in StretchRect

src/d3d9/d3d9_device.cpp
=> [d3d9] Fix StretchRect fast-path resolve

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h
=> [d3d9] Fix render target null pointer deref

src/dxvk/dxvk_graphics.cpp
Shuts up validation layers in Fallout 4 and presumably any game that uses sample rate shading. This doesn't functionally change anything since this only affects pipelines where the mismatched state is dynamic anyway.
=> Sanitize multisample state for fragment output libraries

src/d3d11/d3d11_initializer.cpp, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h
Should fix a validation error in Tales of Arise that has the potential to actually be problematic.
=> Fix misaligned image uploads on transfer queue

src/dxvk/dxvk_memory.cpp, src/dxvk/dxvk_memory.h, src/dxvk/dxvk_queue.cpp
Supersedes  #4381,  but currently untested.
=> Remove memory worker

src/util/config/config.cpp
Looks fine without since dxvk 2.0
=> [util] Remove The Old Republic config

src/d3d11/d3d11_context.cpp, src/d3d11/d3d11_context.h, src/d3d11/d3d11_device.cpp, src/d3d11/d3d11_device.h
Might fix some more issues with S-K.
=> Devirtualize D3D11 method forwarding

src/d3d11/d3d11_context_imm.cpp, src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_format_helpers.cpp, src/d3d9/d3d9_format_helpers.h, src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_context.h, src/dxvk/dxvk_descriptor.cpp, src/dxvk/dxvk_descriptor.h, src/dxvk/dxvk_device.cpp, src/dxvk/dxvk_device.h
Needs some testing, but at least d3d9-nv12.exe still works (without validation errors). Blocks #4378.
=> Remove format conversion context

src/d3d9/d3d9_common_texture.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/dxso/dxso_compiler.cpp
I hope those are genuinely a bit useful and not just describing the obvious.
@WinterSnowfall pls review.
=> D3D9 code comments improvements

src/dxvk/dxvk_adapter.cpp, src/dxvk/dxvk_device_info.h, src/dxvk/dxvk_extensions.h, src/dxvk/dxvk_memory.cpp, src/vulkan/vulkan_loader.h
Might help Nvidia, shouldn't be scary.
=> [dxvk] Enable and use VK_EXT_pageable_device_local_memory if supported

package-release.sh
Copy paste from package-native.sh. These options are very convenient for tinkering. Thank you.
=> Add --64-only and --32-only build options to package-release.sh

src/util/config/config.cpp
=> [util] Add Sims 2 Content Manager & HomeCrafter Plus

src/util/config/config.cpp
Verified The hurricane of the Varstray in game.
Closes #4568 
Also took the liberty of merging the two configs from https://github.com/doitsujin/dxvk/pull/4566
=> [util] Merge Arcana Heart 3 configs & cap Hurricane of the Varstray

src/d3d8/d3d8_d3d9_util.h, src/d3d8/d3d8_device.cpp, src/d3d8/d3d8_device.h, src/d3d8/d3d8_interface.cpp, src/d3d8/d3d8_state_block.cpp, src/d3d8/d3d8_state_block.h, src/d3d8/d3d8_subresource.h, src/d3d8/d3d8_surface.cpp, src/d3d8/d3d8_surface.h, src/d3d9/d3d9_bridge.cpp, src/d3d9/d3d9_interface.cpp
A few d3d8 enhancements, tentatively targeted to land after 2.5.3. Currently WIP.
=> [d3d8] d3d9 bridge & various other enhancements

src/wsi/meson.build, src/wsi/win32/wsi_monitor_win32.cpp
Setupapi getting unloaded is the reason why #4662 is blowing up on my end.
=> [dxvk] Add setupapi as a Windows WSI dependency

src/util/config/config.cpp
=> [util] Disable dcSingleUseMode for Cardfight!! Vanguard Dear Days 2

src/dxvk/dxvk_cs.cpp, src/dxvk/dxvk_stats.h, src/dxvk/hud/dxvk_hud_item.cpp, src/dxvk/hud/dxvk_hud_item.h
Same way we estimate the GPU load.
=> [dxvk] Add CS thread load to the HUD

src/d3d11/d3d11_device.cpp, src/d3d11/d3d11_on_12.cpp, src/d3d11/d3d11_on_12.h
Functionally trivial, just headers are a mess right now.
=> Implement ID3D11On12Device1

src/dxvk/dxvk_cs.h
=> Be more conservative with CS data alignment

src/dxvk/dxvk_presenter.cpp
Turns out that present fences are in fact signaled on error. Also account for `swapchain_maintenance1` not being supported.
=> Fix synchronization on swapchain tear-down

src/d3d9/d3d9_swapchain.cpp
Seems to work as-is, at least when forcing `d3d9.presentInterval=2` via config.
=> [d3d9] Remove double presents with SyncInterval > 1

src/d3d8/d3d8_batch.h, src/d3d8/d3d8_device.cpp, src/d3d8/d3d8_interface.cpp, src/d3d8/d3d8_resource.h, src/d3d8/d3d8_state_block.cpp, src/d3d8/d3d8_surface.cpp, src/d3d8/d3d8_texture.h, src/d3d8/d3d8_wrapped_object.h, src/d3d9/d3d9_bridge.cpp, src/d3d9/d3d9_common_texture.cpp, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_fixed_function.cpp, src/d3d9/d3d9_format.cpp, src/d3d9/d3d9_shader.h, src/d3d9/d3d9_shader_validator.cpp, src/d3d9/d3d9_shader_validator.h, src/d3d9/d3d9_state.h, src/d3d9/d3d9_stateblock.h, src/d3d9/d3d9_swapchain.cpp, src/d3d9/d3d9_window.h, src/dxso/dxso_analysis.h, src/dxso/dxso_compiler.cpp, src/dxso/dxso_compiler.h, src/dxso/dxso_module.h, src/dxvk/dxvk_shader_key.h, src/dxvk/dxvk_util.h, src/util/util_bit.h
I've thrown Cppcheck at the d3d8 and d3d9 folders and basically this has come out of it. Some stuff is potentially scary and everything definitely needs a second pair of eyes. Happy to clarify what the problem was on each change.
Currently WIP.
=> [d3d8/9] Some static analysis-based rework and corrections

src/dxvk/dxvk_context.cpp
So yeah, apparently this hangs Renoir (Vega) and potentially some other (old) AMD GPUs that nobody really tests anymore as well.
Gonna file a mesa issue and see where that goes, will merge the workaround if no quick fix can be found.
=> [dxvk] Disable sparse zero buffer on pre-RDNA AMD hardware

src/dxbc/dxbc_options.cpp
=> [dxbc] Always export point size on ANV

src/dxvk/dxvk_context.cpp, src/dxvk/dxvk_device.cpp, src/dxvk/dxvk_device.h
getting a bit of a deja vu here
=> Work around broken resolve attachments with format interpretation

src/d3d11/d3d11_context.cpp, src/d3d11/d3d11_context_imm.cpp, src/d3d11/d3d11_context_imm.h, src/util/util_flush.cpp, src/util/util_flush.h
May or may not improve things in some cases.
=> Rework tiler submission heuristic (again)

src/util/config/config.cpp
=> [util] Enable Strict floatEmulation for Thumper

src/d3d11/d3d11_context.cpp, src/d3d11/d3d11_context.h, src/d3d11/d3d11_video.cpp, src/d3d11/d3d11_video.h, src/dxvk/dxvk_context.cpp
Needs some targeted testing, but tldr is that we can properly clear planar video views now as a follow-up to #4872.
=> Rework ClearView

src/d3d11/d3d11_device.cpp, src/d3d11/d3d11_device.h, src/d3d11/d3d11_texture.cpp, src/d3d11/d3d11_texture.h
Untested, but relevant for VR workloads.
=> Fix image relocation on interop interfaces

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h, src/d3d9/d3d9_util.cpp
Fixes #4881
D3D9 Tests confirm @WinterSnowfall theory.
=> Allow ATOC with nonmaskable textures

src/util/config/config.cpp
=> [util] Set memoryTrackTest & maxAvaliableMemory for Pirate Hunter

src/dxvk/hud/dxvk_hud_item.cpp, src/dxvk/hud/dxvk_hud_item.h
Should fix missing frame time details on Nvidia.
=> [hud] Pass proper uniform texel buffer view when rendering

src/util/config/config.cpp
Backport for various simple config commits
=> Various V2.6.x config backports

src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_device.h
=> [d3d9] TF2 fixes

dxvk.conf, src/d3d8/d3d8_device.cpp, src/d3d8/d3d8_interface.cpp, src/d3d8/d3d8_interface.h, src/d3d9/d3d9_device.cpp, src/d3d9/d3d9_interface.cpp
Fixes the last remaining failing Wine cursor test.
=> [d3d8/9] Yet another motley crew of fixes

src/util/config/config.cpp
The game works great, RTGI, RT reflections and all.
=> [util] Enable dummy composition for Anno 117

src/util/config/config.cpp
=> [util] Extend Far Cry 5 config to New Dawn

src/d3d9/d3d9_surface.cpp
Another day in the land of the corner-case API... long story short, I was a bit too aggressive (or maybe lazy) when I implemented the dimensions checks on surface locks, because, as it turns out SYSTEMMEM surfaces can be locked with zero-length pRects. And of course there's a game that does that, namely "Legends of Eisenwald".
It simply locks and unlocks the same SYSTEMMEM surface with a `pRect = [{left = 481, top = 443, right = 481, bottom = 443}]`, twice at the start of every frame when on the world map. It doesn't copy anything, nor does it use the locks otherwise, just a lock and unlock in quick succession... twice. Yeah...
Zero-length locks are invalid however on block-aligned formats and there are Wine tests for that, so I've taken the route of relaxing the specific validation which …
=> [d3d9] Relax lock dimension checks on SYSTEMMEM surfaces
