doitsujin/dxvk

src/d3d11/d3d11_buffer.cpp
src/d3d9/d3d9_common_buffer.cpp

Otherwise DXVK removes both flags at once and we may end up with uncached memory.
Further improves performance in Tomb Raider Anniversary.

[d3d9+d3d11] Remove DEVICE_LOCAL flag when forcing cached memory

---

src/util/config/config.cpp

Games can bug out at higher fps, especially the physics, and sometimes in progress breaking ways.

[util] Limit fps for some Tomb Raider games

---

src/d3d9/d3d9.def
src/d3d9/d3d9.sym
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_include.h
src/d3d9/d3d9_main.cpp
src/d3d9/d3d9_on_12.cpp
src/d3d9/d3d9_on_12.h
src/d3d9/meson.build

[d3d9] Stub out D3D9On12 interfaces

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp

The behavior on both native AMD (thanks @Blisto91) and WineD3D is as follows:
- if IDirect3D8/9::GetDeviceCaps() is called, MaxVertexBlendMatrixIndex is set to 0
- if IDirect3DDevice8/9::GetDeviceCaps() is called in HWVP mode, MaxVertexBlendMatrixIndex is set to 8
- if IDirect3DDevice8/9::GetDeviceCaps() is called in SWVP mode, MaxVertexBlendMatrixIndex is set to 255
The last bit seems to be in line with what the docs state:
> DWORD value that specifies the maximum matrix index that can be indexed into using the per-vertex indices. The number of matrices is MaxVertexBlendMatrixIndex + 1, which is the size of the matrix palette. If normals are present in the vertex data that needs to be blended for lighting, then the number of matrices is half the number specified by this capability flag. …

[d3d9] Properly expose the MaxVertexBlendMatrixIndex capability

---

src/dxso/dxso_compiler.cpp

Fixes shadows in Test Drive Unlimited 2.
Closes: #3469

[dxso] Respect all PS input elements for registers

---

src/d3d9/d3d9_fixed_function.cpp

Fixes #3474
It uses the texcoord at slot `index`, not the one at slot `i`.

[d3d9] FF: Fix using wrong texCoord mask

---

src/util/config/config.cpp

Currently when Red Dead Redemption 2 is running the Rockstar launcher, and social club each use over 600MB of VRAM. The root cause of this is DXVK creating two memory pools of 256MB for read, and read/write resources. Reducing the max chunk size to 1MB reduces the memory usage of each to around 40MB.

[util] Set maxChunkSize to 1 for the Rockstar launcher and social club

---

dxvk.conf
src/d3d9/d3d9_common_buffer.cpp
src/d3d9/d3d9_common_buffer.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/util/config/config.cpp

Feels good to remove hacks.
Thanks to Axel Davy of Gallium Nine fame for telling me about the SWVP edge case here.
8bf11fd helps Injustice: Gods Among Us.

Buffer locking cleanup

---

src/d3d9/d3d9_common_buffer.cpp
src/d3d9/d3d9_common_buffer.h
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_stateblock.cpp
src/d3d9/d3d9_stateblock.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h
src/util/config/config.cpp

[d3d9] Reject Reset if there's any remaining DEFAULT resources

---

dxvk.conf
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/d3d11/d3d11_sampler.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h

`d3d9.clampNegativeLodBias` addresses https://github.com/doitsujin/dxvk/issues/2779
a negative lod bias can help for some d3d9 games to look better
while clamping the negative load bias can also help some other games too 😄
Thanks to [@Kaldaien](https://github.com/Kaldaien) for giving me the code for clamping in D3D9!

[d3d9/d3d11] add samplerLodBias to d3d9 and clampNegativeLodBias for both d3d9 and d3d11

---

src/util/config/config.cpp

I'm not entirely sure how many people have the game on GOG, but the executable name is different than the one on Steam.
It's a good idea to leverage the game's builtin framerate limiter flag, but in case users are not aware of its existence this ensures they won't think the game is broken with dxvk.

[util] Match on the GOG version of KoF XIII as well

---

src/dxvk/dxvk_openvr.cpp
src/dxvk/dxvk_openxr.cpp

Fixes GTA V randomly crashing on start after recent update.
The crash is due to DxvkXrProvider::queryDeviceExtensions() calls wineopenxr functions while openxr is already unloaded. The logic with GetModuleHandle() can only work correctly if DxvkXrProvider class is a process global singleton. This is not the case during GTA V startup as different instances of the object are present in both dxgi.dll and d3d9.dll and that races resulting in premature library unloading.

[dxvk] Always use LoadLibrary in OpenXR extension provider

---

src/util/config/config.cpp

Reduces GPU VRAM usage of EADesktop.exe from 162MB to 6MB
Before
After

[util] Set maxChunkSize to 1 for EA App

---

src/d3d9/d3d9_common_buffer.h

Part of #3411
I have found in debugging games with d8vk you could sometimes get weird default values for m_mapFlags

[d3d9] Initialize m_mapFlags to 0

---

src/dxso/dxso_compiler.cpp
src/dxso/dxso_compiler.h

Part of #3411
Was previously unimplemented.

[dxso] Implement bem instruction

---

src/d3d9/d3d9_common_texture.cpp

[d3d9] Fix std::hex in D3D9CommonTexture

---

src/util/util_vector.h

There is no good reason to expect games will have aligned the data they're passing in.

[util] replaceNaN: Use unaligned SIMD _mm_loadu_ps

---

src/util/config/config.cpp

Intros, menu and ui animations are playing way too fast, also causing input issues.
---
Executable name `Game.exe` is unfortunately a bit vague but:
Tested with
```
[Game.exe]
d3d9.maxFrameRate = 60
```
and running the game via steam with `DXVK_CONFIG_FILE=/mnt/games/dxvk-temp/dxvk-steinsgate.conf %command%`.

[util] Limit STEINS;GATE ELITE to 60 fps

---

src/util/util_string.h

Part of #3411
Used by d3d8 to parse a complex config option (`forceVsDecl`)

[util] Add str::split

---

src/d3d9/d3d9_common_buffer.cpp

Revert "[d3d9] Only use direct buffer mapping for DYNAMIC buffers"

---

src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_interface.cpp
src/d3d9/d3d9_interface.h
src/d3d9/meson.build

Part of #3411 
D3D9Bridge is how d3d8 is can affect the behavior of d3d9 and use the dxvk backend in cases where that's needed. This PR does not implement every feature that it can use, it just adds the interface.

[d3d9] Add D3D8Bridge for d3d8

---

src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h

Adds a method to D3D8Bridge to change the API displayed on the HUD.

[d3d9] Allow changing API name for d3d8

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_query.cpp
src/dxvk/dxvk_device.h
src/dxvk/dxvk_queue.cpp
src/dxvk/dxvk_queue.h

Needs testing.
The flush heuristic itself already works well for D3D11 in practice, with major benefits being that:
- There is no race condition with the pending submission count, unlike in the old code
- We can flush at CS chunk boundaries, even during extremely long command sequences where we otherwise wouldn't
- CPU timing is no longer used as a source of information, which makes this a lot more consistent
- Resource readback latency in general should be **much** lower.

D3D9: Port flush heuristic from D3D11

---

meson.build

Since [1], Wine's supports and uses DWARF 4 as default. Make use of it, which should fix inlined stacks and some other small details.
[1]: https://www.winehq.org/pipermail/wine-devel/2021-November/201333.html

build: Switch symbols to DWARF 4

---

src/util/config/config.cpp

The game has 3 v-sync options but doesn't explain what they do. 
0 = 60 FPS
1 = Monitor Refresh Rate
2 = 30 FPS
Framerate is capped at 60 in missions and then up to monitor refresh in the main menu and tavern area
This PR would provide a better default experience for people using option 1 with high refresh displays

[util] BLADESTORM: Nightmare - Game speed increases when above 60 FPS

---

src/util/util_vector.h

Part of #3411 
Otherwise `_mm_store_ps` can fail

[util] replaceNaN: Align result

---

src/d3d9/d3d9_device.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h

Some apps such as level editors such as Hammer World Editor, some GUI apps/launchers etc use window overrides in presentation.
Previously we'd remake a new surface every time, which was incredibly slow making these apps basically unusable.
Now we keep one surface + swapchain + image views around per window/window override we have, along with the frame latency objs + frame counter. (Obviously an app may present to multiple windows in a frame, so for frame latency purposes we track that per-window.

[d3d9] Keep 1 presenter per swapchain window

---

src/util/config/config.cpp

The higher uneven framerates [can bug the game out](https://www.pcgamingwiki.com/wiki/The_Incredibles#Dash_Glitch). The horrible frame timings is allegedly because even though it appears uncapped besides vsync it will try to reach for 60fps. Even then it has some frame time issues, so opted to cap it just below.
<details>
<summary>Screenshots</summary>
uncapped
60
59
</details>

[util] Limit fps in The Incredibles

---

.github/workflows/test-build-windows.yml

The choco package is extremely outdated and breaks now.
Similar fix in https://github.com/HansKristian-Work/vkd3d-proton/pull/1628.

[ci] Download glslangValidator.exe directly rather than using choco.

---

src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_resource.cpp
src/d3d11/d3d11_texture.cpp

Fixes Night Security (steam id 2367230) crash upon reaching 2nd floor during the first mission (soon after beginning of the game, at "1F" to "2F" level transition). The crash is due to shared texture import failure which is due to the mess between handle types (wrongly determined from flags). The texture is created with (D3D11_RESOURCE_MISC_SHARED | D3D11_RESOURCE_MISC_SHARED_NTHANDLE) which looks confusing from the point of view of currently present logic but actually this is the only way one can create a texture with NT shared handle without using D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX (see below).
Only patch 2 is strictly need for the game, while patch 1 fixes handle (and the shared memory under it) possible leak and the rest are straightening the thing up by adding validations (also …

[d3d11] Shared texture flags handling fixes

---

README.md
dxvk.conf

Adds a Graphics Pipeline Library section to the readme and removes a dead option from example config while renaming another.
The new readme section is mostly copy pasted from the dxvk 2.0 release notes with some minor changes.

Add Graphics Pipeline Library readme section and cleanup example config

---

meson.build

Fixes the CI failing with the name change even though the changelog says the old name should have a symlink. https://github.com/KhronosGroup/glslang/releases/tag/12.3.0
Even though that is a bug it seems fine to change the name anyway and have a fallback.
Edit: Symlink now fixed on Arch with glslang 12.3.1-2

[build] Use new glslang name with fallback

---

src/util/config/config.cpp

Lazy-ass implementation
* <s>`#` used as separator</s>
* `;` used as separator
* options will override/extend those in dxvk.conf file
* <s>`DXVK_CONFIG="dxvk.hud=full#dxvk.blah = blah;blah:blah,#"`</s>
* `DXVK_CONFIG="dxvk.hud = full; dxvk.blah=blah"`
Note:
* `DXVK_HUD` variable still have higher priority than `dxvk.conf` and `DXVK_CONFIG`
* `#` act as comment now (same as in `dxvk.conf`)
e.g. `DXVK_CONFIG="#Show compiler; dxvk.hud = compiler; #dxvk.blah=blah"`
Lets call it feature.
Closes: #2894

[util] Add DXVK_CONFIG to define additional options

---

meson.build
src/d3d10/meson.build
src/d3d11/meson.build
src/d3d9/d3d9_include.h
src/dxgi/dxgi_include.h

Disable stdcall aliasing and enable kill-at to ensure our exported functions don't have the @8, @40, etc suffixes.
This still keeps `--enable-stdcall-fixup` as otherwise the linker can get confused trying to find exports from the .def. This does not result in aliases being added, just for them to be found to add to the export table.
This also switches d3d11 to use the MinGW provided dxgi.lib for linking and d3d10 to use the MinGW provided d3d11.lib for linking. Unfortunately the .a's we output seem to still have the @blah that we killed so we cannot use them for internal linkage since using kill-at.
Tested that what we get out of MinGW now is what we want with dllexp.
Supercedes: #3590
Exports
```
➜  build git:(master) ✗ winedump -j export src/dxgi/dxgi.dll
Contents of src/dxgi/dxgi.dll: …
```

build: Disable stdcall alias-ing and use kill-at

---

src/d3d9/d3d9_cursor.cpp

Since dxvk doesn't implement a software cursor, don't attempt to change its visibility. 
Not 100% certain if this is the right behavior vs native, but I'm trying to fix [...] https://github.com/AlpyneDreams/d8vk/issues/59 , and WineD3D simply seems to ignore the game's calls to `D3D8Device::ShowCursor(FALSE)`, which get forwarded to `D3D9DeviceEx::ShowCursor(FALSE)` with d8vk, as the game's software cursor remains visible even after these calls. This is the right, or at least expected, behavior in this case.
I can hypothesize Cossacks 2 is actually trying to hide a mythical and undefined hardware cursor perhaps, although it doesn't explicitly call `SetCursorProperties()` at all, only `D3D8Device::ShowCursor(FALSE)` after loading the main menu or starting a new game, which is a rather odd …

[d3d9] Don't show/hide a software cursor

---

src/d3d9/d3d9_options.cpp

nvk supports nir_op_fmulz/ffmaz

[d3d9] use strict float emulation for nvk

---

src/d3d11/d3d11_resource.cpp
src/d3d11/d3d11_resource.h
src/d3d11/d3d11_texture.cpp

Partially based on a patch by Derek Lesho.
I am planning on implementing the real support for that (in Proton's winevulkan first), although I guess it should be nothing wrong in having a stub meanwhile. Worst case I think some games will have videos starting showing up but still flickering. The stub already helps some games to properly show videos.
I tested that if the shared resource is created without D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX, QueryInterface indeed returns E_NOINTERFACE on Windows. It also seems to me that keyed mutex implementation belongs to DXGI resource (like other shared resources stuff) rather than to D3D11 textures of specific types.

[d3d11] Add stub IDXGIKeyedMutex interface.

---

src/util/config/config.cpp

Physics can bug out at high fps making the character fly or get stuck when running up or down slopes.
Closes https://github.com/doitsujin/dxvk/issues/3485

[util] Limit Conflict Vietnam to 60fps

---

src/d3d9/d3d9_device.cpp

Fixes the following validation errors in Spider Man Shattered Dimensions:
> err:   Validation Error: [ VUID-VkResolveImageInfo2-srcImage-00257 ] Object 0: handle = 0x2820ecf0430, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x24e35931 | vkCmdResolveImage2: srcImage sample count is VK_SAMPLE_COUNT_1_BIT. The Vulkan spec states: srcImage must have a sample count equal to any valid sample count value other than VK_SAMPLE_COUNT_1_BIT (https://vulkan.lunarg.com/doc/view/1.3.250.1/windows/1.3-extensions/vkspec.html#VUID-VkResolveImageInfo2-srcImage-00257)
> err:   Validation Error: [ VUID-VkResolveImageInfo2-dstImageLayout-00262 ] Object 0: handle = 0x2820ecf0430, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xb2b816de | vkCmdResolveImage2: Cannot use VkImage 0xf3215e0000001a22[] …

[d3d9] Don't resolve an image with 1 sample

---

src/d3d9/d3d9_device.cpp

Fixes a regression in PSO2 spotted by @CME42

[d3d9] Check depth bounds test when deciding to bind DSV

---

src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp

Fixes #3593
Instead of an enum or read/write flags like we discussed, I took a step back and thought about what `CommonTexture::m_hazardous` was actually used for. It's used to track whether the image has been transition to the hazard layout (GENERAL or FEEDBACK_LOOP). That's it. The actual hazard tracking happens in the device.
So the image layout strategy for DS is now as follows:
- If there's a hazard with depth write enabled, we transition to LAYOUT_FEEDBACK_LOOP and keep using that, just like we do for color RTs.
- If there's a hazard with depth write disabled (so technically not a hazard), we use LAYOUT_DEPTH_READ_ONLY for the render pass and transition back to the regular layout afterwards.
Before we would transition between LAYOUT_FEEDBACK_LOOP and LAYOUT_DEPTH_READ_ONLY per …

[d3d9] Handle sampling from DS_READONLY properly

---

src/d3d9/d3d9_spec_constants.h
src/dxso/dxso_compiler.cpp

Fixes #3594 (Regression caused by 438ae5cdfce7e7b2b0b34b22caac5bf3310ccc41)
I hope I got every spot.
This will need a bunch of testing. (@Blisto91 :))

[d3d9+dxso] Consider DMAP sampler in bit masks

---

src/util/config/config.cpp

Player movement and animation can bug out at high fps like issues moving around objects and the players head detaching slightly when moving backwards. 
Seems like it also helps some crash issues.

[util] Limit fps in Project: Snowblind

---

src/dxgi/dxgi_options.cpp

DXVK-NVAPI has the HDR bits since https://github.com/jp7677/dxvk-nvapi/commit/e59101009bf51fcc5ecf159d97788ab0546ac4b3
Pseudo-tested with Assetto Corsa Competizione (UE4) on a non HDR setup (NVIDIA GPU and non-HDR monitor), of course no real HDR, but also no crashes and enabling HDR in-game does have effect on colors.

[dxgi] Allow HDR on UE4/D3D11 when NVAPI is enabled

---

src/dxgi/dxgi_output.cpp

For two reasons:
1) Some apps will only enable or attempt to enable HDR if BitsPerColor is >= 10.
2) Encouraging apps to create 10-bit swapchains for use in hardware dithering on Gamescope/Steam Deck and to have more precision thru scanout color transforms

[dxgi] Set BitsPerColor to 10

---

src/util/config/config.cpp

Closes #3528. Turns out the intro plays back fine with deferSurfaceCreation enabled on latest Wine.

[util] Enable deferSurfaceCreation for Drakensang

---

src/util/config/config.cpp

Works around crashing because of statically linked amd ags

[util] Hide AMD in Riders Republic

---

src/d3d9/d3d9_fixed_function.cpp

Fixes #3628
Not entirely sure whether this is correct.

[d3d9] Divide projected textures by w if ProjectedCount is 0

---

src/d3d11/d3d11_buffer.cpp
src/d3d11/d3d11_resource.cpp
src/d3d11/d3d11_resource.h
src/d3d11/d3d11_texture.cpp

Fixes a crash with reshade mod (https://github.com/ValveSoftware/Proton/issues/3977#issuecomment-1716597154).
The mod modifies GetDevice function pointer in resource's vtable, and that triggers the crash in D3D11DXGIKeyedMutex::D3D11DXGIKeyedMutex(). Calling public interface to get dxvk device there was a bad idea.

[d3d11] Pass device directly to D3D11DXGIKeyedMutex

---

src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_stateblock.cpp

Long story short, the behavior of losable resource validation on device Reset() differs slightly between d3d9 and d3d8 in the sense that d3d8 state blocks survive Reset() calls and shouldn't be considered losable. 
D3D8 games like AIM 2: Clan Wars and others depend on this to work properly. Quick tests have also confirmed WineD3D ignores D3D8 state blocks on calls to device Reset().
At @K0bin's suggestion I've given a broader meaning to the member variable, since we might end up using it to toggle other d3d8-specific behavior in the future.

[d3d9] Add a device compatibility mode for d3d8

---

src/d3d9/d3d9_common_texture.cpp

IMO this is the better fix for #3662.
Right now, binding a system mem / scratch texture will make us call FlushImage for that texture which crashes because there is no image. On top of that, we may end up uploading recently created D3DPOOL_DEFAULT textures which means we basically clear it again.

[d3d9] Only set initial NeedsUpload for D3DPOOL_MANAGED textures

---

src/util/config/config.cpp

Helps performance dips that can happen in some areas
<details>
<summary>Screenshots</summary>
</details>
I'm leaving Battlestations Pacific out of this PR as even when i seem to get past the Games For Windows Live related crashes i still crash sitting in the main menu before i can get in game and test if it would benefit the same.

[util] Enable cachedDynamicBuffers for Battlestations Midway

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_swapchain.cpp

I don't particularly like having to do this either, so I've hid it under deferSurfaceCreation for now, as it seems to work around the same sort of problem, albeit at later stages in a swapchain's lifecycle.
Fixes Scrapland (Remastered), which apart from the intro video plays videos using ddraw (or maybe d3d7, haven't *really* checked, but it's not d3d8) when starting a new game or in between some levels, which will end up in a black screen with d8vk/dxvk unless we mark the presenter for recreation. Latest WineD3D somehow handles this sort of multiple swapchains on the same window situation just fine, although Scrapland was broken for a while there too with the same behavior (black screen after video playblack apart from the intro).
The first d3d8 thing the game calls after it's done with …

[d3d9] Mark presenter for recreation on device reset with deferSurfaceCreation

---

src/util/config/config.cpp

Temporary performance drop workaround until QueryDisplayConfig optimization is in Proton Wine.

[util] Enable useMonitorFallback for Holocure

---

src/util/config/config.cpp

Works around a alt tab OOM crash.
https://github.com/doitsujin/dxvk/issues/3639 is kept open for a deeper root cause look when there is time.

[util] Disable allowDirectBufferMapping for SkyDrift

---

src/dxgi/dxgi_monitor.cpp

HDR in Control (a patch released by a developer post-launch, not actually in the game sadly) tries to set a video mode with DXGI_FORMAT_R16G16B16A16_FLOAT.
This seemingly works on Windows, and based on FindClosestMode etc documentaton, this seems required to work for any format that scanout it supported for.
It's really not like the bpp is meaningful on Windows with the distinction of 8bit and 10bit not working in GDI modes at all. Nor does it end up actually setting anything on Linux/Deck where modesets are emulated.
So, treat DXGI_FORMAT_R16G16B16A16_FLOAT as 32bpp so the FindClosestMatchingMode and EnterFullscreenMode calls succeed.

[dxgi] Treat R16G16B16A16_FLOAT as 32bpp for display

---

src/util/config/config.cpp

Test server executables need the same VendorID to work around the rendering issues.

[Util] two more executables to workaround Warhammer Online

---

src/d3d9/d3d9_common_buffer.h

[d3d9] Return empty buffer slice for out-of-bounds offsets

---

src/d3d11/d3d11_context_imm.h
src/d3d11/d3d11_resource.cpp

WaitForResource is supposed to be externally synchronized.
Supersedes #3717
@yshui checked and the VRChat does enable D3D11Multithread. So this is an easy fix.
*If* it's legal to access the KeyedMutex from other threads without the context lock we can worry about that once we hit that case.

[d3d11] Lock context in KeyedMutex::ReleaseSync

---

src/util/config/config.cpp

Spoofing to Nvidia prevents ray tracing enablement on AMD and the game does not crash without ags anymore.
Hitman 2 still needs ags to not crash on startup. (game doesn't support RT)

[util] Don't spoof Nvidia on AMD GPUs in Hitman 3

---

src/util/config/config.cpp

Added Far Cry Primal to the list as it has the same issue. Could not find that Far Cry 5 suffers from it.
Closes #3758

[util] Hide Intel in Far Cry 3, 4 and Primal

---

src/d3d9/d3d9_device.cpp

Fixes: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9126

[d3d9] Fix off-by-one when copying shader defined constants

---

src/util/config/config.cpp

Improves the games performance when CPU bound.
Tested on a Radeon RX 6800 and Ryzen 7950x
<details>
<summary>Screenshots</summary>
Without
With
</details>

[util] Enable cached vertex buffers for Kenshi

---

src/util/config/config.cpp

[util] Set float emulation to Strict for UK Truck Simulator 1

---

src/util/config/config.cpp

Makes it not crash on alt tab when using at least Proton on Linux. Was unable to test regular Wine or Staging as Ubisoft Connect doesn't work there currently.
See [issue description](https://github.com/doitsujin/dxvk/issues/3653) for behavior on Windows.
Closes #3653

[util] Set deviceLossOnFocusLoss for Assassin's Creed 2

---

src/util/config/config.cpp

By total coincidence i stumbled upon https://github.com/doitsujin/dxvk/issues/3651 while i was doing a random test of Battlefield 2142 with Proton. The issue shows when you alt tab out and in of the game. 
When i had tested BF2 originally for the issue i think i did it in regular Wine where i had to enable virtual desktop for it to not just show a black screen which then makes the behavior not show. Proton doesn't have this issue and so i reproduced immediate there when alt tabbing in BF2142 and then went back to check BF2 again.
Fixes #3651

[util] Enable deviceLossOnFocusLoss for BF2 and BF2142

---

src/util/config/config.cpp

Helps CPU bound performance
<details>
<summary>Phase One</summary>
Without
With
</details>
<details>
<summary>Phase Two</summary>
Without
With
</details>

[util] cachedDynamicBuffers for Codename Panzers Phase One/Two

---

src/d3d11/d3d11_interfaces.h
src/d3d11/d3d11_on_12_interfaces.h
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_include.h
src/d3d9/d3d9_interfaces.h
src/dxgi/dxgi_interfaces.h
src/dxvk/dxvk_annotation.h

MIDL_INTERFACE already implies struct DECLSPEC_UUID.

[build] Remove declspec UUID annotations

---

meson.build

I've been playing with using clang-cl in combination with https://github.com/mstorsjo/msvc-wine to cross-compile against MSVC C/C++ runtime on Linux. You can see an example of cross file [here](https://gist.github.com/ishitatsuyuki/bfa4b4764394f94b19115b182d269f4e).
Right now, the upside is smaller binary size as you don't need to link in the C/C++ runtime statically. In the future there might be other reasons to use this, such as when better STL support is wanted.
The PR is some small changes for build flags to ensure this setup works smoothly.

MSVC and clang-cl QoL improvements

---

src/d3d11/d3d11_context.cpp

The Settlers: New Allies, crashes on launch due to the fact that it tries to submit an SRV to clearance via ClearUnorderedAccessViewUint. 
The native behavior is to ignore the errant resource type (see attached repro of the behavior) but dxvk, due to a static cast, crashes when it references the mis-cast object. This change does a QI and confirms the correct object before use, returning immediately if it is not.
[D3D11SrvClearTest.cpp](https://github.com/doitsujin/dxvk/files/13553138/D3D11SrvClearTest.txt)

Fix crash when srv is submitted to ClearUnorderedAccessViewUint

---

src/d3d9/d3d9_device.h

Fixes #3798
Fixes #3617
Observed using this test: https://github.com/K0bin/D3D9Garbage/blob/master/D3D9Garbage/ATIATOC.cpp

[d3d9] Only enable ATOC when rendering to MS RT

---

include/native/windows/windows_base.h

This helps avoid some compiler warnings on GCC in particular.

[native] Add a DECLARE_INTERFACE define for !CONST_VTABLE

---

src/d3d11/d3d11_features.cpp
src/d3d9/d3d9_mem.h
src/d3d9/d3d9_state.h
src/dxbc/dxbc_decoder.h
src/dxvk/dxvk_cs.h
src/dxvk/dxvk_extensions.h
src/dxvk/dxvk_memory.h
src/dxvk/dxvk_sparse.cpp
src/dxvk/dxvk_sparse.h

@mastercoms found an incorrectly coded comparison logic in sparse. The first commit fixes it.
The reason type checker let this through was because some surprising implicit conversion done by operator bool. Mark all operator bool as explicit to prevent any similar bug from happening in the future.

Fix incorrect comparison in sparse, convert all operator bool to explicit

---

meson.build

This makes it easier for distributors to build from the GitHub tarball, since they'll likely have libdisplay-info provided anyhow.
This is taken pretty much directly from gamescope's libdisplay-info dep.

[meson] Only use the libdisplay-info subproject as a fallback

---

package-native.sh

This ensures that the script produces a build similar to the default steamrt build, even if libdisplay-info is available on the build system root.
Fixes #3833

package-native.sh should force libdisplay-info subproject

---

src/d3d9/d3d9_common_buffer.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_swvp_emu.cpp
src/d3d9/d3d9_vertex_declaration.cpp
src/d3d9/d3d9_vertex_declaration.h
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h

Fixes #3755
Fixes #2375
Fixes #1828
Every frame Shank 2 maps multiple >1MB buffers with SizeToLock = 0.
That means we cannot just upload a subset of the buffer but have to upload the entire buffer multiple times per frame.
Copying that much data around is slow and on top of that it exceeds our 16MB staging buffer budget which makes us stall until the GPU is done with the earlier staging data.
This is actually the first time I've seen a game blow that budget outside of loading screens.
This PR changes it so that draws that only use buffers with D3DPOOL_SYSTEMMEM + D3DUSAGE_DYNAMIC upload all required data before each draw similar to DrawPrimitiveUp/DrawIndexedPrimitiveUp.
This reduces the amount of data copied each frame in Shank 2 from >30MB to <1MB.
I assume D3D9 drivers (or the runtime) …

Upload per-draw data for dynamic systemmem buffers

---

src/d3d9/d3d9_device.cpp

This fixes a gcc warning (originally reported by @Saancreed)

d3d9: Remove an unused variable

---

src/d3d9/d3d9_device.cpp

Fixes #3825
See the commit message.
This solves the problem according to Blisto. Pretty stupid.

[d3d9] Fail GetRTData if src and dst have mismatching sizes

---

dxvk.conf

Minor clarification in the example config comment as this option often leads to confusion because people expect applications to honor the reported number.

[util] Clarify maxDeviceMemory and maxSharedMemory

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_swapchain.cpp

Fixes #3724
Total War Medieval 2 uses GetFrontBufferData to take a screenshot and then copies that screenshot to a texture which is used to render the background of the loading screen.
In windowed mode, GetFrontbufferData will in fact take a screenshot of the entire screen. We don't implement it that way in DXVK, we always blit the most recent front buffer.
There's two problems with our implementations in Medieval 2:
- The image is positioned incorrectly. The game retrieves the window client rect and copies those parts of the GetFrontBufferData destination surface. DXVK always puts the screenshot at 0,0.
- The game uses additional swapchains (on the same window no less) and presents using one of those. DXVK always blits the implicit swapchain.
So to solve this without having to implement …

D3D9: Make windowed GetFrontBufferData more accurate

---

src/util/config/config.cpp

The issue affect the 3 other d3d9 Supreme Ruler games as well

[util] Disable countLosableResources for all d3d9 Supreme Ruler games

---

meson.build

This is at least enough to use the system headers when building from the tarball, but doesn't check for any version requirements. While imperfect, it's an improvement on the current solution which is to `sed -i` meson.build, which is sort of overkill...
Partially fixes #3322

meson: Check for bundled Vulkan/SPIR-V headers

---

src/util/config/config.cpp

Dirt 5 does not crash without working ags anymore and Ethan Carter Redux also starts fine without a spoof. 
This allows the built in AMD ags in Proton 9 to be used for these games.
The Hitman 3 config is redundant as it doesn't allow RT to be enabled without Nvapi anyway.
Tested on a AMD 7900xtx and a RTX 4080

[util] Remove some unneeded built in configs

---

src/util/config/config.cpp

Insane Performance increase With d3d9.allowDirectBufferMapping To false
oddly enough seems like the performance issue only apply's to AMD card since Radeon HD 4000 To current RX card,
I was wondering If I can also get this command to work without using the Vulkan graphic api as The majority playersbase in
eldewrito (Halo online) uses Radeon GPU that doesn't support Vulkan. It would be nice if its possible.
Here are some proof that using the commands makes the game run faster
https://www.youtube.com/watch?v=vRG7wRrptiY

[util] Add config for Halo Online ( massive performance increase )

---

src/d3d9/d3d9_device.cpp

Fixes #3888 
Before anyone asks: You cannot specify an offset when binding the index buffer so we don't have to do the same thing there.

[d3d9] Respect vertex buffer offset when dynamically uploading geometry

---

src/d3d9/d3d9_device.cpp

Fixes a regression in Dragon Age Origins, Carries Order Up and Mount & Blade.
Fixes #3891
Fixes #3892

[d3d9] Only unbind in EndScene if the game cleared the binding

---

src/d3d9/d3d9_device.cpp
src/util/util_bit.h

When targeting ARM64EC, both __x86_64__ and _M_X64 are defined but not all x86 intrinsics are present, treat EC as regular ARM64 so the native intrinsics are used instead.

Support building for ARM64EC

---

src/d3d11/d3d11_view_srv.cpp
src/d3d11/d3d11_view_uav.cpp

Noticed this bug while messing around with running OVRServer (Oculus Runtime) in Wine, as its MiscFlags was set to `D3D11_RESOURCE_MISC_SHARED (0x2), D3D11_RESOURCE_MISC_BUFFER_STRUCTURED (0x40)` (0x42), GetDescFromResource would fail due to it not being exactly 0x40.
I don't know if the direct MiscFlags comparison was intended behavior, but changing it to a `&` like a proper flag comparison worked fine in my testing.
Please let me know if this is correct or if there is any changes I should make.

Fix MiscFlags check in GetDescFromResource

---

src/util/config/config.cpp

Game crashes in certain places like specific cutscenes unless capped at 60fps.

[util] Cap Dark Void to 60fps

---

dxvk.conf
src/dxgi/dxgi_factory.cpp
src/dxgi/dxgi_options.cpp
src/dxgi/dxgi_options.h
src/util/config/config.cpp

The QueryDisplayConfig optimization is now in Proton 9 Wine which is the proper fix.
Closes https://github.com/doitsujin/dxvk/issues/3632

[dxgi] Remove useMonitorFallback option

---

src/d3d11/d3d11_texture.cpp

D3D11_RESOURCE_MISC_SHARED_KEYEDMUTEX is implemented.

[d3d11] Remove missed Shared Keyedmutex warning

---

src/dxgi/dxgi_options.cpp

Games using libxess.dll or wrapper modules will crash. To work around this, the vendor ID is set to -1 to avoid using the XeSS module.
This change was tested with various XeSS titles, including Shadow of the Tomb Raider, Hitman 3, Dying Light 2, and Diablo IV (I ensured the relevant driconf changes were made so that the mesa driver isn't the one setting the vendor ID to '-1').
Note that Dying Light 2 created its own DX11 wrapper module, libxess_dx11.dll, which uses some functionality from the libxess.dll module and consequently causes a hang. I don't anticipate many titles doing this, so it's included in the module check.

[dxgi] Force vendor ID change when XeSS is detected on an Intel GPU

---

src/util/config/config.cpp

Without mods, Nier Replicant runs faster when going above 60 FPS.
The game had an official patch that implemented a framerate limiter to prevent this. This limiter is terrible, because it's not a stable 60 FPS, but a weird 57-58 FPS. There's no way to disable this in-game, it has to be done by editing a config file or through a mod.
- In the default case (a user plays the game as it is), it does nothing, since 57-58 is lower than 60.
- If a user is going out of their way to edit the config file, why would they assume that DXVK already provides a frame limiter? [Guides](https://www.pcgamingwiki.com/wiki/NieR_Replicant#Framerate_limited_to_57.7E58_FPS) already tell the user to set up a frame limiter.
- They are using [Special K in order to use a mod to play at high refresh rates at normal …

[util] Remove framerate limiter for Nier Replicant

---

src/d3d9/d3d9_query.cpp

Fixes #3951. VERTEXSTATS queries are only exposed on debug runtime builds apparently, a fact confirmed both in the trace attached to the issue and by the official docs: https://learn.microsoft.com/en-us/windows/win32/direct3d9/queries . That game uses a VERTEXSTATS query to determine if the debug runtime is loaded...
I've taken a cleaver and outright removed it, but if it's somehow needed or deemed useful we could hide it behind a config variable. Let me know if you'd rather have that approach and I'll be less of a barbarian.

[d3d9] Remove support for VERTEXSTATS queries

---

src/util/config/config.cpp

OpenGL game that also spins up d3d9. Will black screen without deferSurfaceCreation when using dxvk
fixes #3964

[util] Set deferSurfaceCreation for 9th Dawn II

---

src/dxgi/dxgi_swapchain.cpp
src/dxgi/dxgi_swapchain.h

dxgi hooking tools might hook both, eg. https://github.com/SpecialKO/SpecialK/issues/167
meanwhile those tools would likely not expect their presentation hooks to be fired twice per presentation

[dxgi] unchain DxgiSwapChain::Present1 and Present

---

src/dxgi/dxgi_factory.cpp
src/dxgi/dxgi_factory.h

similar to https://github.com/doitsujin/dxvk/pull/3966, avoid chaining so that dxgi tools attempting to wrap swapchains don't end up double wrapping
ref: https://github.com/SpecialKO/SpecialK/issues/168

[dxgi] unchain DxgiFactory::CreateSwapChain and CreateSwapChainForHwnd

---

src/d3d11/d3d11_video.cpp

The use case is the implementation of Media Foundation video processing to convert YUV to RGB D3D buffers.
Media Foundation decoders only support YUV format output, and have some specific behavior where they align their YUV planes on 16 bytes (most common case is 1920x1080 video being padded to 1920x1088, with padding at the end of the Y plane). For some games, we need to be able to convert these aligned YUV buffers to RGB buffers while at the same time cropping or keeping the alignment-induced padding (this depends on the video processor MFT media type attributes).
In short, I'm implementing it like this:
```C
if (FAILED(hr = IMFMediaType_GetUINT64(processor->input_type, &MF_MT_FRAME_SIZE, &input_desc.frame_size))
|| FAILED(hr = IMFMediaType_GetGUID(processor->input_type, &MF_MT_SUBTYPE, …
```

[d3d11] Implement video processor source rect and tweak filtering.

---

src/dxgi/dxgi_adapter.cpp

Set to max signed integer and prevent sign bit from being set to negative.
Resolves https://github.com/doitsujin/dxvk/issues/3983

Initialize UMD version quad to a max signed int64

---

src/d3d9/d3d9_adapter.cpp

Fixes #3938. Adds a check against passed DS formats during calls to `CheckDepthStencilMatch()`. Should prevent games from using D32, D15S1 and D24X4S4 going forward.
We had to do [a similar check for DS formats in d8vk](https://github.com/AlpyneDreams/d8vk/blob/1a039a4729b9a8f0440739eec4cedf59e79a3aa0/src/d3d8/d3d8_format.h#L18) for what it's worth, so this makes sense.

[d3d9] Validate DS format support during CheckDepthStencilMatch

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp

Looks like another one of those situations where D3D9 technically allows something, but in practice no native driver actually supports it. Verified that `CheckDeviceFormat` actually does not expose cube support for **any** depth format, even the fourcc ones.
Fixes #3980, the game has two code paths to deal with torch shadows and the D248 one happens to be broken.

[d3d9] Do not support cube textures with depth formats

---

src/util/config/config.cpp

Fixes invisibility effect flicker when invariantPosition is enabled

[util] Enable d3d11.longMad for Guild Wars 2

---

src/util/config/config.cpp

Prevents the game black screening on alt-tab

[util] Set deviceLossOnFocusLoss for The Sims 3

---

README.md
src/wsi/wsi_platform.cpp

A modified port of the top section of the [dxvk-native](https://github.com/Joshua-Ashton/dxvk-native) readme.
Rendered version at https://github.com/Blisto91/dxvk/blob/native-readme/README.md
CC: @flibitijibibo It was shortly discussed after the merge that there was a preference to change `DXVK_WSIDRIVER` to `DXVK_WSI_DRIVER`

[meta, native] Add DXVK Native readme section and change DXVK_WSIDRIVER name

---

dxvk.conf
src/d3d9/d3d9_format.cpp

Should get #4008 shadows working properly on Nvidia and provide a saner default behavior for some games. Since native Nvidia d3d9 drivers don't support DF16 or DF24 it makes little sense to expose them IMHO.
The game in question would still need a config option for AMD and Intel, since it seems to be broken in regards to shadows in general.
Alternatively, we could allow it only for AMD and Intel (more historically accurate), rather than disabling it only on Nvidia, since this would also disable it for more exotic vendors. Let me know what you think.

[d3d9] Do not enable support for DF formats on Nvidia

---

src/util/config/config.cpp

Works around incorrect shadows on AMD & Intel
Closes #4008

[util] Disable supportDFFormats for Prototype

---

src/d3d9/d3d9_options.cpp
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_adapter.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device_filter.cpp
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_instance.cpp
src/dxvk/hud/dxvk_hud_item.cpp
src/util/util_version.h

And stop misusing deprecated `VK_VERSION` macros.
Supercedes #4001.
@Blisto91

Use custom driver version helper

---

.github/workflows/artifacts.yml
include/native/meson.build
meson.build
src/d3d10/meson.build
src/d3d11/meson.build
src/d3d9/meson.build
src/dxgi/meson.build

This reworks #3325 to apply to the latest dxvk revision, and is based on #3738 and #3743. As a result, only the last 3 commits are actually for this specific PR.
CC @smcv, I had to adjust a few of the patches, so we'll need to re-confirm the signoffs for those.
Fixes #3323
Part of #3451
Supercedes #3325

Install headers and pkg-config files, MkII

---

src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_descriptor.cpp
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_extensions.h

Confirmed that this does in fact reduce the number of descriptor pools we create in some cases, might need some testing to ensure it doesn't regress performance by accident.

Use NV_descriptor_pool_overallocation if available

---

dxvk.conf
src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/util/util_flush.cpp
src/util/util_flush.h

It ensures that for the same D3D commands the output VK commands don't change between runs.
Useful for comparative benchmarking, can negatively affect performance.
---
To fully test it I'd need to disable all threading and compare runs with api dump layer. For now, what was compared are renderpasses after d3d11 translation - they are the same between runs.
When `reproducibleCommandStream` is not set the number of draw calls in renderpass and even the number of renderpasses may vary, which makes hard to make comparisons between runs, especially on GPUs where renderpasses do matter.

[d3d11,d3d9,util] Add a config option for reproducible VK output

---

src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_options.cpp

I'm guessing the use of customDeviceId for vendorID was unintentional, right? :sweat_smile: Not that it affected much beyond VQuery support on the few titles that have Nvidia vendorID (& deviceID) overrides set in place (even then, only on AMD and Intel).
Also moved the DF Format support disabling on Nvidia during options parsing, sorry for not doing that earlier (didn't really think a vendorID check was already done there, so didn't bother to check).

[d3d9] Options parser vendorID fix and DF format support validation rework

---

src/d3d9/d3d9_query.cpp

I'm not entirely sure which games relied on this being exposed anyway, but here's a bit more insight into how this obscure query is supposed to work: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d9types/ns-d3d9types-_d3ddevinfo_vcache
Also this is what you get with native 45.23 Nvidia drivers, on Windows XP, with a GeForce 4:
```
Listing VCache query result:
~ vCache Pattern: CACH
~ vCache OptMethod: 1
~ vCache CacheSize: 16
~ vCache MagicNumber: 7
```
dxvk currently does:
```
Listing VCache query result:
~ vCache Pattern: HCAC
~ vCache OptMethod: 1
~ vCache CacheSize: 24
~ vCache MagicNumber: 20
```
Since I'm guessing CacheSize refers to the number of internal cached buffers the driver holds, it's probably safe to assume a d3d9-era card reported somewhat higher …

[d3d9] Tweak VCache query results

---

src/d3d9/d3d9_fixed_function.cpp

Fixes the bug in Phantasy Star Online that was reported after merging #4015.
I've tested this PR with both Phantasy Star Online apitraces, the Cold Fear apitrace and the Snowblind apitrace. Those were the games that I know were broken at some point because of fixed function texture coordinate processing. On top of that, I ran the Wine FF texcoord tests again and those were fine too.
______
Tests show that the count out of `D3DTSS_TEXTURETRANSFORMFLAGS` gets applied to generated texcoords like `D3DTSS_TCI_CAMERASPACEPOSITION` too.
At the same time, projection only gets applied (or renders something sensible) when used with `FVF_XYZ` and `D3DTTFF_COUNT3` or higher. With lower values it either produces garbage like this:
(FVF_TEXCOORDSIZE1 + FLAGS_COUNT1)
or this:
(FVF_TEXCOORDSIZE2 + …

[d3d9] FF: Apply transform flags count to generated texture coords

---

src/util/config/config.cpp

Closes #4034.
@K0bin 
Here's a screenshot of which processes stay open with the game (tested with Battlefield 4):

Add dxvk.maxChunkSize 1 to Origin

---

src/util/config/config.cpp

A follow-up to #4037.
Tested by exiting Steam completely, then launching with `DXVK_CONFIG="dxvk.maxChunkSize = 1" steam` and playing Watch Dogs 1 for about 5 minutes. Haven't experienced any problems.
Below are the processes that stay open with the game in the background:
`UbisoftConnect.exe` is the main process, which doesn't stay open, but I'm adding it for extra safety. `upc.exe` seems to be what really matters here (I guess it means "UPlay Core").
We also have these ones in the Ubisoft Game Launcher installation folder:
- `UbisoftGameLauncher64.exe` and `UbisoftGameLauncher.exe` (opens temporarily during Steam game launch; maybe a proxy service for Steam-Ubisoft?)
- `UplayCrashReporter.exe` (I don't think this one needs maxchunksize)
- `UplayWebCore.exe` (probably related to the …

[util] Add dxvk.maxChunkSize 1 for Origin Web Helper Service and Ubisoft Connect (UPlay)

---

src/util/config/config.cpp

Works around flickering on some objects such as the blue light arrow on lowering gates

[util] Set longMad for Watch_Dogs

---

src/wsi/glfw/wsi_platform_glfw.cpp

`GlfwWsiDriver::getInstanceExtensions` was creating an `std::vector` with a size argument in the ctor but then used `push_back` instead of filling the pre-allocated elements, leading to a bunch of nullptr entries at the start that caused an exception later on when accessed.

Fixed GLFW exception at startup

---

src/util/config/config.cpp

Depends on https://github.com/doitsujin/dxvk/pull/4056
Game bug in its d3d10 mode where it selects the lowest supported refresh rate.

[util] Disable Crysis 1 refresh rate fps limiter

---

src/util/config/config.cpp

Similar to the first game it has a poor vsync implementation (limits to 30 fps) and physics issues when the frame rate is unlocked.
Limiting to 60 FPS and enabling vsync externally provides a better experience after the ingame vsync is disabled.

[util] Dead Space 2 - Limit to 60 FPS and enable vsync

---

src/util/config/config.cpp

Prevents the game from black screening on each alt-tab

[util] Enable deviceLossOnFocusLoss for The Force Unleased

---

src/util/config/config.cpp

Works around the game black screening on alt-tab when it is set to fullscreen with a non native resolution

[util] Set deviceLossOnFocusLoss for Guild Wars

---

src/d3d9/d3d9_interface.cpp

Probably not all that relevant, however native drivers apparently enforce it. There are games out there that make use of D3DCREATE_PUREDEVICE, so it doesn't hurt to make sure we don't end up in weird situations. 
To be fair, I fail to see how this flag would ever have made any sense outside of HWVP (and maaaaaybe mixed VP), but there's nothing explicitly mentioned in the spec as far as limitations go, so this was based purely on observed behavior.

[d3d9] Validate D3DCREATE_PUREDEVICE usage

---

src/d3d9/d3d9_device.cpp

Fixes #4083
The game also suffers from a broken shadow which is fixed by #4036

Fixes for D3D8 Total War Rome

---

src/util/config/config.cpp

Helps slowdowns below 30fps in certain scenarios like when moving the camera over heavy vegetation areas among others.
Yes the exe is named `game.dat`
Closes #3950

[util] Set cachedDynamicBuffers for Battle for Middle-Earth 2

---

src/util/config/config.cpp

There is a game engine bug where playing above 60fps, causes audio to brake when switching maps. It would be nice to lock the framerate to avoid that issue.

WRC4 Added

---

dxvk.conf
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/util/config/config.cpp

Fixes #4098.
Tests of both modern and d3d8/d3d9 era drivers show that D16_LOCKABLE is and was only ever supported on AMD.
P.S.: [Reference outputs here](https://drive.proton.me/urls/1WHHKT8P0C#cbJ6R2bTCCF8).
I've also taken the liberty to clean up the D32 configs and what was left of the validation logic, since we've removed support for it globally quite some time ago.

[d3d9] Various vendor formats adjustments

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_state.h
src/d3d9/d3d9_stateblock.cpp
src/d3d9/d3d9_stateblock.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swvp_emu.cpp
src/d3d9/d3d9_swvp_emu.h
src/util/util_matrix.cpp
src/util/util_small_vector.h

Fixes the following Wine test failures:
StretchRect, lighting, specular_lighting
```
visual.c:4451: Test failed: Test 6, got unexpected hr 0.
visual.c:4451: Test failed: Test 7, got unexpected hr 0.
visual.c:4451: Test failed: Test 8, got unexpected hr 0.
visual.c:4451: Test failed: Test 9, got unexpected hr 0.
visual.c:4451: Test failed: Test 14, got unexpected hr 0.
visual.c:4451: Test failed: Test 15, got unexpected hr 0.
visual.c:4451: Test failed: Test 16, got unexpected hr 0.
visual.c:4451: Test failed: Test 17, got unexpected hr 0.
visual.c:4451: Test failed: Test 22, got unexpected hr 0.
visual.c:4451: Test failed: Test 23, got unexpected hr 0.
visual.c:4451: Test failed: Test 24, got unexpected hr 0.
visual.c:4451: Test failed: Test 25, got unexpected hr 0.
visual.c:4451: Test …
```

[d3d9] Fix a bunch of Wine test failures

---

src/util/config/config.cpp

Works around flickering on characters when a outline or highlight effect is showing.
Closes #4090

[util] Enable longMad for Watch_Dogs 2 and Legion

---

src/util/config/config.cpp

Works around a crash regression in dxvk 2.3 upon resolution change.

[util] Disable countLosableResources for Myst V

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_fixed_function.h

Fixes #4035
Fixes #4087 
We need to apply the count **after** transforming the texcoord.
Passes my tests here: https://gitlab.winehq.org/K0bin/wine/-/blob/ff-texcoord-tests/dlls/d3d9/tests/visual.c#L28402-29023

[d3d9] Rework FF texcoord processing

---

package-native.sh
src/util/thread.h
src/util/util_env.cpp
src/util/util_win32_compat.h

This pull request adds initial FreeBSD operating system support.
To build: `env CC=cc CXX=c++ ./package_native.sh <other args here> --64-only` (for 64-bit system)
~~(gcc13 is currently not working)~~

Add FreeBSD support

---

src/util/config/config.cpp

Also combine the entries for the two games because BF2142 is essentially a reskin or a standalone add-on.

[util] Disable counting losables for Battlefield 2 & 2142

---

src/util/config/config.cpp

Since the enablement of invariant position by default the game suffers from white flickers on characters when you use the Next Generation Content option

[util] Enable longMad for Tomb Raider Legend

---

src/util/config/config.cpp

Helps very low CPU bound performance especially in Castaway Stories.
https://github.com/doitsujin/dxvk/issues/4066 is kept open since even though this helps a bunch the performance is still oddly low. 
I haven't been able to compare to Windows since it crashes for me before i get ingame without dxvk and so far the game doesn't agree with apitrace.

[util] Set cachedDynamicBuffers for The Sims 2 and friends

---

src/util/config/config.cpp

To prevent it from crashing on a alt-tab

[util] Enable deviceLossOnFocussLoss for Rise of Nations

---

src/d3d8/d3d8_device.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_device.cpp

Fixes #4119
Fixes #4122
I did some cleanup to CopyRects and put the StretchRect internals into a separate function that allows disabling specific checks.
cc
@WinterSnowfall 
@Joshua-Ashton

[d3d8+9] Relax certain StretchRect restrictions

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h

Would need feedback from @AlpyneDreams .
The idea is to get rid of reinterpret casts and stick with what native does, namely a monotonically increasing counter that is passed back as the token whenever new state blocks are created. Tests have shown there's no token reuse, not even between device resets.
I also don't think we should worry about the address space being exhausted, because I did some quick math and if let's say a game creates 8 state blocks per frame @ 60 fps, it will take about 100+ days to overflow a DWORD. That's "let's not worry about it" territory in my book... but I can in theory implement a check to see if a token is already taken before allocating it.

[d3d8] Implement monotonic state block tokens

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h

Wrote some more extensive tests against native and it looks like:
- tokens actually start at 1
- tokens decrease if the most recent token is the one being deleted
Perhaps there are some additional corner cases I've missed, but since ultimately the token values are purely cosmetic, I'm going to call this close enough.

[d3d8] Mimic native token allocations

---

src/util/config/config.cpp

Suggested by @Blisto91. Makes more sense to order them this way, now that d3d8 is part of the picture. I'll let @Blisto91 follow up if he also wants to order them alphabetically :wink: .
I've also checked if we missed to transition any d3d8 games from the d3d9 section, but it all looks good as is.

[util] Reorder config options by API

---

src/d3d9/d3d9_fixed_function.cpp

[d3d9] FF: Fix return type for lighting op

---

src/util/config/config.cpp

Without this fix, Batman Arkham Knight won't boot on Intel GPUs since the code explicitly checks for vendor id `0x10DE` & `0x1002` and if the vendor id is different, the game won't boot.

[utils] Hide Intel Gpu for Batman Arkham Knight

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_format.h

Fixes #4158
Serious Sam 2 has 3 ways of uploading video frames:
- Lock XRGB texture and write XRGB data to that texture.
That happens when: YUY2 **textures** are supported in `CheckDeviceFormat`. DXVK master hits this code path on Nvidia GPUs because we check for sampling support on `VK_FORMAT_G8B8G8R8_422_UNORM` and Nvidia supports that.
- Lock YUY2 offscreen surface and write YUY2 data to that surface. Copy it to a XRGB texture afterwards using `StretchRect`.
That happens when: YUY2 **textures** are **un**supported but YUY2 **surfaces** are supported in `CheckDeviceFormat`. Additionally YUY2 is supported as a source format in `CheckDeviceFormatConversion`.
- Lock XRGB texture and write YUY2 data to that texture.
That happens when:
- either YUY2 **textures** are **un**supported in …

Fix issues with CheckDeviceFormat & CheckDeviceFormatConversion

---

dxvk.conf
src/util/config/config.cpp

Like stated in the commit message, the feature was present in one of the d8vk branches at some point. But it never landed in DXVK.
For reference, I restored the feature here, rebase on top of current master: https://github.com/tobiasjakobi/dxvk/tree/d3d8-shadowbuf
However we might need some documentation of `d3d8.scaleDref` in the config template.

Small fix for the config template and the profiles

---

src/dxvk/dxvk_descriptor.cpp

Currently shouldSubmit will force the dxvk context to be flushed when too many descriptor pools have been allocated. This heuristic does not work when VK_NV_descriptor_pool_overallocation is in use because there will only ever be a single pool.
This change updates the heuristic to use the number of allocated sets when VK_NV_descriptor_pool_overallocation is in use.
Resolves the issue described in https://github.com/ValveSoftware/Proton/issues/7862

Update shouldSubmit to correctly handle descriptorPoolOverallocation

---

src/util/config/config.cpp

The game will sometimes black screen upon alt-tab without deviceLossOnFocusLoss. 
Spoofing the GPU through dxgi to a known one from its list prevents the System Detection tool from complaining that it is unsupported on some setups.
The reason for the spoof being dxgi and not d3d9 is that it is what is used during system validation. Deleting systemdetection.dll will make the game not load dxgi.dll at all (besides via the ubisoft overlay).
The game itself uses d3d9 to determine vendor for e.g. if Nvapi should be loaded or not.

[util] Add configs for Splinter Cell Conviction

---

src/util/config/config.cpp

See issue https://github.com/doitsujin/dxvk/issues/4172. 
Does not close it as it is just a work-around and not a proper fix.

[util] Set textureMemory to 0 for Operation Racoon City

---

src/util/config/config.cpp

Think the screenshots speak for themselves
<details>
<summary>Screenshots</summary>
Without
With (+ vsync forced off)
</details>

[util] Enable cachedDynamicBuffers for Art of Murder

---

src/util/config/config.cpp

See https://github.com/doitsujin/dxvk/issues/3356#issuecomment-2266668057
Also move up Battle.net so the launchers are grouped

[util] Set maxChunkSize to 1 for Epic Games Launcher

---

src/d3d9/d3d9_surface.cpp

This allows people using interop to use `GetVulkanImageInfo` on surfaces like render targets and the backbuffer in addition to textures.

[d3d9] Allow querying ID3D9VkInteropTexture from surfaces

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_initializer.cpp
src/d3d9/d3d9_initializer.h

Fixes Brigand: Oaxaca (Steam ID 652410) crashing during loading in game. Repro steps:
```
1) Launch game
2) Click Continue and then 1: Begin
3) Select any story (I did Brigand - Oaxaca)
3) Wait for crash
```
This is 32 bit game. At some moment the game tries to create a 16384x16384 texture with 15 mips, usage 0, POOL_MANAGED. That happens because it uses D3DX functions for that without verifying the status. First calls D3DXGetImageInfoFromFileA() while some files are missing (in this case the output dimensions are not intialized or zeroed with neither Wine builtin nor Windows native d3dx). Then it calls D3DXCreateTexture() with those uninitialzed on-stack variables which usually end up in huge values. D3DXCreateTexture() clamps those dimensions to device texture caps and thus ends up with …

[d3d9] Handle map failure in texture initializer

---

dxvk.conf
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h
src/util/config/config.cpp

The intention here is to do this by default and remove the option as soon as we flip on longMad as well, only made this an option for now for a) testing purposes and b) not screwing with fossilize DBs too much. Not sure if we should do this for D3D9 too.
Fixes #4162.

Add option to explicitly emit long dot products

---

src/d3d9/d3d9_options.cpp

AMD's Linux open source driver now optimizes for the Strict floatEmulation path.

[d3d9] Default to Strict floatEmulation for amdvlk 2024.Q3.1

---

dxvk.conf
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h
src/dxso/dxso_compiler.cpp
src/dxso/dxso_options.cpp
src/dxso/dxso_options.h
src/dxvk/dxvk_instance.cpp
src/spirv/spirv_code_buffer.cpp
src/spirv/spirv_code_buffer.h
src/spirv/spirv_module.cpp
src/spirv/spirv_module.h
src/util/config/config.cpp

DCE Fixes invalid SPIR-V in some edge cases, e.g. unreachable continue blocks in a loop. Doing this at the front-end level would theoretically be possible, but much more difficult to reason about.
As for the rest, all of these changes mess with fossilize DBs so do it all in one go.

Fix various shader-related issues

---

src/dxgi/dxgi_adapter.cpp
src/util/config/config.cpp

Should help games pick the correct GPU on setups with integrated graphics.
Supercedes #4192.

[dxgi] Under-report iGPU memory if dGPUs are present

---

src/d3d11/d3d11_context_ext.cpp
src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_device.h

A fix for the performance regression with DXVK-NVAPI that we found earlier.
This isn't the nicest solution but it's a simple solution.

[d3d11] Always keep barrier control options set by app profile

---

src/util/config/config.cpp

Improves performance by avoiding stalls.
The game locks an index buffer multiple times per frame.
warn:  Waiting for resource: Lock Buffer
- Pool: D3DPOOL_DEFAULT
- Usage: D3DUSAGE_WRITEONLY
- OriginalFlags: 0
- Flags: 0
- OffsetToLock: 0
- SizeToLock: 240
- Type: INDEXBUFFER
- Total buffer Size: 240
- Map Mode: DIRECT

[util] Disable direct buffer mapping for Max Payne 1

---

src/util/config/config.cpp

Fixes frametime jumps when shooting.
Discussed on the Discord server.

[util] Enable cachedDynamicBuffers for APB:Reloaded

---

src/d3d11/d3d11_swapchain.cpp
src/d3d9/d3d9_swapchain.cpp
src/dxvk/dxvk_presenter.cpp
src/dxvk/dxvk_presenter.h
src/util/util_fps_limiter.cpp
src/util/util_fps_limiter.h

Might need a bit of testing to ensure it still applies where necessary.
Should fix some cases where some mixture of swapchain buffering and timing errors cause us to enable the limiter even if the game has its own or if we're running at display refresh in a non-`present_wait` environment.

[util] Make frame rate limiter enablement heuristic more robust

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h

There's a minor type difference between BaseVertexIndex in d3d8 (UINT set by SetIndices) and in d3d9 (INT as input parameter for DrawIndexedPrimitive). The values are, I expect, too high to ever be hit, however if that happens we shouldn't overflow into a negative value with d3d9.
Clamping is perhaps not ideal, but in order to simulate native d3d8 behavior we technically have to accept the full range of UINT values of BaseVertexIndex, which we should also return during calls to GetIndices. I have verified this works fine with native.

[d3d8] Clamp BaseVertexIndex to INT_MAX during use

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h
src/d3d9/d3d9_util.cpp
src/d3d9/d3d9_util.h

A bunch of edge cases we weren't handling properly.
This is gonna need some testing.
In theory we could also use VK_STORE_OP_DONT_CARE for discardable depth stencil surfaces but I don't think that's worth the additional complexity. Tracking the load op is already a bit of a mess. Games don't really use discardable depth stencil surfaces all that much and it would only help tilers anyway as far as I know.

[d3d9] Handle remaining edge cases of Discard & Lockable

---

src/util/log/log.cpp
src/util/log/log.h

This matches wine's definition, fixes crashes when wine is built with clang.

[util] Use cdecl calling convention for __wine_dbg_output

---

src/d3d8/d3d8_d3d9_util.h
src/d3d8/d3d8_include.h

A minor nit, and most likely generally unused, but better safe than sorry. D3DPRESENT_RATE_UNLIMITED (0x7FFFFFFF) is present in the d3d8 spec, but unsupported. Ignore it and revert to D3DPRESENT_RATE_DEFAULT (0) in case any early d3d8 games are mad enough to use it. [D3DPRESENT_RATE_UNLIMITED was removed in d3d9](https://learn.microsoft.com/en-us/windows/win32/direct3d9/converting-to-directx-9#intervals-and-swapeffects-changes), but may have actually been scrapped as far back as d3d8 with the DX8.1 release.

[d3d8] Ignore unsupported D3DPRESENT_RATE_UNLIMITED

---

src/util/config/config.cpp

Steel Soldiers does some "classic" CPU read-backs from DYNAMIC buffers. So does FIFA Football 2003. Plus some minor config file alignment, as it was a bit all over the place for the last two entries.

[util] Enable cachedDynamicBuffers for Steel Soldiers and FIFA 2003

---

src/util/config/config.cpp

Pretty much what the description says: inputs and some physics-based effects are broken above 60 fps. 
The game also needs **Nvidia Shadow Buffers** support to be fully playable (as in camera avoidance gameplay depends on it), but I'm hoping @AlpyneDreams will get to reinstate it at some point.

[util] Add a framecap for Pandora Tomorrow

---

src/d3d8/d3d8_device.cpp

D3D8 apparently validates this, while D3D9 does not. I've checked that WineD3D also performs this validation, ~~I am yet to check olden (WinXP) native behavior~~. Native d3d8 drivers, of WinXP fame, also perform this validation.
P.S.: @Blisto91 Also tested on modern Windows with AMD and it also performs the validation.

[d3d8] Validate viewport dimensions on SetViewport

---

src/util/config/config.cpp

Chrome has regressed at some point prior to the d8vk merge, during the last rebase we did.
The game is weird. It calls CopyRects on a X8R8G8B8 surface (D3DPOOL_DEFAULT) as source and a R8G8B8 off-screen surface (D3DPOOL_SCRATCH) as target. This would never work in practice (and the game indeed crashes during start-up), because CopyRects doesn't perform format conversions, especially not on unsupported formats, so I can only assume that the game relied on hardware R8G8B8 support originally.
As a workaround, we can do the opposite and force convert the target surface to X8R8G8B8 when it gets created. This seems to work fine with a minor annoyance: the screenshots captured by the game alongside save games are corrupted.
WineD3D works fine on both accounts, but unfortunately I can't quite …

[d3d8] Add a framecap for Chrome: Gold Edition

---

src/d3d8/d3d8_batch.h
src/d3d8/d3d8_buffer.h
src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_interface.cpp
src/d3d8/d3d8_interface.h
src/d3d8/d3d8_surface.h
src/d3d8/d3d8_swapchain.h
src/d3d8/d3d8_texture.h
src/d3d8/d3d8_volume.h

Mostly nits uncovered while I was (yet again) reviewing refcounts...
The only real concern is that in some cases we are creating & reffing objects even after the proxied calls to d3d9 are failing, which of course doesn't make any sense. Probably less of a problem with games that choke on such errors anyway, but as we know there are some that *expect* calls to error out in order to function properly.

[d3d8] Improve handling of failed d3d9 calls

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h

In D3D8 the runtime owns VS & definitions, PS and state blocks. Client applications interact with them by means of handles/tokens used in D3D8 API calls. Thus, from a D3D9 standpoint, we are responsible for managing the object lifecycle, and for releasing them when appropriate.
D3D8 typically does this on device release, since none of the above mentioned objects are considered perishable, ergo they survive device resets. So far we were not handling the release of VS & definitions and PS that were created by D3D9 for us.
This PR addresses that and also changes the stored pointers to Com objects, so that we can more easily clear them, instead of having to manually call Release().
Fixes this obscure crash in Hitman 2: https://github.com/AlpyneDreams/d8vk/issues/11 :tada: .
It will need some …

[d3d8] Clean up D3D9 shaders on D3D8 device release

---

src/util/config/config.cpp

Helps CPU bound performance.
<details>
<summary>Comparison</summary>
</details>
Didn't find that any of the other games from the dev around that time benefited. Neither the other Battle Mages game.

[util] Enable cachedDynamicBuffers for Battle Mages

---

src/util/util_small_vector.h

We can only move over the ptr if the other small_vector has MORE than N elements, otherwise it will still use the local  array.

[util] Fix small_vector move again

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swvp_emu.cpp

```
err:   VUID-VkImageViewCreateInfo-pNext-02662: 
err:   Validation Error: [ VUID-VkImageViewCreateInfo-pNext-02662 ] Object 0: handle = 0x612f93000000004e, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfcaee507 | vkCreateImageView(): pCreateInfo->pNext<VkImageViewUsageCreateInfo>.usage (VK_IMAGE_USAGE_SAMPLED_BIT) must not include any bits that were not set in VkImageCreateInfo::usage (VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT) of the image. The Vulkan spec states: If the pNext chain includes a VkImageViewUsageCreateInfo structure, and image was not created with a VkImageStencilUsageCreateInfo structure included in the pNext chain of VkImageCreateInfo, its usage member must not include any bits that were not set in the …
```

A bunch of validation error fixes

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h
src/d3d8/d3d8_include.h
src/d3d8/d3d8_multithread.cpp
src/d3d8/d3d8_multithread.h
src/d3d8/meson.build
src/d3d9/d3d9_bridge.h

By popular demand, thread-safe d3d8, ported over from d3d9 and sprinkled wherever it affects state. Unsure if anything is actually affected by it (based on testing so far doesn't seem like it), but the overhead is probably rather negligible anyway in d3d8 space.

[d3d8] Respect D3DCREATE_MULTITHREADED and make d3d8 thread safe

---

src/d3d9/d3d9_format.cpp

Some games will use these two formats (excessively even) with CreateOffscreenPlainSurface (d3d9) / CreateImageSurface (d3d8), which won't fail even for known unsupported formats. We've had the same problem with P8 on d3d8 side in the past.
WineD3D supports both R16 and AL16 along these lines, but not with CreateTexture (nor does it advertise them as supported formats). This PR brings us on par and is also meant to silence a lot of `ConvertFormat: Unknown format encountered` warnings we've seen in logs for these two formats in particular.
I've also cleaned up some supported formats from GetUnsupportedFormatInfo, for good measure (I'm assuming nobody bothered to remove them from there once support was added). 
Draft for now as I still have to:
- test the behavior on native WinXP
- see if …

[d3d9] Add R16 and AL16 as known unsupported formats + some cleanup

---

README.md
src/d3d9/d3d9_common_buffer.cpp
src/d3d9/d3d9_common_buffer.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_hud.cpp
src/d3d9/d3d9_hud.h
src/d3d9/d3d9_swapchain.cpp

Needs lots of testing.
This makes D3D9 devices, that are configured to always use software vertex processing (so not `MIXED`), always use the late per draw buffer upload path. We copy the vertex data that each specific draw accesses to a temporary buffer and render from that, similar to Up-draws.
This makes sense because games that use pure SWVP expect vertex processing to be synchronous which has lead to both bugs and performance problems. For example we used to run into issues when respecting NOOVERWRITE or have dozens or even hundreds of queue syncs per frame. Considering that SWVP is supposed to run on the CPU, the amount of vertices is hopefully small.
I hope this won't impact more modern or demanding games.
The game that inspires this was Phantasmat from this comment: …

[d3d9] Optimize SWVP devices

---

src/d3d9/d3d9_common_buffer.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_vertex_declaration.cpp
src/d3d9/d3d9_vertex_declaration.h

Based on #4274
Optimizes late buffer uploads (managed or per-draw) similar to how we're doing it for textures.
This avoids having to iterate over all 16 vertex buffers multiple times for every draw.

[d3d9] Optimize late buffer uploads with dirty bitmasks

---

src/d3d9/d3d9_device.cpp

Fixes #4291
The game uses the RESZ hack to copy from a `D3DFMT_D24S8` texture to one with format `D3DFMT_DF24`.

[d3d9] ResolveZ: Only copy aspects that both images support

---

src/util/config/config.cpp

Solve this error `err:   D3D9SwapChainEx: Failed to recreate swap chain: VK_ERROR_NATIVE_WINDOW_IN_USE_KHR`
After fix it works
PS: if run under 4K, LAA patch is suggested to avoid crash

[util] Solve Swapchain Error for Time Leap Paradise

---

src/d3d8/d3d8_buffer.h
src/d3d8/d3d8_device.h
src/d3d8/d3d8_options.h
src/util/config/config.cpp

Fixes missing textures in Rayman 3, a problem that based on online testimonies started to occur with the transition to Windows 7.
Test on Windows XP have shown that the game renders properly, so native behavior on age-accurate systems seem to differ from d3d9, as in D3DLOCK_DISCARD appears to be respected only for D3DUSAGE_DYNAMIC + D3DUSAGE_WRITEONLY.
Making it a draft for now, as it would need more testing to ensure there are no regressions in other titles.

[d3d8] Add an option to respect DISCARD only for dynamic write-only buffers

---

README.md
package-release.sh
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_adapter.h
src/dxvk/dxvk_allocator.cpp
src/dxvk/dxvk_allocator.h
src/dxvk/dxvk_buffer.cpp
src/dxvk/dxvk_buffer.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device.h
src/dxvk/dxvk_image.cpp
src/dxvk/dxvk_memory.cpp
src/dxvk/dxvk_memory.h
src/dxvk/dxvk_sparse.cpp
src/dxvk/hud/dxvk_hud.cpp
src/dxvk/hud/dxvk_hud_item.cpp
src/dxvk/hud/dxvk_hud_item.h
src/dxvk/hud/dxvk_hud_renderer.cpp
src/dxvk/hud/dxvk_hud_renderer.h
src/dxvk/hud/shaders/hud_chunk_frag_background.frag
src/dxvk/hud/shaders/hud_chunk_frag_visualize.frag
src/dxvk/hud/shaders/hud_chunk_vert.vert
src/dxvk/meson.build
src/util/util_bit.h

First part of a massive rework. Not going to merge this until after 2.4.1, and this needs a lot of testing anyway, especially on Nvidia and in more memory-constrained scenarios.
Currently, DXVK allocates video memory in chunks of up to 256 MiB, and uses an extremely basic per-chunk free list to allocate memory, employing a worst-fit strategy to suballocate memory from those chunks. The original reasoning here was that worst-fit tends to perform quite well with allocations of more or less the same size with respect to external fragmentation, and texture allocations generally satisfy that criterium.
However, this approach does come with drawbacks:
- The runtime complexity for **any** allocation is `O(n)`, with `n` being the total number of free ranges in all chunks of a memory type. Even …

Rewrite memory allocator

---

src/wsi/win32/wsi_platform_win32.h
src/wsi/win32/wsi_window_win32.cpp

That fixes a regression with Yakuza 0 introduced by commit ed9ffa6584dfb49a630df4d8cd7ec7fe29b1f23b (after which commit the game hangs with black screen on start).
There are actually two manifestations of essentially the same problem. 
1. The initial hang on start happens after the game sets fullscreen mode through dxgi and then calls GetFullscreenState which kicks off fullscreen state and retuns no fullscreen status. This is unexpected, game seems to refuse to do anything after this. What happens here is that the game didn't make the window visible yet before SetFullscreenState, it is only becoming visible in the course of configuring fullscreen mode (here on Windows WS_VISIBLE attributed is still not set while window is fullscreen and visible, but this is unrelated and unfixable in dxvk …

[dxgi] Delay qualifying foreground loss as occlusion

---

src/dxvk/hud/dxvk_hud_item.cpp

Correctly colors CACHED memory on UMA as well. Also fixed a VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT derp.

[dxvk] Fix HUD memory chunk colors on UMA

---

src/dxvk/dxvk_memory.cpp
src/dxvk/dxvk_memory.h
src/dxvk/hud/dxvk_hud_item.cpp

Does two very simple things:
- decide whether to nuke empty chunks based on the budget rather than heap size,
- show the used memory percetage relative to the reported budget too.
Not too interesting right now, but I want to use this to work out how useful the budget value actually is for decision making on different platforms / drivers, especially on Deck.

Memory budget stuff

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_state_block.cpp
src/d3d8/d3d8_state_block.h
src/d3d9/d3d9_device.cpp

Fixes all of Wine's D3D8 state block tests.
In short:
- fixed the default value of the D3DRS_POINTSIZE_MIN render state being 0.0f in D3D8 (this was changed to 1.0f in D3D9)
- capture VB stream state as part of D3D8 state blocks
- automatically capture state on state block creation via CreateStateBlock()
Master:
`0020:stateblock: 9283 tests executed (0 marked as todo, 0 as flaky, 108 failures), 0 skipped.`
This PR:
`0020:stateblock: 9283 tests executed (0 marked as todo, 0 as flaky, 0 failures), 0 skipped.`

[d3d8] Various Wine state block tests fixes

---

src/d3d9/d3d9_cursor.cpp
src/d3d9/d3d9_cursor.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h

Probably not an entirely sound approach, but it's a start. I believe we'll actually need to draw the cursor onto the final image ourselves, before the HUD. Some processing on the cursor bitmap surface that a game provides also needs to be done, because it needs to be trimmed to the bounding dimensions of pixels that contain color data and then blended.
I'm fine if @K0bin wants to pick up and reuse some of what I've done here, since the `d3d9_cursor.cpp/h` additions should be sound.
As is, the implementation is fully functional and sets/shows/hides a software cursor properly. However, the cursor surface is very unceremoniously sent onto the final backbuffer using StretchRect(). I had sort of hoped that would simply work, but alas.
As always, Dungeon Siege 2 is the game to test this with. …

[d3d9] Implement a software cursor

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h
src/d3d9/d3d9_common_texture.cpp

I've reworked our implementation of GetInfo() to more closely follow what d9vk is doing, namely:
- `pQuery->Issue()` will never fail in d9vk (and even if can fail according to spec, we shouldn't care much, as `pQuery->GetData()` would also then fail).
- `D3DDEVINFOID_RESOURCEMANAGER` and `D3DDEVINFOID_VERTEXSTATS`, though technically supported by d3d8 are not implemented in d9vk. D3D9's `CreateQuery()` will always return `D3DERR_NOTAVAILABLE` for both as it stands, thus we shouldn't really speculate on the outcome (removed the "unlikely" hint).
- According to specs, D3D9 `GetData()` should always be called with `D3DGETDATA_FLUSH` for the queries that D3D8 supports.
- D3D9 `GetData()` returns are inline with what `GetInfo()` should return if it reaches that point.
The above allows us to …

[d3d8] GetInfo rework and various assorted fixes

---

src/d3d8/d3d8.def
src/d3d8/d3d8.sym
src/d3d8/d3d8_d3d9_util.h
src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_interface.h
src/d3d8/d3d8_main.cpp
src/d3d8/d3d8_shader.cpp
src/d3d8/d3d8_state_block.h
src/d3d8/d3d8_swapchain.h
src/d3d8/d3d8_texture.h
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h

Fixes a rather large portion (in terms of failures, at least) of Wine's D3D8 device tests.
The changes are:
- fixed a type derp on texture subresource lookup
- don't allow mix-matched adapter and buffer formats in windowed mode (apparently that's not a thing in D3D8)
- make some D3D8 present parameter validations visible to the calling application
- cache (and hold references to) all the back buffers tied to an additional swapchain
- various additional CheckDeviceMultiSampleType validations that native also does (~TODO: check these on D3D9 side directly also~ They indeed check out on D3D9 as well)
- failure of device resets due to invalid losable count should return D3DERR_DEVICELOST
- can't create a 0 x 0 backbuffer in fullscreen (but windowed mode works, absolutely lovely)
- D3D8 …

[d3d8] Various Wine device tests fixes (Part 1)

---

src/d3d9/d3d9_cursor.cpp
src/d3d9/d3d9_cursor.h
src/d3d9/d3d9_device.cpp

Turns out @doitsujin's prophecy of games switching between software and hardware cursor has come true. Ironically it's with a game that apparently doesn't showcase its full cursor capabilities with WineD3D, namely Act of War.
I was never aware it had animated cursors, because WineD3D just shows the default cursor permanently throughout the game, whereas we now properly animate it depending on the situation. The animations end up on the software cursor path, while the default game cursor ends up on the hardware path.
Since we still need to render the software cursor as a 0-sized rect (to hide it in the backend) even on such a switch switch,  I had to add a bit of extra lifecycle tracking in the struct, however it does work as expected now.

[d3d9] Fix software cursor reset and transitions

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_util.h

Fixes #4338
I also added a bunch of missing likely/unlikely.
I'd prefer it if @misyltoad could take a look as she can better review how common each of those is.

D3D9: Fix fixed function sampler mask

---

src/d3d9/d3d9_cursor.cpp

Fixes a small potential derp. `ResetCursor()` is always called on device reset, at which point neither a software cursor nor a hardware cursor may be created, so there was really no point to always enqueue a software cursor reset.
Also, skip resetting a software cursor if a new one is set before a present has had the chance to process the reset flag.

[d3d9] Fix device reset handling when no cursor is set

---

src/d3d8/d3d8.def
src/d3d8/d3d8.sym
src/d3d8/d3d8_main.cpp

This has to be like the dumbest thing ever, but C&C: Generals is spamming calls to DebugSetMute() *every frame* whenever the slowdowns occur. Stubbing it makes it not choke. Fixes #4112.

[d3d8] Stub DebugSetMute to fix C&C:Generals performance

---

src/d3d9/d3d9_cursor.cpp
src/d3d9/d3d9_cursor.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h

Apparently only now it dawned on me that XHotSpot/YHotSpot are not in fact initial cursor positions, rather where the cursor pointer tip should be set within the bitmap coordinates :man_facepalming:. That means all the bitmap clipping & processing I was doing is rather superfluous, and in retrospect the new approach makes a lot more sense.
Anyway, this fixes some snapping on cursor bitmap transitions that I noticed and shouldn't be there. Now everything is properly aligned vs hotspot coordinates, as the application expects it to be.
This also means we frequently end up rendering the bitmap rectangle outside of the screen when the cursor is near screen edges, so that backend viewport-based positioning wasn't a bad idea after all :wink:.

[d3d9] Make proper use of X/YHotSpot for software cursors

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h

Fixes #4344
The map binds a `AUTOGENMIPMAP` texture as RT, calls `GenerateMipSubLevels` which clears the dirty bits, renders to the texture and then calls `GenerateMipSubLevels` again which just exits out early because of the cleared dirty bits.
The contents of mip 0 have changed however due to some drawing. I don't want to mark the texture mip gen bits as dirty on every single draw, so instead I decided to just don't clear them if the texture is currently bound as RT. They will get cleared once the game changes RT and then generates the mip levels.

[d3d9] Don't clear mipGenBit if texture is bound as attachment

---

src/d3d11/d3d11_query.h
src/d3d9/d3d9_query.h
src/dxvk/dxvk_cmdlist.cpp
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device.h
src/dxvk/dxvk_gpu_event.cpp
src/dxvk/dxvk_gpu_event.h
src/dxvk/dxvk_gpu_query.cpp
src/dxvk/dxvk_gpu_query.h
src/dxvk/dxvk_lifetime.cpp
src/dxvk/dxvk_lifetime.h

TL;DR finally figured out what some weird validation errors were about, we would sometimes use the same Vulkan query twice in a row for some really strange reason. There was also another long-standing issue where a D3D11 app overlapping scoped queries of the same type would lead to invalid Vulkan usage, this rework should fix both.
~~Only ran this through wine tests so far, edge cases definitely require testing, hence the draft.~~
Did more testing now, seems to work even in scary edge cases. Fixes #2698.

Properly reference-count queries and events

---

src/d3d9/d3d9_device.cpp

This doesn't fix anything besides getting rid of a warning but @WinterSnowfall said it would be good to add it so it isn't potentially missed whenever TruForm support is worked on.

[d3d9] Silence unhandled render state D3DRS_ADAPTIVETESS_Y

---

src/util/util_matrix.cpp

Let's be as precise as possible without breaking float boundaries.
Fixes #4340 and most likely the flickering problems in #4222. Also, what I thought was some shadow flickering on buildings in Act of War is also gone now.
I've also checked that the affected Wine test still passes.

[d3d9] Adjust matrix inversion boundary

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h

Simplified version of #4349 that removes some tracking.
It removes some more tracking that has kind of bothered me.

[d3d9] SIMPLIFIED: Only dirty frame buffer on render state changes if render area is impacted

---

src/util/config/config.cpp

Otherwise d3d9 mode thinks we only have 512MB vram which will lock the higher graphics presets.
~~I opted to put this in the d3d11 section as going by the Far Cry 2 config I assume we sort the games by their highest supported dxvk renderer (d3d12 not included).~~ See comment below

[util] Add Secret World Legends config and move Far Cry 2

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_interfaces.h
src/d3d9/d3d9_interop.cpp
src/d3d9/d3d9_interop.h
src/d3d9/d3d9_surface.cpp
src/d3d9/d3d9_surface.h
src/d3d9/d3d9_texture.cpp
src/d3d9/d3d9_texture.h

This extends the D3D9 device interop interface to allow creating surfaces and textures with custom image usage flags. This is useful, for example, if you want to add usage flags like `VK_IMAGE_USAGE_STORAGE_BIT` for writing to D3D9 textures in compute shaders.

[d3d9] Add ID3D9VkInteropDevice::CreateImage to create custom textures/surfaces

---

src/dxvk/dxvk_context.cpp

World War Z somehow manages to hit this.
Annoying problem, but since xfb is rare and expected to be slow we don't need to be smart here.

End transform feedback when changing the active graphics pipeline

---

.github/workflows/test-build-windows.yml
meson.build

While DXVK seems mostly meant for usage with Wine, a lot of people end up using it anyways as a D3D9 replacement on Windows due to native driver support getting worse or being dropped altogether and replaced with D3D9on12.
Generating PDBs for MSVC builds makes debugging DXVK issues a lot easier on Windows, especially when porting legacy D3D9/D3D8 code to use it. I believe PDB symbols would have been generated anyways for debug builds, but testing with release builds is sometimes required. 
Not sure if uploading the artifacts for the MSVC builds is a good idea, I presume there might have been a reason those weren't uploaded before. If those builds are not intended for anything other than testing, I could look into whatever PDB generation is possible under `mingw` without breaking anything …

[Build/CI] Build PDBs for MSVC builds + upload MSVC build artifacts.

---

src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_device.h
src/dxvk/dxvk_state_cache_types.h
src/util/sha1/sha1_util.h

Saves a few CPU cycles when creating shaders.
There's probably no good reason to change the hash algorithm for D3D9 since shaders there are tiny.

Do not use SHA-1 to look up D3D11 shaders

---

dxvk.conf
src/dxvk/dxvk_allocator.cpp
src/dxvk/dxvk_allocator.h
src/dxvk/dxvk_buffer.cpp
src/dxvk/dxvk_buffer.h
src/dxvk/dxvk_cmdlist.cpp
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device.h
src/dxvk/dxvk_image.cpp
src/dxvk/dxvk_image.h
src/dxvk/dxvk_memory.cpp
src/dxvk/dxvk_memory.h
src/dxvk/dxvk_options.cpp
src/dxvk/dxvk_options.h
src/dxvk/dxvk_sparse.cpp
src/dxvk/dxvk_sparse.h
src/dxvk/dxvk_swapchain_blitter.cpp
src/dxvk/hud/dxvk_hud_item.cpp
src/dxvk/hud/dxvk_hud_item.h
src/dxvk/hud/dxvk_hud_renderer.cpp
src/dxvk/hud/shaders/hud_chunk_frag_background.frag
src/dxvk/hud/shaders/hud_chunk_frag_visualize.frag
src/dxvk/hud/shaders/hud_chunk_vert_background.vert
src/dxvk/hud/shaders/hud_chunk_vert_visualize.vert
src/util/util_small_vector.h

Builds on all the reworks from the past couple of weeks to implement memory defragmentation.
As described in #4280, our memory allocator works on chunks of 256MB that are allocated from the system. The goal here is to make more efficient use of these chunks and *actually* return memory back to the system if we have a lot of unused memory sitting around. This is especially important under memory pressure (even more so on Nvidia due to the need of dedicated allocations for e.g. render targets), or if the app in question isn't actually a game but rather a launcher that temporarily eats over 1GB of VRAM but frees most of it when getting minimized.
As an example, Metaphor ReFantazio (the demo version in this case) allocates over 4GB of memory right at the start, just to free most of it right …

Memory defragmentation

---

src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h

Spotted some issues while investigating #4395:
- We shouldn't emit hundreds of `VkImageMemoryBarrier2`s during defrag when most of them don't even do a layout transition
This doesn't affect correctness, but makes renderdoc captures less painful to look at and saves some CPU cycles.
- Doing defrag where we did it was technically correct, but hard to reason about *why* it was correct.
- Image invalidation for sequential swap chains image recreation was essentially broken and wouldn't ensure that the images involved were actually transitioned back to the correct layout. This is a real bug, but not related to defrag.

Fix various image invalidation issues

---

dxvk.conf
src/dxvk/dxvk_memory.cpp
src/dxvk/dxvk_memory.h
src/dxvk/dxvk_options.cpp
src/dxvk/dxvk_options.h
src/util/config/config.cpp
src/util/util_bit.h

I hate everything about this, The game has some 432-byte constant buffer that it constantly `DISCARD`s but doesn't really bother writing to, yet it accesses the uninitialized data in the shader.
Before the memory rework, this was sort-of fine because per-buffer allocations were more or less set in stone, we'd grab some memory, clear it and then just reuse those regions, so any data not written at all would remain zeroed. The new allocator however allocates fresh memory on every `MAP_WRITE_DISCARD`, which means the memory we return to the app might have been used for a different purpose before and can contain stale data.
This workaround essentially zeroes all mapped memory allocations when they are freed. While this mostly happens on a worker thread, it is **very** CPU-intensive and slow, …

Work around Vindictus constant buffer breakage

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h
src/d3d9/d3d9_surface.cpp
src/d3d9/d3d9_volume.cpp

Built on top of #4320, I'm now expanding and hoping to fix (most) of the Wine tests dealing with surface locks (LockRect/LockBox validations).
Work so far:
- d3d8/9 seem to validate the boundaries of the locking rectangle for D3DPOOL_DEFAULT surfaces with formats that need to be block aligned, surfaces created via `CreateImageSurface` and cube textures outside of D3DPOOL_DEFAULT (the last one being specific to D3D8). ~If only it were so simple, though. Essentially **all** validation are done on surfaces or subsurfaces of textures so we need some way to determine the origin of a surface. To that end I've added a `D3DRESOURCETYPE` Type variable part of `D3D9_COMMON_TEXTURE_DESC`.~
- a ~very highly cursed~ alignment lock check for block aligned formats, ~performed only on direct calls to …

[d3d8] Wine device tests fixes (Part 2) - LockRect/LockBox

---

src/dxvk/dxvk_barrier.cpp
src/dxvk/dxvk_cmdlist.cpp
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_sparse.h

Now that we only have one single `DxvkContext`, we can be a bit more aggressive about pulling copies into the init command buffer in order to reduce barrier and/or render pass counts in some cases, ideally without discarding the destination resource.
Previously, we would only do this on full buffer uploads, this new code covers image uploads and actual GPU->GPU buffer copies as well.
An alternative implementation would work based on barrier tracking and be more granular, but since that's **much** more expensive I don't think it's warranted, especially since the issue we're trying to solve isn't all that common to begin with.
There's probably more we can do here (moving image ClearUAV perhaps, or at least related barriers), need to investigate.

Further optimize certain copies

---

src/d3d9/d3d9_interfaces.h
src/d3d9/d3d9_volume.cpp

In the spirit of #4193, this extends ID3D9VkInteropTexture so that it can be used for volumes in addition to surfaces and textures. I don't expect this to create any new issues here since a volume is just a surface with depth and we already expose this for surfaces and textures.

[d3d9] Add texture/image interop to volumes

---

src/util/config/config.cpp

The GOG edition uses `Prince of Persia.exe` as the main executable name, although it also has the launcher.
It will similarly hang on loading screens without a framecap.

[util] Include Prince of Persia main executable

---

src/d3d9/d3d9_adapter.cpp

Fixes #4288. Not the shadows, those are fine. The game does however pick the first (lowest ordinal) mode for a particular resolution. 
Since we were ordering them ascending by refresh rates, this has the potential to end up on 24 Hz. The game offers no means of manually selecting refresh rates. Which is why I suspect the reporter of the issue gets stuck on 50 Hz, being on AMD (see below output sample).
Behavior on native drivers is as follows:
- Nvidia:
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 60 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 59 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 50 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 120 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 100 Hz
- AMD:
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 50 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 59 Hz
>     D3DFMT_X8R8G8B8 1920 x 1080 @ 60 …

[d3d9] Order modes descending by refresh rate

---

src/util/config/config.cpp

Fixes #4422. While disabling direct buffer mapping got rid of some queue syncs caused by buffer locks, which improved the game's quirky frame-rate heuristics, it seems to break some in-game effects. Guess it is what it is.
The games's SWVP mode (hackable through the game's ini) seems to rely on disabling direct buffer mapping to render properly, but since it's not recommended or exposed by the game and HWVP now works properly, that's not that big of a problem.

[util] Re-enable direct buffer mapping for Rayman 3

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format_helpers.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_util.h

Adds support for clearing compressed formats and errors out on depth formats, which fixes a wine test. Also ensures that we can actually render to the image in question, there were a **lot** of related validation errors.
This fixes `color_fill_test` crashing inside the CS thread.

D3D9: Fix various ColorFill cases

---

src/d3d9/d3d9_swapchain.cpp

Tenatively fixes #3894.
Creating a device with NULL hFocusWindow and hDeviceWindow already works, so does getting the backbuffers. However, Present crashes because  `m_wctx` is uninitialized when m_window is nullptr.
Moving the return a bit earlier makes it work just fine however. Haven't checked if this messes with anything else, but I doubt any of the `m_wctx` stuff is relevant for this use case.
I have yet to check if rendering to the backbuffer works in this situation, but I think it will. Drafting until I actually check on that bit.

[d3d9] Early return D3D_OK on present with a NULL m_window

---

src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device.h

Disables the workaround introduced in 00872e9e4fdd87d92f2dd662791b8de6a7edf10c on drivers that were not affected by the bug.

Only force late clears on older Nvidia drivers

---

.github/workflows/test-build-windows.yml

Merges the two separate archives in to one and puts the dll and pdb files in a x32 and x64 folder. Currently the two archives package the output in a folder called src and the files in subfolders of the respective names. E.g. `src/d3d9/d3d9.dll` etc.
This makes the MSCV artifacts archive match the regular artifacts CI output.

[CI] Make MSCV artifacts output match the regular artifact CI

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_interface.cpp
src/d3d9/d3d9_interface.h

Fixes Black Desert d3d9 device initialization (apparently the game creates a `D3DDEVTYPE_NULLREF` device to do some form of cursed d3d11 interop).
Here is the initial call, for future reference:
`IDirect3D9::CreateDevice(this = 0x6850400, Adapter = D3DADAPTER_DEFAULT, DeviceType = D3DDEVTYPE_NULLREF, hFocusWindow = NULL, BehaviorFlags = D3DCREATE_HARDWARE_VERTEXPROCESSING, pPresentationParameters = [{BackBufferWidth = 1920, BackBufferHeight = 1080, BackBufferFormat = D3DFMT_X8R8G8B8, BackBufferCount = 1, MultiSampleType = D3DMULTISAMPLE_NONE, MultiSampleQuality = 0, SwapEffect = 0, hDeviceWindow = NULL, Windowed = FALSE, EnableAutoDepthStencil = FALSE, AutoDepthStencilFormat = D3DFMT_UNKNOWN, Flags = 0x0, FullScreen_RefreshRateInHz = 0, PresentationInterval = …

[d3d9] Skip some validations when hDeviceWindow is NULL

---

src/d3d9/d3d9_options.cpp

[d3d9] Enable strict float emulation by default on new Nvidia drivers

---

dxvk.conf
src/d3d11/d3d11_buffer.cpp
src/d3d11/d3d11_buffer.h
src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_context_def.cpp
src/d3d11/d3d11_context_def.h
src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_initializer.cpp
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/d3d11/d3d11_texture.cpp
src/d3d11/d3d11_texture.h
src/dxvk/dxvk_buffer.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device.h
src/dxvk/dxvk_image.cpp
src/dxvk/dxvk_image.h
src/util/config/config.cpp

For real now. Main difference to the original PR is that querying linear subresource layouts has a much cleaner solution now and is done in such a way that we can query it *before* creating an image, so we can decide which tiling mode to use based on that.
We also try to use `LINEAR` tiling for more resources now, specifically:
- Images that are essentially linear (i.e. have a height and depth of 1)
- Images that look like a video. We use some dumb heuristic to determine this based on the aspect ratio and format size. We also try to keep these in system memory since they are likely only going to be accessed once per frame anyway.
- Huge images. This both saves memory and makes Warhammer III perform acceptably without an app profile.
This fixes a bunch of bugs, gets rid of another config …

D3D11: Improve direct image mapping v2

---

.github/workflows/test-build-windows.yml

Fixes the msvc CI builds not including the git commit in the dxvk version because 'git describe --dirty=+'  called though meson fails.

[CI] Add fetch-depth: 0 to Windows CI

---

.github/workflows/artifacts.yml
.github/workflows/test-build-windows.yml

Now future-proof with free auto-upgrades! Also, bigger number better (we get newer kernels in the linux runners, which might help speed things up a little), otherwise rather inconsequential since actual builds are containerized. windows-2022 is currently latest anyway, so no actual change there.
P.S.: ubuntu-20.04 is set to be deprecated by the end of the year anyway.

[CI] Use latest action runner images

---

README.md
meson.build

Statically linking the run-time library in MSVC is controlled via [b_vscrt in Meson](https://mesonbuild.com/Builtin-options.html#base-options). I've switched the default to `static_from_buildtype`, to get the statically linked equivalent of default behavior.
Needs some sanity testing at least to confirm it builds something functional.

[build] Use the static version of the run-time library for MSVC builds

---

dxvk.conf
src/dxvk/dxvk_memory.cpp
src/dxvk/dxvk_options.cpp
src/dxvk/dxvk_options.h

We still don't understand what the problem is or to which extent it affects other games, so unless a solution magically pops up by next week, we should disable defragmentation on this driver for now to reduce breakage for users.
See: #4395, https://gitlab.freedesktop.org/mesa/mesa/-/issues/12084

Disable memory defragmentation on ANV

---

src/d3d9/d3d9_fixed_function.cpp
src/dxso/dxso_compiler.cpp
src/dxso/dxso_compiler.h
src/spirv/spirv_module.cpp
src/spirv/spirv_module.h

Fixes #4319, Supersedes #4439.

DXSO: Fix various shader instructions

---

src/util/config/config.cpp

Crashes because of static ags on amd systems which report HDR support.

[util] Hide amd for GTA The Definitive Edition trilogy

---

src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_texture.h
src/dxvk/dxvk_memory.h

Should fix #4467, supersedes #4460.

[d3d11] Store map mode as raw integer

---

src/dxgi/dxgi_options.cpp
src/util/config/config.cpp

For when UE4 games aren't caught by our regular workaround.

[dxgi] Introduce dxgi.enableUe4Workarounds option

---

src/d3d8/d3d8_d3d9_util.h
src/d3d8/d3d8_device.cpp

Two rather derpy derps. Should now work as intended, and the `-1u` part should also silence a clang warning.

[d3d8] Use unsigned values to identify remapped sampler states

---

src/util/config/config.cpp

Currently with Proton/Wine these games will prefer to use the iGPU. On systems using the Nvidia proprietary driver this can make them bug out so they don't start or show a gray screen.
It has to be figured and fixed why they even want to use the iGPU, but in the meantime we might as well work around the issue.

[util] Hide iGPU for WoW and WC3 Reforged

---

src/util/config/config.cpp

My brain didn't catch on that this would also affect the original Warcraft 3 as it isn't a dxgi config. Thanks @WinterSnowfall 
Reforged sits in a folder called x86_64 which should filter out the original Warcraft 3

[util] Don't include original WC3 in Reforged config

---

src/d3d9/d3d9_device.cpp

Been doing a lot of testing of this issue to figure out what is up and down.
The [original issue the current code fixed](https://github.com/doitsujin/dxvk/issues/1854) is actually a game bug that also happens with the version of the FF13Fix addon used back then (1.4.6). On Windows with native d3d9 amd drivers this issue can be observed when running the game with a 2560 x 1440 resolution. 
This was then later fixed in the addon and so if you download the latest version of FF13Fix it will look correct both with the native driver and dxvk with a 0.5f correctness factor. https://github.com/rebtd7/FF13Fix/releases
> Fixed misaligned screen effects (proper fix for the 1440p resolution)
Fixing the game bug back then in dxvk sadly introduced issues in other games like …

[d3d9] Change correctness factor to 0.5f

---

meson.build

Leftover from when tests were in the main repository

[build] Remove old d3dcompiler_47 dependency

---

src/util/config/config.cpp

Indirect bug report on the Borderlands 2 PCGamingWiki page

[util] Set Borderlands 2 floatEmulation to Strict

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_main.cpp
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_interface.cpp

I'm aiming to fix a few more d3d8/d3d9 Wine devices tests. 
So far:
- readdressed a relaxation of validations done to prevent crashing in Black Desert in a way that now passes the affected Wine device tests
- fixed invalid storage of VS/PS functions and declarations as well as other d3d8 VS/PS behavior
- added DS dimensions validation on SetRenderTarget (d3d8 specific)
- added PS/VS version validation on shader creation (d3d8)
- partially implemented ValidateVertexShader/ValidatePixelShader, with version validations (d3d8)
- fixed d3d9 multiple image unlock behavior
- validated RT parent device during SetRenderTarget
- added various NormalizeTextureProperties validations

[d3d8] Wine device tests fixes (Part 4)

---

dxvk.conf
src/d3d11/d3d11_swapchain.cpp
src/d3d11/d3d11_swapchain.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h
src/dxvk/dxvk_presenter.cpp
src/dxvk/dxvk_presenter.h
src/util/config/config.cpp

So far we're always letting the driver decide whatever it wants to, but since Windows doesn't seem to give drivers any sort of low-level access to anything more modern than D3D9-level presentation APIs we just end up in a situation that sucks for everyone anyway, so migth as well disable it and at least have a slim chance of things like alt+tab actually working.
Should also fix #4465 and related issues, I can't be arsed to add hundreds of app profiles for this garbage.

Always disable exclusive full-screen on Windows

---

src/util/config/config.cpp

Intros are played back using ddraw, and main menu isn't rendered otherwise.

[util] Enable deferSurfaceCreation for the Codename Panzer series

---

src/d3d9/d3d9_annotation.cpp

The `D3DPERF_` PIX event functions can crash the app due to a race condition. Typically this means that the calls to `EmitCs` trigger an access violation because `m_csChunk` is null. This PR fixes it by simply locking the device before calling `EmitCs` for these functions. The issue is worse in complex pipelines with a lot of markers.

[d3d9] Fix race condition in PIX events

---

src/d3d9/d3d9_interface.cpp

Fixes #4496. Turns out 9Ex has a much higher back buffer limit. Thanks to @Blisto91 for finding the header constants.

[d3d9] Use header back buffer limits during validation

---

meson.build

Starting with MinGW 14, we get these lovely repeated warnings:
```
In file included from ../../source/dxvk-fork/src/d3d11/d3d11_buffer.h:11,
from ../../source/dxvk-fork/src/d3d11/d3d11_context.h:16,
from ../../source/dxvk-fork/src/d3d11/d3d11_context_imm.h:7,
from ../../source/dxvk-fork/src/d3d11/d3d11_initializer.cpp:3:
../../source/dxvk-fork/src/d3d11/d3d11_resource.h: In member function ‘dxvk::D3D11ResourceRef& dxvk::D3D11ResourceRef::operator=(dxvk::D3D11ResourceRef&&)’:
../../source/dxvk-fork/src/d3d11/d3d11_resource.h:292: note: ‘-Wmisleading-indentation’ is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
292 |       if (m_resource)
../../source/dxvk-fork/src/d3d11/d3d11_resource.h:292: note: adding ‘-flarge-source-files’ will …
```

[build] Suppress gcc misleading indentation warnings

---

src/d3d8/d3d8_d3d9_util.h
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_format.h
src/d3d9/d3d9_stateblock.cpp
src/d3d9/d3d9_stateblock.h
src/d3d9/d3d9_surface.cpp

~WIP to fix several low hanging d3d9-specific Wine device tests.~ Done.
So far:
- fixed SRCCOLOR2 & INVSCRCCOLOR2 caps being exposed with non-9Ex devices/interfaces (allegedly only WARP does this)
- fixed the `test_refcount` Wine test by preventing device child refcount underruns (we were already doing this in d3d8, thanks to Motor City Online)
- apply MultiplyTransform state block behavior universally (it is not d3d8 specific)
- operations on clip planes with an out of bounds index will reflect on the highest valid clip plane
- add surface format validations to `D3D9Surface::GetDC()` (note that valid formats still don't seem to work properly here, which might be something we'd want to revisit at some point)
- fixed a d3d8/d3d9 difference of expected error codes on failed device reset …

[d3d9] Several Wine device test fixes

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_spec_constants.h
src/d3d9/d3d9_state.h
src/dxso/dxso_compiler.cpp

Add a new spec constant with a mask of the enabled clip planes such that they can be optimized out to improve performance.
For GPL shaders, override what we return here so it's always true and don't bother putting the mask in the UBO.

[d3d9] Spec-constant out writes to clip distances when disabled

---

src/d3d9/d3d9_shader_validator.h

Fixes #2045.
(Working) rebase of @misyltoad's former d3d9-shader-val2 branch, which doesn't crash on the main menu with The Void. On top of it I've added a crude adaptation of @gofman's PS input counts validation. It seems to work fine in terms of actually doing what's expected of it ~, but it doesn't currently fix the crashing issues in the game~.
A save file that can reproduce the crashing can be found [here](https://github.com/ValveSoftware/Proton/issues/4527#issuecomment-756287834).

[d3d9] Implement several IDirect3DShaderValidator9 validations

---

src/util/config/config.cpp

The `d3d9.floatEmulation = Strict` was tested by @Blisto91 and it fixes a problem, but it is only relevant for Borderlands 2, as the test was not performed in The Pre-Sequel nor are there any bugs reported for the Pre-Sequel game regarding the need of Strict floats.
This PR reorganizes Borderlands games fixes and only keeps Strict float emulation for BO2.

[util] Separate Borderlands 2 fixes from Borderlands: The Pre-Sequel

---

src/d3d8/d3d8_state_block.h

Minor nit, mostly for my future sanity. We sort of lucked out so far, because that header is *somehow* included through other imports, but we should also add it explicitly here.

[d3d8] Add missing include to d3d8_state_block.h

---

src/d3d9/d3d9_device.cpp

Yet another validation we were missing. Tested both d3d8 and d3d9, they both behave the same here.

[d3d9] Validate depth and stencil clears

---

src/util/config/config.cpp

Game uses D3D11 according to https://www.pcgamingwiki.com/wiki/Earth_Defense_Force_5#API. Currently it's listed in the D3D9 section.

[util] Adjust "Earth Defense Force 5" position

---

src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_shader.cpp
src/d3d9/d3d9_shader.h
src/dxso/dxso_compiler.cpp
src/dxso/dxso_compiler.h
src/dxso/dxso_module.cpp
src/dxso/dxso_module.h
src/util/config/config.cpp

Fixes #4387
Alpha Protocol binds a cube texture to a slot which is declared as a 2d texture in the shader. Binding a mismatching texture type leads yields (0,0,0,0) (yes, alpha 0, unlike binding NULL) on native D3D9. See the table inside the issue.
I also checked that this is checked at draw time, not at the time of the SetTexture call. So binding a shader with a correct texture type afterwards results in correct rendering and the other way around as well. 
Because if there's one thing the D3D9 frontend needed, it is more bit field tracking... :)

D3D9: Handle binding mismatching texture types

---

src/d3d9/d3d9_device.cpp

Fixes #4532
I somehow managed to miss those lines when I fixed more or less the same mistake but in the code paths for programmable shaders. Now it only impacts games using the fixed function pipeline.

[d3d9] Fix messing up the dirty textures bitmask

---

src/spirv/spirv_module.cpp

Currently the grad and const offset image operand ids are emitted in the incorrect order. This causes incorrect code gen if both the grad and const offset image operands are used.
https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Image_Operands
This fixes the compilation error found when running TopSpin 2k25 through DXVK using the NVIDIA proprietary Vulkan driver.
https://github.com/ValveSoftware/Proton/issues/7684

[spirv] Emit the grad and const offset image ops in the correct order

---

src/d3d9/d3d9_device.cpp

Fixes https://github.com/ValveSoftware/Proton/issues/1277

[d3d9] Skip texture type check when forceSpecConst option is active

---

src/d3d9/d3d9_surface.cpp
src/d3d9/d3d9_volume.cpp

Based on a test that I wrote and ran on Windows XP it looks like:
- d3d9 behaves similarly to d3d8 during LockRect/Box
- ~LockRect doesn't discriminate based on RTYPE and textures also get their pLockedRect contents cleared~
So the Wine tests were partially incorrect for d3d8 and incomplete for d3d9 (the Wine test in question was d3d8 specific, in all fairness).
I'm waiting for @Blisto91 to confirm modern native behavior, and in the meantime I will do some general testing. Not that I expect anything to blow up due to this minor nit, but you never know.
Edit: All the above is confirmed on modern AMD and Intel Windows drivers.

[d3d8/9] Clear pLockedRect/Box contents universally on lock

---

src/d3d9/d3d9_shader_validator.cpp
src/d3d9/d3d9_shader_validator.h
src/d3d9/meson.build

I had hoped the input count validation would work globally, but apparently it regresses that particular game.
There's no nicer way to handle this unfortunately, since we're dealing with entirely undocumented behavior, so I've hidden the offending validation behind a config option and enabled it only for The Void, the only known game that actually needs it.
Also part of this PR, I've refactored the code to sit in its own .cpp file (as I should have done from the start really).

[d3d9] Refactor D3D9ShaderValidator

---

src/d3d9/d3d9_shader_validator.cpp

Tentatively fixes #4537, by making sure we don't read tokens out of bounds. The Void still works fine with the change (ergo the validation still fails, as it's supposed to).

[d3d9] Use cdw to iterate over register tokens in D3D9ShaderValidator

---

dxvk.conf
src/dxvk/dxvk_options.cpp
src/dxvk/dxvk_options.h
src/dxvk/dxvk_presenter.cpp
src/dxvk/dxvk_presenter.h

It sucks that Windows users have to choose between functioning VRR, HDR and present_wait (aka any sort of frame latency guarantees) on the one hand, or being able to alt+tab out of their games on the other, but there's not much we can really do as long as win32 vulkan WSI is stuck in d3d9 kinds of stone age.
Currently untested. Closes #4595.

Reintroduce config option to enable FSE on Windows

---

src/util/config/config.cpp

Fixes invisible terrain on Intel (Windows and Linux)

[util] Enable zeroInitWorkgroupMemory for Far Cry 5 and New Dawn

---

src/util/config/config.cpp

The game will prefer other vendors over Intel even if the latter is the dGPU in the system. It likely assumes that Intel is always a iGPU. This also happens with the native game on Windows and so isn't a Linux exclusive. Both in d3d11 and d3d12 mode.
Bright Memory: Infinite which is a newer game does not seem to suffer from this.

[util] Enable hideIntegratedGraphics for Bright memory

---

src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_compiler.h

Halo MCC is broken and reads PS inputs outside the declared range, which causes flickering on Nvidia, see https://github.com/ValveSoftware/Proton/issues/2907#issuecomment-2569997475.
Needs extensive testing in games that are known to use geometry and tessellation shaders, since handling shader i/o is finicky enough as-is.

Bound-check dynamically indexed shader input registers

---

src/dxvk/dxvk_instance.cpp
src/dxvk/dxvk_instance.h

There was a major bug in #4505 where the instance extension name set is freed from scope which invalidates the strings in `m_extensionNames`. This is trivially fixed by storing the extension set in `DxvkInstance`. Not sure how I didn't notice this, I think when I tested it the custom memory allocator my project uses left the freed string data untouched on the heap or something. Anyway, this PR fixes it.

[d3d9] Fix invalid strings returned by GetInstanceExtensions

---

src/d3d9/d3d9_shader_validator.cpp
src/d3d9/d3d9_shader_validator.h

If something fails, print the entire instruction as dwords.

Add more logging to D3D9 shader validation

---

src/dxvk/dxvk_presenter.cpp

Unless it's NATIVE_WINDOW_IN_USE. Should fix a regression where D3D swapchain creation would succeed on out-of-memory errors.

[dxvk] Error out on surface creation again

---

src/d3d11/d3d11_view.h

I don't know if passing by value was intentional, but it seems to cause stack alignment issues when building DXVK with AVX2 and along with glibc assertions (`_GLIBCXX_ASSERTIONS`) enabled. DXVK crash is reproduced in game 20 Minute Till Dawn under the above conditions. GDB backtrace showed the following:
```gdb
Thread 57 "UnityGfxDeviceWorker" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 528]
0x00006fffd95503ab in dxvk::CheckViewOverlap<dxvk::D3D11ShaderResourceView, dxvk::D3D11DepthStencilView> (a=0x66784000, b=0x72d2d0)
at ../../dxvk/src/d3d11/d3d11_view.h:78
78	    return a && b && CheckViewOverlap(a->GetViewInfo(), b->GetViewInfo());
```
The crash issue is fixed when function takes both arguments by reference.

[d3d11] Fix missing argument reference

---

src/util/config/config.cpp

In both the base game and expansion the Water and Shader Detail options are locked at their lowest value when they see Intel. In the base game (not expansion) the AA option disappears for some reason when it sees vram at 2075MB and above.

[util] Add configs for Star Wars Empire at War

---

meson.build

I know DXVK doesn't officially support AVX builds, but I'd still like to suggest this flag to fix stack alignment issues when using mingw, since apparently i686-w64-mingw32 assumes that stack alignment is 16-bit when SSE is used, which is incorrect and causes game crashing issues. Wine experienced similar issues and added this flag about a year ago to workaround them by ensuring that the stack alignment is always 4 bytes, please see for more details:
https://gitlab.winehq.org/wine/wine/-/merge_requests/4030
https://gitlab.winehq.org/wine/wine/-/commit/4b458775bb8c9492ac859cfd167c5f54f245dec1
I'm fine if there any concerns why this can't be merged, as I realize that stack alignment issues need to be fixed either on the compiler side or by more courteous code, but it's too hard to debug, …

[build] Use -mpreferred-stack-boundary=2 on 32-bit x86

---

dxvk.conf
src/d3d8/d3d8_d3d9_util.h
src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h
src/d3d8/d3d8_interface.cpp
src/d3d8/d3d8_main.cpp
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_interface.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_shader.cpp
src/dxso/dxso_options.cpp
src/dxso/dxso_options.h

Fixes #4625 and follows up on an idea I've had in the d8vk days, see https://github.com/AlpyneDreams/d8vk/pull/208.
Extends D3D7-compatible FF only caps (aka disabling programmable shader support) to D3D8 when using `d3d9.shaderModel = 0`, and also validates shader versions on creation in D3D9.
Useful for debugging and for nostalgia reasons (with games that do handle such situations properly).

[d3d8/9] Proper (and age accurate) handling of d3d9.shaderModel = 0

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_options.cpp

Thanks to @Blisto91 for noticing it.
D3D9 archeology strikes again, as some PS version 2.1 have been spotted in the wild. I can only assume they correspond to the more lenient 2_x SM2 mode, although that doesn't come with an equivalent cap at device level.
I have found obscure references that ATI provided an override to 2.1 at some point at least: https://www.bodnara.co.kr/bbs/article.html?num=49848 .
The conventions around 2_x are very unclear, so this PR relaxes the minor version checks with SM2, to ensure we don't cause any issues with late D3D9 games.

[d3d9] Relax SM2 minor version checks on shader creation

---

src/d3d9/d3d9_adapter.cpp

These were ultimately (largely) correct, but they do have D3D constants defined.
~I still have to check how all of these show up on a SM1 capable card, so WIP for now.~ Update: I've checked, and they're all 0 for SM1 (and fixed-function ofc).
Doubt it matters much beyond esthetics, but let's unleash it in experimental for a while.

[d3d9] Adjust SM2 VS/PS caps

---

src/d3d11/d3d11_video.cpp

Issue: D3D11VideoProcessorInputView constructor ignores D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC::Texture2D.ArraySlice parameter and always sets viewInfo.minLayer to 0.
The fix assigns the correct array layer value.

Assign viewInfo.minLayer for D3D11VideoProcessorInputView

---

src/d3d9/d3d9_adapter.cpp

Missed this earlier, as it is apparently a SM3-specific thing. Docs say: 
> VertexTextureFilterCaps indicates what kind of filters are allowed at the vertex texture samplers. D3DPTFILTERCAPS_MINFANISOTROPIC and D3DPTFILTERCAPS_MAGFANISOTROPIC are disallowed.
However modern Nvidia supports:
```
Listing VertexTextureFilterCaps support:
- D3DPTFILTERCAPS_CONVOLUTIONMONO is not supported
+ D3DPTFILTERCAPS_MAGFPOINT is supported
+ D3DPTFILTERCAPS_MAGFLINEAR is supported
- D3DPTFILTERCAPS_MAGFANISOTROPIC is not supported
- D3DPTFILTERCAPS_MAGFPYRAMIDALQUAD is not supported
- D3DPTFILTERCAPS_MAGFGAUSSIANQUAD is not supported
+ D3DPTFILTERCAPS_MINFPOINT is supported
+ D3DPTFILTERCAPS_MINFLINEAR is supported
+ D3DPTFILTERCAPS_MINFANISOTROPIC is supported
- D3DPTFILTERCAPS_MINFPYRAMIDALQUAD is not …
```

[d3d9] Report vertex texture filtering support only for SM3

---

src/util/config/config.cpp

I'm having a good day so I decided to fix this game. Somehow the config options got lost when we merged d8vk in 2.4. This PR simply restores the intended configuration by setting `d3d8.scaleDref` to `24` which fixes shadow buffers (#4257). This PR also sets `deviceLossOnFocusLoss` to fix the game crashing when alt-tabbing.
For more info on Dref scaling, you can see [here](http://web.archive.org/web/20070104115249/http://www.nvidia.com/object/General_FAQ.html#G5), specifically:
> We've changed the behavior of hardware shadow maps between the DirectX8 and DirectX9 interfaces.  In DirectX8, you're required to scale the interpolated z component (that will be compared with the value in the shadow map) by the bit depth of the shadow map itself.  Starting with the DirectX9 interfaces, we've …

[d3d8] Restore config for Splinter Cell

---

src/util/config/config.cpp

A bunch of alt-tab related issues are gone on current master which allows a small builtin config cleanup.
This has been tested on a RTX 4080 in KDE Wayland, KDE X11 and Windows.
Delta Force, The Sims 3, Guild Wars 1 and Splinter Cell Conviction work out of the box since https://github.com/doitsujin/dxvk/pull/4609 so the configs aren't needed.
Rise of Nations is fine since the 2.4.1 release without the config.
Closes https://github.com/doitsujin/dxvk/issues/4082

[util] Cleanup some deviceLossOnFocusLoss configs

---

src/util/config/config.cpp

Adds profile for Trainz v1.3, which resolves black screen after alt-tab for Trainz.
Can close #4116

[d3d8] Fix black screen after alt-tab for Trainz v1.3

---

src/d3d8/d3d8_device.cpp
src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h
src/dxvk/hud/dxvk_hud_item.cpp
src/dxvk/hud/dxvk_hud_item.h

Kind of a minor derp that went unnoticed so far: in d8vk we were only setting the correct API level for the implicit swapchain. If games decided to create any additional swapchains, the HUD would incorrectly show D3D9.
I've uncovered this thanks to Serious Sam (The First/Second Encounter), which does just that.
The PR removes the needless `SetAPIName` cascading calls from the d3d9 bridge and simply relies on the D3D8 compatibility mode when determining the HUD API level.

[d3d8] Use D3D8 compatibilty mode to set HUD API level

---

src/util/util_vector.h

Stack alignment is 4 bytes on 32-bit, and we cannot align variables on the stack, so this is technically broken. Use unaligned stores instead even if those are a bit slower.

[d3d9] Do not assume 16-byte alignment in replaceNaN

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_main.cpp
src/d3d8/d3d8_shader.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_shader_validator.cpp

Fixes #4113.
https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3d9types/ne-d3d9types-_d3dshader_instruction_opcode_type
The information in the docs isn't clear or complete, but it is at least clear that RSQ isn't the only opcode which requires the explicit use of a replicate swizzle for its inputs.
If the swizzle on inputs is somehow `.xyzw` / D3DVS_NOSWIZZLE (although that is technically illegal in the context of the affected opcodes) it appears native d3d8 does indeed impose a replicate swizzle, as @AlpyneDreams has already determined when looking at **Indiana Jones And The Emperor's Tomb**, and also based on empirical evidence it appears `.w` is the one that makes things look as expected, and in this case also fixes the missing fog in **NFS Hot Pursuit 2**.
Needs testing …

[d3d8] Fix up swizzle for all opcodes requiring a replicate swizzle

---

src/util/config/config.cpp

Cursed fix for #4666.
This seems to be outside of our control as this should not happen to begin with.

[dxvk] Work around locale-dependent regex parsing crash

---

src/dxvk/dxvk_context.cpp

See #4641. Currently untested.

[dxvk] Fix initializing buffers with non-dword sizes

---

src/dxvk/hud/dxvk_hud_renderer.cpp

This was tripping me up when I was modifying the HUD to display a custom font. Sorry if this is not correct.

dxvk_hud_renderer.cpp: Rename `textBufferDescriptor` to `drawArgsDescriptor`, `drawBufferDescriptor` to `drawInfosDescriptor`

---

src/dxvk/dxvk_presenter.cpp
src/dxvk/dxvk_presenter.h
src/dxvk/dxvk_queue.cpp

The signaling thread can queue up a wait while the swapchain is being destroyed, which blows up. This also fixes a related race condition where we would queue up a wait using the wrong present mode.
This is somewhat fragile in the sense that the queue worker *must* call signalFrame for each and every present, or this will fall apart.
Needs testing.

[dxvk] Fix potential race conditions w.r.t. swapchain destruction

---

src/d3d9/d3d9_cursor.cpp
src/d3d9/d3d9_cursor.h
src/d3d9/d3d9_device.cpp

Fixes #3020 on Windows as well.
Games relying on software cursors apparently also call SetCursorPosition on each frame, and since we call ::SetCursorPos(X, Y) when that happens, on native Windows that tends to cause some strange movement feedback for some reason when we later retrieve the cursor position before present, using ::GetCursorPos(). And, you guessed it, this works just fine in Wine...
Regardless, what seems to work just as fine both on Windows and Wine is simply using the coordinates passed by the application with SetCursorPosition calls instead of us getting the position of the win32 cursor before present.
The downside is that if any game expects software cursors to work without it calling SetCursorPosition on each frame, it will be very very disappointed now.
Needs a bit more …

[d3d9] Update software cursor position using SetCursorPosition

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h

Fixes #4138. I narrowed it down (using apitrace) to some odd ZBIAS values we were getting in dxvk. Turns out we were casting things incorrectly in `GetRenderState()`.

[d3d8] Fix invalid casting in GetRenderState

---

meson.build

The "v" prefix was causing the version to be incorrectly set for generated files (such as pc files for pkg-config).
Dropping the prefix fixes the issue.

meson: Fix version construct by dropping the "v" prefix

---

src/dxvk/dxvk_latency_builtin.cpp
src/dxvk/dxvk_latency_builtin.h
src/dxvk/dxvk_latency_reflex.cpp
src/dxvk/dxvk_presenter.cpp
src/dxvk/dxvk_presenter.h

TL;DR there are situations where swapchain destruction will wait for the frame worker to drain the queue, but the frame worker might lock up in the frame latency tracker because something is calling `setLatencyMarkerNV` which in turn stalls until swapchain recreation finishes and keeps the latency tracker locked.
It's a mess, needs testing.

Fix possible presenter deadlock (hopefully)

---

src/dxvk/dxvk_graphics.cpp

Fixes the validation error in #4683, not sure if it also fixes the vertex explosions.

[dxvk] Don't create GPL pipeline if we need to patch the vertex shader

---

src/d3d9/d3d9_device.cpp

Fixes #4687
I hate bit masks.
The game has a mismatching texture type bug but I basically shifted the mask again, so we ended up unbinding the wrong texture slot.

[d3d9] Fix mismatching texture type mask updates

---

src/d3d9/d3d9_mem.cpp
src/d3d9/d3d9_mem.h

Hopefully fixes #4613
There was a race that could lead to freeing a chunk and allocating memory from it at the same time. This was extremely rare because D3D9 games usually don't make use of multi threading for rendering and just have a single rendering.
On top of that nearly all calls into any methods related to this are protected by the device lock anyway.
To fix this we just always route all operations through the general allocator which acquires its own lock before
calling the equivalent function inside the chunk.

[d3d9] Route operations on unmappable memory through allocator

---

src/d3d8/d3d8_device_child.h
src/d3d8/d3d8_options.cpp
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device_child.h
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_state.cpp
src/d3d9/d3d9_stateblock.cpp
src/d3d9/d3d9_swapchain.cpp
src/dxso/dxso_compiler.cpp
src/dxso/dxso_tables.cpp
src/dxso/dxso_tables.h

Closes #4615.
If there's a more optimal way to do it or you have any suggestions to improve the code, they're more than welcome. It's the first time I'm implementing anything of the sort in C++, so there might be some rough edges.
The second commit is an homage to @K0bin's early 2025 quote :stuck_out_tongue: :
> The rest of DXVK uses numeric_limits<uint32_t>::max() instead.
Needs a bit of testing, will undraft once that is done.

[d3d8/9] Prevent device child ref underruns on release

---

src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_context_ext.cpp
src/dxbc/dxbc_analysis.cpp
src/dxbc/dxbc_analysis.h
src/dxbc/dxbc_compiler.cpp
src/dxvk/dxvk_barrier.cpp
src/dxvk/dxvk_barrier.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_graphics.cpp
src/dxvk/dxvk_graphics.h
src/dxvk/dxvk_pipelayout.cpp
src/dxvk/dxvk_pipelayout.h
src/util/com/com_private_data.h

Based on #4691, which needs to land first.
TL;DR if a shader accesses a UAV only via one atomic operation (`add`, `and`, `or`, etc) and does not use the result, and if all prior accesses to the same UAV have used only the same operation, the result will be the same regardless of execution order, and we do not need to insert a barrier.
A small number of games hit this case in graphics shaders (Trine 4/5, Days Gone), some in compute (e.g. RE2 remake in D3D11 mode).
Also fixes a (more theoretical) bug with merged multidraw where we would incorrectly skip inserting barriers.

Optimize barriers around order-invariant atomic operations

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_shader.cpp
src/d3d9/d3d9_stateblock.cpp
src/d3d9/d3d9_util.h
src/dxso/dxso_compiler.cpp

Fixes #4703
The actual bug was an off-by-one bug but I also made it exclude the displacement map sampler in general.
We don't actually implement the displacement feature and I hope no game actually uses it but better safe than sorry.
The second commit tries to slightly clean up the sampler slot mess and make it more clear which functions take in a sampler slot counted the way the API does it and which one takes in a sampler slot counted the way we do it.
Hopefully that will make bugs like this one a bit less likely (but probably wont).

Stalker texture type fix

---

src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_context.h
src/d3d11/d3d11_context_ext.cpp
src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_context_imm.h
src/d3d11/d3d11_context_state.h
src/d3d11/d3d11_shader.cpp
src/d3d11/d3d11_shader.h
src/d3d11/d3d11_util.h
src/d3d11/d3d11_video.cpp
src/d3d11/d3d11_view_uav.h
src/dxbc/dxbc_analysis.cpp
src/dxbc/dxbc_analysis.h
src/dxbc/dxbc_common.cpp
src/dxbc/dxbc_common.h
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_module.cpp
src/dxbc/dxbc_module.h
src/dxbc/dxbc_util.h
src/util/util_bit.h

~~Based on #4693 because the DXBC bits would otherwise turn into rebase hell, so that needs to land first.~~ Merged.
TL;DR is that we defer forwarding resource bindings (`SetShaderResourceViews` and friends) to the backend if:
- None of the active shaders use the binding, or
- The app sets a null buffer/view/sampler.
These will instead be applied on the next draw or dispatch that are actually known to use the given binding.
The rationale here is that forwarding unused bindings can confuse the backend a little and lead to descriptor set invalidations even if none of the *actually used* bindings have changed. As for null bindings, these are very rarely actually used in shaders, and instead we can assume that the app will either bind a non-null resource right after or binds a shader which …

Lazy binding for D3D11

---

src/d3d11/d3d11_cmd.h
src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_context.h
src/d3d11/d3d11_video.cpp
src/d3d9/d3d9_device.cpp
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_context_state.h
src/dxvk/dxvk_cs.h
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_extensions.h
src/dxvk/dxvk_stats.h
src/dxvk/hud/dxvk_hud_item.cpp
src/dxvk/hud/dxvk_hud_item.h
src/vulkan/vulkan_loader.h
src/vulkan/vulkan_util.h

Because @DadSchoorse bullied me into it.
This uses `VK_EXT_multi_draw` to batch consecutive draws with no state changes, in much the same way we already batch consecutive *indirect* draws into a single indirect multidraw. Even if the extension *isn't* supported, this may slightly reduce CPU overhead because we're no longer redundantly checking dirty states all the time.
Games that see a notable reduction in draw calls include the Atelier series, Yakuza 0 / Kiwami, Nier Automata, Watch Dogs 2.
Based on #4699 to avoid rebase hell.

D3D11 Direct draw batching

---

src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_memory.cpp

Fixes potential memory allocation issues on unified memory setups that have unique memory types for different resources.

Fix memory type selection for non-device local property flags

---

src/dxvk/dxvk_device_filter.cpp

Closes #4121 and enables quick testing with `DXVK_FILTER_DEVICE_NAME="llvmpipe"`.

[dxvk] Don't skip CPU devices when a device filter is set

---

src/d3d11/d3d11_device.h
src/d3d11/d3d11_initializer.cpp
src/d3d11/d3d11_initializer.h
src/d3d11/d3d11_shader.cpp
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_compiler.h
src/dxbc/dxbc_module.cpp
src/dxbc/dxbc_module.h
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_shader.cpp
src/dxvk/dxvk_shader.h

Small rework, not overly scary. TL;DR:
- Skip vector components that are always zero to save some space; plenty of shaders only use a scalar or vec2 array.
- If we promote an icb to a uniform buffer, allocate it in non-mapped VRAM rather than HVV. HVV allocations can't be relocated by defragmentation, so having any sort of persistent allocation there is bad.
- If we keep the icb as a local array instead, bound-check any reads from it to avoid UB.

Rework D3D11 Immediate Constant Buffers

---

src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_compiler.h
src/dxvk/dxvk_graphics.cpp
src/dxvk/dxvk_shader.cpp
src/dxvk/dxvk_shader.h

Based on #4714 for now since both touch shader stuff.
Works around an issue in Clanfolk where the game would use a GS with `point` input topology when the pipeline uses triangles.
DCS World also hits this issue with its particle system, except there it's even more cursed and its GS uses `point` while tessellation outputs lines.
Needs some testing, especially in games that are known to do cursed Nvidia things (think Hairworks) since they really seem to love their geometry shaders.
See https://gitlab.freedesktop.org/mesa/mesa/-/issues/11853, https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/33533

Work around geometry shader topology mismatch

---

src/dxvk/dxvk_barrier.cpp
src/dxvk/dxvk_barrier.h
src/dxvk/dxvk_buffer.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_image.cpp
src/dxvk/dxvk_image.h
src/dxvk/dxvk_pipelayout.h
src/util/util_bit.h

Optimizes a bunch of barriers away when the app is doing back-to-back image copies/updates to the same subresource of an image. Since this uses morton codes to linearize texture coordinates, there **will** be false positives when copying unaligned image blocks around, but it improves a few common use cases.
This is a relatively common occurence when games stream in textures, either if virtual texturing is used (e.g. The Evil Within, this is one of the few games that constantly hit this case even during gameplay), or if a texture atlas is being created (seen that in Trine 5).
Also catches a few cases of 3D image updates in various Cryengine games, and some image->image copies in AC:Origins.
This probably won't drastically change performance anywhere, but it's a fairly trivial optmization …

Improve image hazard tracking granularity

---

src/dxso/dxso_compiler.h

Derp that thankfully seems to be harmless.

[dxso] Fix uninitialized m_maxDefinedConstant variable

---

src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h

TL;DR we have a buffer containing nothing but zeroes that is only used for image and buffer initialization, which can in some cases waste substantial amounts of memory, e.g. if we use it to initialize something like 16384x8192 BC1 texture, since the buffer needs to be large enough to hold one full subresource of the image.
If the device has good support for sparse binding, we can just create a sparse buffer that will implicitly read zeroes, and avoid having to allocate real memory for it.
This also moves all zero-initialization to the transfer queue so we may avoid eating graphics resources for no reason when the app creates a lot of resources back to back.
This **is** a scary change and will require a lot of testing across all sorts of different drivers, since accessing null tiles on a …

Rework zero buffer and resource initialization

---

src/util/config/config.cpp

The game checks for either ATi or nVidia vendor ID to enable real-time shadows, unfiltered for ATi and filtered for nVidia. Because of that there are no dynamic shadows on e.g. Intel. This PR fixes that. Maybe there are other effects locked behind a vendor check.
Only tested on Intel HD Graphics 630 (Mesa 24.3.4).

[util] Spoof vendor ID for CivCity: Rome

---

src/dxbc/dxbc_analysis.cpp
src/dxbc/dxbc_analysis.h
src/dxbc/dxbc_compiler.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_pipelayout.h

TL;DR RE2 has a pixel shader that simply writes `1` to a buffer for culling purposes and then does a bunch of back-to-back draws *without* enabling UAV overlap. This adds constant stores to the order-invariant access optimization to avoid over-synchronizing the GPU.

Consider constant stores as invariant

---

dxvk.conf
src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_interface.cpp
src/d3d8/d3d8_options.h
src/d3d8/d3d8_shader.cpp
src/d3d8/d3d8_shader.h
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_interface.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_surface.cpp
src/d3d9/d3d9_volume.cpp
src/dxvk/dxvk_state_cache.cpp
src/util/config/config.cpp

This adds validation capabilities to our d3d8->d3d9 shader translation logic and fixes a FVF normals component Wine test specific to d3d8. The test in question seems to suggest the validation is needed by 3DMark2001, but at least 3DMark2001 SE does not appear to hit it, so perhaps it was ultimately fixed? Regardless, the validation *is* in line with native behavior.
While I was at it, I also changed the shader creation logic a bit to not needlessly store partially created vertex shader objects if something should fail along the way.
Might look into a few more of the remaining tests, after which I'll test a bit and undraft.

[d3d8] Various D3D8 Wine device test fixes and other nits

---

dxvk.conf
src/d3d9/d3d9_include.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_swapchain.h
src/util/config/config.cpp

Fixes #3943
I made it a config option because modded Silent Hill 2 is the only game we've ever seen that actually needs the extra blit.

[d3d9] Keep front buffer around when we don't swap with it

---

src/dxvk/shaders/dxvk_present_frag_blit.frag

DXVK *generally* does not scale anything up or down because the app will use a swapchain that matches the display resolution, and in any sort of Proton environment we'll have fshack or gamescope dealing with non-native resolutions, however there are situations where the responsibility falls on us.
We already do the following:
- If the game's swapchain resolution matches the Vulkan swapchain, we just copy the source pixel, do whatever color space transforms are necessary (usually none) and move on.
- If the game's swapchain is multisampled, we do a manual resolve in linear space.
- If the game's swapchain is multisampled with `n` samples *and* requires scaling, we do some simple math on the coordinates to sample the closest `n` samples from a 2x2 pixel grid for each output pixel. This is …

Improve swapchain scaling

---

src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_compiler.h
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h

... or on broken drivers that just explode for no reason at all.

Do not export PointSize on maintenance5-enabled drivers

---

src/dxvk/dxvk_device.cpp

Clearly I am once again the proud owner of the **only** PC in the entire universe that doesn't run into any sort of GPU hang, rendering issue or whatever, so shipping this path doesn't seem viable and debugging it is kind of impossible right now until I find a way to actually reproduce anything on either RDNA2 or Nvidia.
Unfortunately this is going to turn the tiler optimizations into untested bitrot, but it's clearly broken anyway.

Don't use secondary command buffers on desktop drivers in general

---

src/d3d11/d3d11_context.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_format.h

Small cleanup, hence the negative delta. Also fixes an oversight where we accidentally broke partial resolves for certain D3D9 StretchRect cases.
Need to verify that this doesn't break anything else.

Rework depth-stencil resolves

---

src/d3d9/d3d9_constant_set.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h

Some small leftover from #4745
Basically moves everything we have for shader constants into one place. This is a little cleaner and allows us to get rid of some `VertexShader ? a : b` expressions (although they were always with a template).
The only exception are the actual shader constants because they live in the `D3D9State` struct which is shared between the device and state blocks.

[d3d9] Consolidate shader const related fields

---

src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_video.cpp
src/d3d9/d3d9_device.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_context_state.h
src/dxvk/dxvk_cs.h

Clamps scissors against the render area (which we should *technically* always have done, we have run into issues with out-of-bounds scissors and viewports in vkd3d-proton before), and refactors the D3D11 viewport/scissor update code to use CS chunk arrays.

Small viewport cleanup

---

src/wsi/win32/wsi_window_win32.cpp

EnumDisplaySettings(..., ENUM_CURRENT_SETTINGS, ...) is guaranteed to have DM_DISPLAYORIENTATION, DM_BITSPERPEL, DM_PELSWIDTH, DM_PELSHEIGHT, DM_DISPLAYFLAGS, DM_DISPLAYFREQUENCY, and DM_POSITION.
If we don't compare positions, then in Win32WsiDriver::restoreDisplayMode(), the original monitor layout might not be restored. For example, a secondary 1080p monitor at (3840, 0) can be moved to (1280, -1080) after the primary 4K monitor resolution changes to 720p and back to 4K. And due to the secondary monitor having the same resolution, its position won't be restored before this patch.
Fix Rime (493200) fails to switch monitors in borderless mode in some cases for Proton 10 alpha.
Related to #2064.

[wsi] Check more display mode flags when comparing them.

---

src/dxvk/dxvk_graphics.cpp
src/dxvk/dxvk_graphics.h
src/dxvk/dxvk_shader.cpp
src/dxvk/dxvk_shader.h

Essentially the DXVK equivalent of https://github.com/HansKristian-Work/vkd3d-proton/pull/2400, if TCS enables point mode then GS has to consume points, and if TES is the last active geometry stage then we'll actually be rasterizing points rather than triangles or lines.

Point-mode tessellation fixes

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_interface.cpp

Fixes some device type madness observed in #4766 , but probably not the main cause of concern in that issue.
Drafted until @Blisto91 helps validate the behavior/return codes against modern Windows, current implemented behavior is "the Windows XP way".
~P.S.: Also noticed Windows consistently reports 5 MB shy of 4096 MB when it comes to available texture memory by default, so let's do the same.~

[d3d8/9] Validate D3DDEVTYPE on device creation and cap queries

---

VP_DXVK_requirements.json
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_extensions.h
src/dxvk/dxvk_presenter.cpp
src/vulkan/vulkan_util.h

Third-party software like RTSS doesn't handle `_SRGB` formats properly, so always create swapchains with a plain `_UNORM` format and use `VK_KHR_swapchain_mutable_format` in order to keep the `_SRGB` format internally, which is necessary for the HUD and software cursor to be rendered correctly.
On the other hand, this change may regress SDR games on some HDR setups on Windows as well for the same reason.
This may also regress third-party software that isn't aware of swapchain create flags or `pNext` chains.

Don't use sRGB swapchain formats

---

src/dxvk/dxvk_device.cpp

This was disabled in 2.6 due to driver bugs, would need to test this on more hardware before re-enabling is viable.
On desktop, this only affects render passes that use MSAA, and helps with redundant resolves and reduces barrier spam somewhat.

Re-enable secondary command buffer usage

---

src/d3d11/d3d11_context_def.cpp
src/d3d11/d3d11_context_imm.cpp
src/d3d11/d3d11_initializer.cpp
src/d3d11/d3d11_swapchain.cpp
src/d3d9/d3d9_initializer.cpp
src/d3d9/d3d9_swapchain.cpp
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h

And instead do some magic to clear backing storage for resources directly as much as humanly possible.
There will still be cases when a zero buffer is required, but that should be extremely rare now and largely be limited to systems without `maintenance5` support.
The sparse thing is just broken on too many drivers.

Don't use sparse zero buffer

---

src/util/config/config.cpp

Regresses GPU-bound performance, but considerably reduces FPS drops in areas where draw call counts are high.
Not sure which one is worse tbh, I hate when games make it literally impossible to get good perf all the time.

[util] Enable cached constant buffers for Hitman 2

---

src/util/config/config.cpp

I didn't make an API trace to investigate the game, I just randomly tried the option and saw the improvements. The Extras menu in particular has a 10000% performance improvement.
The game is downloaded from Amazon/Twitch Prime (Heroic).
Gameplay
Pause menu > Extras
Gameplay
Pause menu > Extras
I kinda wonder if this is the only game that has this problem, since there are *many* games using the same engine: https://www.pcgamingwiki.com/wiki/Engine:Nu2 [^1]
I do have other LEGO games that I can test later, though.
[^1]: Ordering by release date, the first game supporting D3D11 is Lego Batman 3 (2014!), while the first to drop D3D9 support was Lego City Undercover (2017!?).

[util] Enable cachedDynamicBuffers for Lego Indiana Jones: The Original Adventures

---

src/d3d11/d3d11_blend.cpp
src/d3d11/d3d11_blend.h
src/d3d11/d3d11_context.cpp
src/d3d11/d3d11_context.h
src/d3d11/d3d11_depth_stencil.cpp
src/d3d11/d3d11_depth_stencil.h
src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_input_layout.cpp
src/d3d11/d3d11_input_layout.h
src/d3d11/d3d11_rasterizer.cpp
src/d3d11/d3d11_rasterizer.h
src/d3d11/d3d11_video.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_util.cpp
src/dxvk/dxvk_constant_state.cpp
src/dxvk/dxvk_constant_state.h
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_graphics_state.h
src/dxvk/meson.build

Compresses some render state structures in a similar way to what the pipeline state thing already does, and changes all the D3D11 state binding methods to pass a copy of the full state rather than ref-counting the D3D11 state object itself. This is now much more feasible when things like depth-stencil state are now 10 bytes rather than 72.
Additionally, this normalizes depth-stencil and blend state to the extent possible in the frontends. The backend already does this to an extent at pipeline compile time, but sanitizing some state can be useful to not create extra pipeline states in the first place. 
This also benefits #4785 since we can now more easily prove that e.g. stencil isn't written, and also changes blend states that essentially disable writing to a given render target to use a …

Refactor and normalize render state

---

VP_DXVK_requirements.json
src/d3d11/d3d11_context.cpp
src/d3d9/d3d9_device.cpp
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_context_state.h
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_extensions.h
src/dxvk/dxvk_framebuffer.h
src/dxvk/dxvk_graphics.cpp
src/dxvk/dxvk_graphics.h

Another small tiler optimization: If a render target or depth buffer is used in two back-to-back render passes and gets cleared before the second pass, we can set `STORE_OP_DONT_CARE` for that render target in the first pass, provided that that pass is rendered using secondary command buffers.
This is actually quite common in D3D9 land since many games reuse the default depth buffer for all sorts of things.
Additionally, we can use `LOAD_OP_NONE` for unused attachments, and `STORE_OP_NONE` for unused or read-only attachments.

Use STORE_OP_DONT_CARE/NONE whenever possible

---

src/d3d11/d3d11_input_layout.cpp
src/d3d11/d3d11_input_layout.h

[d3d11] Don't use bcmpeq to compare input layouts

---

src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h

Lego Movie 2 has a number of render passes where it draws a fullscreen triangle without any sort of depth or stencil test and *then* clears stencil. We can make this pattern more tiler-friendly by hoisting that clear into the render pass itself and avoid a useless `LOAD_OP_LOAD`.
I also expect this to be common in D3D9 land.

Clear unused attachments early

---

src/util/util_bit.h

Now MSVC will always use BSR for LZCNT.
Also correct 0 input behavior for TZCNT when fallback to BSF.
Should fix #4808 .
Need test before merge.

[util] Fix broken LZCNT&TZCNT on non-BMI platforms

---

src/wsi/sdl3/wsi_platform_sdl3.h

In SDL3 it's possible for the platform to refuse returning a good refresh rate, so we have to try as many options as we can. Numerator/Denominator is best, but sometimes we just get a float, and sometimes we don't even get that (I managed to repro this via Xwayland).
This ensures that if the WsiRational is ever invalid, it's almost certainly SDL's fault rather than dxvk's.

[wsi] Handle SDL3 refresh rate not being available

---

meson.build
meson_options.txt

* [build] Remove unused option dxvk_native_wsi
Before support for dynamic WSI selection was added, this option selected
the single supported WSI. Now it no longer does anything.
Fixes: d5d236a1 "[wsi] Refactor platform system to support multiple WSI implementations"
* [build] Add options for the various DXVK Native WSIs
Previously, each of these was enabled automatically if its corresponding
development files was installed, or disabled if they were not (an
"automagic dependency"). For example, when building in the Steam Runtime
SDK, which always includes SDL, there would be no way to turn off the
SDL2 WSI if it is not desired.
For predictable, reproducible builds, OS distributions generally prefer
to be able to explicitly enable or disable features. Using build options
of type `feature` …

[build] Add options for the various DXVK Native WSIs

---

src/util/config/config.cpp

See comment here <https://github.com/ValveSoftware/Proton/issues/164#issuecomment-2800918030>
Verified that Prototype 1 does not allow setting AA to 4x when i sees a high amount of vram. Even though the game is d3d9 it queries it through dxgi.
I could not reproduce the same for the second game which list AA values NONE, LOW and HIGH the same with and without a limit.
Also a minor cleanup for some stuff missed prior.

[util] Limit vram reported for Prototype and minor cleanup

---

src/util/sync/sync_spinlock.h
src/util/util_bit.h

* [util] Fall back to busy-loop on spinlock for unknown CPU architectures
If there's no known equivalent of _mm_pause() on an architecture,
it seems to be most typical to fall back to not doing anything,
resulting in busy-looping for a short time. Porters who don't like this
behaviour can add an `#elif` here with their architecture's closest
equivalent, if it has one.
* [util] Don't error out for otherwise unknown CPU architectures
All of the conditionally-compiled parts seem to have a `#else` that is
ordinary non-architecture-specific C++, except for the spinlock that
was made generic in the previous commit, so there's no particular reason
to forbid compiling for other CPUs.
---
The bug report that I believe this resolves:
Debian unstable currently has builds of DXVK as PE DLLs (only) …

Don't error out for otherwise unknown CPU architectures

---

src/d3d11/d3d11_video.cpp
src/d3d11/d3d11_video.h
src/d3d11/shaders/d3d11_video_blit_frag.frag

This aims to support the game JR East Train Simulator, which uses the video processor with input and output streams both in the NV12 format.
Vulkan does not (usually?) support rendering to a G8_B8R8_2PLANE_420_UNORM (=NV12) view (it lacks the COLOR_ATTACHMENT_BIT in features - tho I've only checked on a modern AMD gpu).
Two passes are necessary since the Y and CbCr views may have different dimensions (in the case of NV12, CbCr is half the size of the Y view).
Since the creation of the output view now significantly overlaps with the input view's code (both have to iterate over the aspectMask to create views), I've introduced a superclass `VideoProcessorView` to share the behavior.
In case of planar output, the output view still creates a view in its "native" format, to support being …

[d3d11] Support planar outputs in video processor

---

dxvk.conf
src/d3d11/d3d11_options.cpp
src/d3d11/d3d11_options.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h
src/dxso/dxso_compiler.cpp
src/dxso/dxso_options.cpp
src/dxso/dxso_options.h
src/spirv/spirv_module.cpp
src/spirv/spirv_module.h
src/util/util_math.h

Intel's `sin(x)` is **very** inaccurate for `|x| ≈ π/2`, which leads to issues such as #4861.
This is an attempt to work around the problem by implementing a custom sin/cos implementation using a Taylor approximation within a range of `[-π/4,π/4]`, and doing some magic to map the rest of the curve to that interval. Precision is good enough to meet D3D11 requirements and should fix Thumper, but this is expected to be quite slow.
On systems with good sin/cos, keep using the corresponding SPIR-V instructions.
Needs testing across a reasonably wide range of games including D3D11, this changes code gen in *all* shaders that use `sincos` instructions even if the workaround is not used.

Implement custom sin/cos approximation

---

dxvk.conf
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_query.cpp
src/dxgi/dxgi_adapter.cpp
src/util/config/config.cpp

Closes #4860 and goes a bit beyond that to:
- clean up some vendorid jank in d3d9 code (now we determine what we're using in a single place)
- report all non-Intel, non-Nvidia and Non-AMD GPUs as AMD in d3d8/9 (this affects mobile GPU vendors) - I have not hidden this under a,  say, `d3d9.hideGenericGpu` config option, but I can do that if anyone thinks it's worthwhile.
Needs quite a bit of testing on Intel, AMD and mobile, as I was only able to confirm the new `d3d9.hideNvidiaGpu` option works as expected.
~We could also potentially rework some of the existing config options now, but I haven't really looked into any of that yet.~ ~Mostly done now, save for Warhammer, which I'm sure sure what is about.~ Done deal.

[d3d9] Implement hideVendorGPU logic for d3d9

---

src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_image.h

Allows us to merge resolves into render passes more often.

Use barrier tracking for inline resolve attachments

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_state.h

Might as well "un-stub" these, as it's fairly straight-forward, based on: https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-setclipstatus
There's two claims I've written a test for and have proved to be false:
- When D3DRS_CLIPPING is set to FALSE, ClipUnion and ClipIntersection are set to zero. (they are not set to 0, rather retain whatever values they have even after a draw call)
- Clip status is used during software vertex processing. Therefore, this method is not supported on pure or nonpure hardware processing devices. (Set/GetClipStatus return D3D_OK on all type of HWVP/Mixed/SWVP devices, but the clip status is most likely not updated & ignored outside of SWVP, I guess)
As for the actual implementation, I'm still not sure what the clip status is …

[d3d9] Implement Get/SetClipStatus

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_monitor.cpp
src/d3d9/d3d9_monitor.h

On a tangent, also noticed all vendors seem to report the following adapter/backbuffer format support:
```
Device back buffer format support (full screen):
+ The D3DFMT_A8R8G8B8 format is supported, device creation SUCCEEDED
+ The D3DFMT_X8R8G8B8 format is supported, device creation SUCCEEDED
+ The D3DFMT_R5G6B5 format is supported, device creation SUCCEEDED
- The D3DFMT_X1R5G5B5 format is not supported
- The D3DFMT_A1R5G5B5 format is not supported
+ The D3DFMT_A2R10G10B10 format is supported, device creation SUCCEEDED
Device back buffer format support (windowed):
+ The D3DFMT_A8R8G8B8 format is supported, device creation SUCCEEDED
+ The D3DFMT_X8R8G8B8 format is supported, device creation SUCCEEDED
+ The D3DFMT_R5G6B5 format is supported, device creation SUCCEEDED
+ The D3DFMT_X1R5G5B5 …
```

[d3d9] Properly report supported adapter/backbuffer formats

---

src/d3d11/d3d11_video.cpp
src/d3d11/d3d11_video.h

[d3d11] Fix planar video output when dst rect is enabled

---

src/d3d8/d3d8_device.cpp

Closes #4917 by extending the same "log only once" logic to the currently unimplemented d3d8-specific render states.

[d3d8] Only log unimplemented RS use once

---

src/util/config/config.cpp

Prevents the game from blinking, freezing, crashing or going windowed mode when you alt-tab.

[util] Add configs for alt-tabbing in Red Orchestra: Ostfront

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h

In addition to gating vendor hacks behind their proper vendorIds, we should also properly report support for said hacks in `CheckDeviceFormat`, as querying for support is the first step in any guide that describes these hacks. I definitely think exposing some of these on all the vendors is asking for trouble, especially considering how poorly some d3d9 games actually behave when faced with unexpected support for certain features.
Also took the liberty to cache device specific identifier data in the adapter, since it won't change during its lifetime and some queries can get spammed both internally and by external calls. I'm also getting the (cached) vendorId for the device from the adapter now.
~~D3D8 doesn't seem to expose *any* vendor hacks (the entire madness probably came into being a …

[d3d9] Properly determine support for vendor hacks

---

VP_DXVK_requirements.json
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_extensions.h
src/vulkan/vulkan_loader.h

Instead of erroring out. Bit of an oversight from maintenance5 enablement.
Should be fairly non-controversial since it's optional anyway.

Optionally enable maintenance6 for null index buffer

---

dxvk.conf
src/dxbc/dxbc_compiler.cpp
src/dxbc/dxbc_options.cpp
src/dxbc/dxbc_options.h
src/dxvk/dxvk_adapter.cpp
src/dxvk/dxvk_cmdlist.cpp
src/dxvk/dxvk_descriptor_heap.h
src/dxvk/dxvk_device.h
src/dxvk/dxvk_pipelayout.cpp
src/dxvk/dxvk_pipelayout.h
src/dxvk/dxvk_sampler.cpp
src/dxvk/dxvk_sampler.h
src/dxvk/dxvk_util.h

To address some fallout from the descriptor buffer merge:
- Disable on ANV due to random perf loss
- Disable NV_raw_access_chains for byte address buffers to work around a hang
- Use smaller sampler set to fix NV performance with both binding models
- Couple of (largely cosmetic) changes to separate descriptor buffer-specific stuff from legacy model stuff

Post-descriptor buffer cleanup

---

src/dxbc/dxbc_compiler.cpp

Small optimization that changes all typed UAVs with atomic instructions to raw SSBOs, which works because atomic stuff only works on R32 anyway.

[dxbc] Promote typed UAV to SSBO if accessed atomically

---

src/util/config/config.cpp

The game locks certain "FX" generation features behind certain deviceIds. I'd have gone with an ATI 9700, but it seemed to disable terrain lighting on that, so a GeForce FX 5900 Ultra it is. I've extracted the most performant deviceId from the game's own GPU list.
Technically one could add their own deviceId to that list manually, but I think it's worthwhile to spare end users the pain.

[util] Add a deviceId spoof for Battle Engine Aquila

---

src/dxvk/dxvk_instance.cpp

Turns out we have 32 bit OpenVR spectacularly double broken in Proton now. One problem was introduced recently in Proton's vrclient (right now fixed in Proton Experimental [bleeding-edge] only, another is from recent dxvk commit 1ef2801d41c64629198e1d4626068842e3f0d6e9 .
The problem is that initDeviceExtensions for OpenVR provider depends on the adapters array being initialized, without that it can't get adapter ids and doesn't query any extensions.
That happens to work on 64 bit because of OpenXR initialization which effectively delivers the same set of native Vulkan extensions and initDeviceExtensions for OpenXR provider doesn't use dxvk adapters. But 32 bit wineopenxr is non-existent and the problem becomes apparent with 32 bit OpenVR / d3d11 games.

[dxvk] Call providers' initDeviceExtensions with initialized adapters

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h

Should speed up `SetRenderState` calls where state changes by a bit. I don't expect anything dramatic, but that being said `SetRenderState` is a *very* hot path, albeit not that heavy, and these things do tend to add up.

[d3d9] Improve SetRenderState state tracking

---

src/d3d9/d3d9_device.cpp
src/dxvk/dxvk_context.cpp

Doesn't fi.x #4769 but still has some good stuff.
The backend commit should probably be backported to the v2.6.x branch.
I'll do that after the merge.

Fix OSU crash due to null pointer in the backend

---

src/d3d9/d3d9_device.cpp

[d3d9] Don't unbind buffers on Ex device

---

src/d3d9/d3d9_device.cpp

Silences logging spam in some games that set the vendor hack RS frequently, namely:
COPM:
- BioShock 2
- Mirror's Edge
SSAA:
- S.W.I.N.E HD Remaster

[d3d9] Only show unsupported vendor hack warnings once

---

dxvk.conf
src/d3d8/d3d8_interface.h
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/dxgi/dxgi_options.cpp
src/dxgi/dxgi_options.h
src/dxgi/dxgi_output.cpp
src/dxgi/dxgi_output.h

Closes #4421, although it's not directly meant to enable people into forcing higher refresh rates, it can be used for that too.
It's more useful to fix situations where stubborn games force the lowest refresh rate available, by limiting the listed modes to only a single refresh rate. Drafted until I've tested it a bit more.
P.S.: I've kept it in line with how the forceAspectRatio option behaves, but we can potentially make this a bit more clever (to support stuff like "max" as well), though hhhhnnnggggg, it certainly has the potential to explode on certain setups, I think.

[d3d9/dxgi] Add a force refresh rate config option

---

src/d3d9/d3d9_hud.cpp
src/d3d9/d3d9_hud.h
src/d3d9/d3d9_swapchain.cpp
src/dxvk/dxvk_sampler.cpp
src/dxvk/dxvk_sampler.h

Doesn't functionally change *much* besides fixing an old bug, but with the way the sampler heap works, there's no reason to artificially limit sampler count any further, so this changes the LRU list to simultaneously serve as a free list. We really only need to start recycling samplers once the heap is completely full.

Sampler simplification

---

src/util/config/config.cpp

A.I.M.: Artificial Intelligence Machine uses an external configuration window which is opened once the (d3d8) main menu option is selected. The added config option prevents a black screen on return to the main menu from the options window or simply by alt-tabbing back and forth in-game.

[util] Fix black screen on return from the A.I.M. options window

---

src/dxvk/dxvk_device_info.cpp

Usage of `copyFeature` is inconsistent in `initSupportedFeatures` when `deviceInfo` is provided. This happens in D3D11on12 scenarios where the device is reused. `copyFeature`'s signature is `const void*` not `const void**` as the ref to `deviceInfo->pNext` suggests. The first `copyFeature` succeeds because the usage is correct. The `CORE_VERSIONS` define crashes immediately.
Found testing on Windows with the  https://github.com/microsoft/directx-graphics-samples/tree/master/Samples/Desktop/D3D12VariableRateShading sample. It uses D3D11on12 and crashes in the `D3D11On12CreateDevice` call.

Fix usage of copyFeature

---

src/util/config/config.cpp

Otherwise any graphical change gets you this lovely thing:

[util] Don't count losable resources for Astebreed

---

src/d3d9/d3d9_caps.h
src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_subresource.h
src/d3d9/d3d9_swapchain.cpp

Bind all RTs unless we need to skip them to resolve a hazard or avoid restricting the render area.
The rewritten `BindFramebuffer`-code is based on #4973.
Binding a texture for sampling, binding a render target, changing the shader or changing a color write mask calls
`UpdateActiveHazardsRT` with a masks for the changed textures/rts. This function then scans for hazards and checks if those can be resolved by unbinding the render target. If that's possible, the  bit in `unboundHazardRT` is set and the `DirtyFramebuffer` bit is set. `unboundHazardRT` will then get checked when rebinding the render targets.
If its not possible to resolve the hazard by unbinding. the bit in `hazardRT` is set which makes DXVK transition the RT to LAYOUT_FEEDBACK_LOOP at draw time just like before.
Fixes #4900

[d3d9] Rework render target binding logic

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_meta_blit.cpp
src/dxvk/dxvk_meta_blit.h
src/dxvk/meson.build
src/dxvk/shaders/dxvk_blit_frag_2d_ms.frag

Improves #4895 when using MSAA in Source.
HL2 frequently resolves a 2048x1536 screenshot into a 1024x1024 image which is then used for refraction when rendering glass.
The game does these resolves (using StretchRect) quite frequently and unfortunately a lot of them are redundant.
Current DXVK master would first resolve the original texture to a temporary image and then blit that to the actual target texture.
While that's actually what the D3D9 docs suggest happens behind the scenes, it's a bit slow:
> Note that use of the extra surface involved in using StretchRect to downsample a Multisample Rendertarget will result in a performance hit.
This PR changes it so the blit and resolve are done in one step rather than in two. It improves performance in the HL2 main menu at 4k Max settings with …

[d3d9] Optimize StretchRect stretching resolves

---

src/util/util_bit.h

@WinterSnowfall made the good point that we should at least give users a warning when using unsupported build flags.
AVX is a no-no because it GCC will generate code that requires 32-byte stack alignment, but we're never going to get more than 16 (or 4 on 32-bit builds). Native builds and MSVC *should* be unaffected, but it's not tested.

[dxvk] Error out at build time if AVX is enabled

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_format.h
src/d3d8/d3d8_interface.h
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_bridge.cpp
src/d3d9/d3d9_bridge.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h

Clean up mostly of d3d8 format support on `CheckDeviceFormat` and `CreateImageSurface`, which addresses the following corner cases:
- d3d8 `CheckDeviceFormat` shouldn't report support for d3d9-exclusive formats
- `CreateImageSurface` should work even with unsupported formats, including lockable depth formats ~(to be confirmed on native)~, similarly to how `CreateOffscreenPlainSurface` with `D3DPOOL_SCRATCH` behaves in d3d9
- volume textures can't be used as render targets, yet we were advertising support (fixed)... some native drivers seem to do that too for some reason, although creation will fail on them as well
- `W11V11U10` is not available in d3d9, so should not be advertised outside of d3d8 (this brings us in line with native and WineD3D)
- `A2B10G10R10_XR_BIAS` does not appear to …

[d3d8/9] Clean up CheckDeviceFormat and CreateImageSurface formats

---

src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h

Silences "ConvertFormat: Unknown format encountered:" log spam in some games that like to call `CheckDeviceFormat` a lot... even during rendering (don't ask). The warnings are a bit pointless for these formats anyway, since we know that they exist and are unsupported.
WineD3D, for some reason, allows OffscreenPlainSurface creation for `AL16` and `R16`, but I've checked both mordern and olden drivers and haven't found any indication that support was a thing even back in the day, in either d3d8 or 9, at least not on mid-2000s/Windows XP timescales. My suspicion is that perhaps at least some of these are remnants from even earlier d3d times, from the land of Mord... I mean ddraw, where the shadows lie.

[d3d9] Add more known unsupported formats

---

src/d3d9/d3d9_adapter.cpp

Drafted, until I write some tests to check if that's actually true in d3d8/9 as well, since the game is using 9Ex. But the below does fix crashing when attempting to start a game in Wargame: European Escalation.
Confirmed with an apitrace the game checks:
`IDirect3D9Ex::CheckDeviceMultiSampleType(this = 0x2e3cbf0, Adapter = D3DADAPTER_DEFAULT, DeviceType = D3DDEVTYPE_HAL, SurfaceFormat = D3DFMT_NULL, Windowed = FALSE, MultiSampleType = D3DMULTISAMPLE_NONE, pQualityLevels = ?) = D3DERR_NOTAVAILABLE`
... and crashes if the above call fails.

[d3d9] Fix NULL format CheckDeviceMultiSampleType behavior

---

src/d3d11/d3d11_swapchain.cpp
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_interface.cpp
src/d3d9/d3d9_interface.h
src/d3d9/d3d9_main.cpp
src/d3d9/d3d9_swapchain.cpp

Only relevant if the game actually creates a D3D9 or D3D11 swap chain rather than a D3D12 one, but A Hat In Time does just that:

Display whether device is 11on12 or 9on12 device in HUD

---

src/dxgi/dxgi_factory.cpp
src/dxgi/dxgi_swapchain.cpp

Band-aid for #5053 for now, Present as well as ResizeBuffers should just work.
At some point, we should probably test how the other methods behave since things like ResizeTarget don't seem to make much sense in the context of dcomp.
Not ideal to have a dummy window, but this should at least work with d3d12 as-is.

Dcomp swapchain

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp

In current master, we use `LAYOUT_DEPTH_READONLY` views every time writing the depth buffer is disabled. This causes unnecessary layout transitions. It also doesn't really have any advantages because we never use this layout when also sampling the depth buffer.
The PR changes it so we always use the read-write layout unless the depth texture is also bound for sampling and depth write is disabled. I'm not sure if the extra complexity is worth it compared to just resorting to FEEDBACK_LOOP_LAYOUT when the depth texture is bound for depth testing and sampling. Let me know, what you think.
Either way, not using DEPTH_READONLY for depth attachments significantly reduces the number of render passes in Half Life 2. One random hallway in one of my apitraces goes from 17 render passes down to just …

[d3d9] Only use readonly depth layout if necessary

---

src/dxgi/dxgi_adapter.cpp
src/dxgi/dxgi_adapter.h
src/dxgi/dxgi_factory.cpp
src/dxgi/dxgi_factory.h
src/dxgi/dxgi_output.cpp
src/dxgi/dxgi_output.h

Adds `ID3DDestructionNotifier` support to:
* `DxgiAdapter`
* `DxgiFactory`
* `DxgiOutput`
A quick test on Windows reveals that these objects support `ID3DDestructionNotifier`. It seems that anything with private data support also has `ID3DDestructionNotifier` support, so maybe it'd make sense to move all of this into `DxgiObject` instead.

Add missing ID3DDestructionNotifier support in DXGI

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format.h

There's a d3d9Ex wine test that suggests `CreateOffscreenPlainSurface` behaves in a similar way to `CreateTexture` when D3DPOOL_SYSTEMMEM is used along with `pSharedHandle` (calls won't fail, but will rather set the initial data based on `pSharedHandle`).
I've also fixed other `pSharedHandle` and pool validations that the tests expected (along with some... odd choice of return codes).
Now that this particular test is (mostly) fixed, the entire d3d9ex suite of wine tests (part of d3d9) can be run to its end and currently stands at:
`2960 tests executed (51 marked as todo, 4 as flaky, 176 failures), 1 skipped.`

[d3d9] Shared resource fixes (based on d3d9ex wine tests)

---

src/util/config/config.cpp

For consistency, we should always report an Nvidia vendorId for the game, since shadow buffers and the perspective divide were very much hardware specific. Also, game physics is broken in various degrees above 60 fps, with one level being unpassable without a hard cap.

[util] Splinter Cell config option tweaks

---

src/util/config/config.cpp

Otherwise the games config tool will complain about vram unless we restrict it and also wont allow up to 1080p if set too high. Also helps CPU performance.

[util] Add configs for GTR - FIA GT Racing Game

---

src/d3d8/d3d8_batch.h
src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_device.h
src/d3d8/d3d8_format.h
src/d3d8/d3d8_shader.cpp
src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_format.cpp
src/d3d9/d3d9_format.h
src/d3d9/d3d9_mem.cpp
src/d3d9/d3d9_mem.h
src/d3d9/d3d9_names.cpp
src/d3d9/d3d9_names.h
src/d3d9/d3d9_swapchain.cpp
src/d3d9/d3d9_util.cpp
src/d3d9/d3d9_util.h

The initial idea was to get rid of some now dead d3d8 code (some leftovers from the initial batcher implementation, I guess) and consolidate things a bit, but I happened to spot some misplaced d3d9 format helpers too while at it.

[d3d8/9] General and format helpers cleanup

---

src/d3d9/d3d9_device.cpp

Should fix #5080. @Blisto91 would appreciate it if you can confirm this when you get the time.
Wrote a test and it looks like the restriction only applies to D3DPOOL_DEFAULT resources. Turok (2008) was trying to lock some D3DPOOL_SYSTEMMEM textures and that was causing issues.

[d3d9] Only fail on DISCARD|READONLY locks of D3DPOOL_DEFAULT resources

---

src/util/config/config.cpp

In dxvk 2.6.2 and 2.7 changes were made so we only expose support for various bits and pieces as they are also supported in the vendors native d3d9 drivers. 
Prior to those two releases the game used its AMD rendering path on Nvidia, which worked without visual issue. Now that the game can correctly select the Nvidia path we've discovered it depends on `NvAPI_D3D9_StretchRectEx` being implemented. Without it visual effects effects such as blood splatters will appear buggy. 
It was decided that it was much simpler to revert the game back to its AMD path rather than going through with implementing the above function fully.
Edit: I was mixing issues together. This does not need a backport to v2.6.x as it only affects 2.7
Edit 2: No i am dumb. It does need a backport

[util] Enable d3d9.hideNvidiaGpu for Perilous Warp

---

src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_meta_blit.cpp
src/dxvk/dxvk_meta_blit.h
src/dxvk/shaders/dxvk_blit_frag_2d_ms.frag

Fixes #5107, #5074. Needs some testing that it doesn't regress Source Engine again.
TLDR if there is no stretching happening, just do a normal shader-based resolve. WoW hits the blit path here for... some reason (presumably view swizzles), but this also allows the resolve to work properly in scenarios where the regular resolve functions wouldn't work, e.g. if the image gets mirrored at the same time.

[dxvk] Support average resolve in blit shader

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_swapchain.cpp
src/util/config/config.cpp

Noticed a distinct difference between dxvk and native d3d9 when looking at several traces, namely `GetAvailableTextureMem()` consistently reports lower numbers on native (this is for newly created devices). The exact delta varies between 2 MB and 8 MB depending on chosen resolution, so I can only assume it's memory reserved for back buffer use or other internal (Windows) purposes.
This PR might help us get rid of the caps for some games currently using a 2048 limit, but that needs further testing.
Other than that, I've taken the liberty to attempt a somewhat (more) consistent formatting/alignment of the config.cpp profiles. The only actual change in there besides formatting/alignment is that I've bumped the memory limit for NFS4 to 1024 MB, to account for potential modding, since the game …

[d3d8/9] Assorted fixes and nits

---

dxvk.conf
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_adapter.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/util/config/config.cpp

I've resurrected this, because the problem with the AquaNox games has come back to bite me even on my most recent Lunar Lake laptop. It seems that laptops in general (their screens in particular) simply expose too many modes for some games to be happy.
That can usually manifest as:
- higher resolutions are missing from in-game mode selection options
- lower resolutions get cut, which sometimes breaks the first-run configurations of games
- games overflow in their mode count logic and crash or refuse to start
There's always the option of coming up with an allow list of resolutions, similarly to how certain drivers apparently reduce excessive mode counts, but I'd rather have something user configurable, as we can't possibly account for all preferences and hardware combinations.
Edit: …

[d3d9] Add a modeCountCompatibility config option

---

src/d3d11/d3d11_device.cpp
src/d3d11/d3d11_video.cpp

Overcooked: All You Can Eat spams pretty much all of D3D11's video API (as observed in #5081), except the DRM/crypto stuff, so I've silenced most of the calls to prevent excessive log spam. The game works fine save for video, in any case, so none of it warrants the "error" status, thus I've also lowered the logging to "warning".
I've also subbed `GetVideoDecoderConfigCount` a bit more, to return 0, hopefully it might make it clear to some apps they shouldn't spam unsupported things like mad.

[d3d11] Slience video related log spam in Overcooked AYCE

---

src/d3d9/d3d9_common_texture.cpp
src/d3d9/d3d9_common_texture.h
src/d3d9/d3d9_device.cpp

Part 1 of what was originally #5092.
The validation changes are fairly straightforward.
It's particularly about the USAGE flags in the CreateXYZSurfaceEx functions that 9Ex added.
Thankfully they simply reject almost all usage flags instead of magically turning an offscreen surface
into a render target.
Besides that, it cleans up the actual image creation.
For example offscreen surfaces always got VK_IMAGE_USAGE_COLOR_ATTACHMENT
because they can be used with D3D9Device::ColorFill. That function however
uses DxvkContext::ensureImageCompatibility anyway and it's not super commonly
used with plain offscreen surfaces.

[d3d9] Texture creation cleanup + missing D3D9Ex texture creation validations

---

src/util/config/config.cpp

Prevents Geralts hair from "exploding" in the inventory at very high fps

[util] Cap Witcher 1 at 300 fps

---

src/d3d9/d3d9_interfaces.h
src/d3d9/d3d9_interop.cpp

If you call `GetVulkanImageInfo` on a texture that does not have a `DxvkImage`, then DXVK will immediately segfault. This usually happens for `NULL` format textures and textures in `SYSMEM` or `SCRATCH`, but all the specific cases are opaque to the user. This PR fixes that by making it fail gracefully and return `D3DERR_NOTFOUND`.

[d3d9] Fix crash in GetVulkanImageInfo for SYSMEM or NULL textures

---

src/d3d9/d3d9_device.cpp

Fixes the use of the option with #5172 (so it seems that _was_ actually a bug of sorts), and I'm assuming also fixes #2400 (the issue mentioned in it).
@K0bin please review, ~~I'm not entirely sure if I'm piping in things properly here, though the principle seems sound~~ (nevermind, after looking at it in more detail, pretty sure the piping is a good as it can get).
I've checked that other games where the option is useful (e.g. Mafia) still work properly in terms of the intended effect.

[d3d9] Override sampler anisotropy only on multi-mip textures

---

src/util/config/config.cpp

Cursor animations are the most visibly affected, since they play back too fast to even notice at times, but other minor map animations are tied to the framerate as well, looks like.
The executable sits in a `Data` folder on the GOG version, but doesn't appear to on Steam, so I've catered to both situations.

[util] Add a frame cap for HoAE

---

src/util/config/config.cpp

Backport of #5188 for v2.6.x branch.

v.2.6.x Backport: [util] Enable dummy composition for Anno 117

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_fixed_function.h
src/d3d9/d3d9_spec_constants.h
src/dxso/dxso_compiler.cpp
src/dxso/dxso_options.cpp
src/dxso/dxso_options.h
src/dxso/dxso_util.cpp

DXVK uses a global hashmap that assigns an index to a semantic (Usage + Index). To make the programmable + fixed function combination work, we prepopulate that with the semantics that fixed function actually exports.
Besides that, programmable shaders with shader model <3 also emit all outputs that fixed function fragment shaders might use. This is to avoid requiring shader patching for missing outputs in the backend (and thus breaking GPL) when combining programmable VS + FF ubershader FS.
Current master has a bunch of spec constants that are used by SM1 shaders for which we generate different SPIR-V shaders when it comes to fixed function.
We need those spec constants for the ubershaders anyway so the PR also changes the generated FF SPIR-V shaders to use the spec constants instead. …

[d3d9] Preparation for the FF Ubershader

---

src/d3d9/d3d9_device.cpp
src/d3d9/d3d9_device.h
src/d3d9/d3d9_fixed_function.cpp
src/d3d9/d3d9_fixed_function.h
src/d3d9/d3d9_options.cpp
src/d3d9/d3d9_options.h
src/d3d9/d3d9_spec_constants.h
src/d3d9/d3d9_state.h
src/d3d9/meson.build
src/d3d9/shaders/d3d9_fixed_function_common.glsl
src/d3d9/shaders/d3d9_fixed_function_frag.frag
src/d3d9/shaders/d3d9_fixed_function_vert.vert
src/dxvk/dxvk_shader_spirv.cpp
src/dxvk/dxvk_shader_spirv.h

This creates a single shader that handles the D3D9 fixed function vertex stage and another one that handles the fixed function pixel stage.
This initial PR keeps the old FF code generator around. The ubershaders are enabled by default but can be disabled using `d3d9.ffUbershaderVS=False` and `d3d9.ffUbershaderFS=False` respectively.
The long term plan is to get rid of the FF code generator.
To get performance up to par with the generated shaders (mostly), we have to optimize the fragment shader using spec constants. That works like this:
The D3D9 fixed function pixel pipeline stage consists of 8 texture stages. Each of those has both a color operation with 3 arguments and an alpha operation with 3 arguments. The arguments decide which value to use and the operation decides what to do with …

D3D9 Fixed function ubershader

---

VP_DXVK_requirements.json
src/dxbc/dxbc_options.cpp
src/dxvk/dxvk_cmdlist.cpp
src/dxvk/dxvk_cmdlist.h
src/dxvk/dxvk_compute.cpp
src/dxvk/dxvk_context.cpp
src/dxvk/dxvk_context.h
src/dxvk/dxvk_descriptor_pool.cpp
src/dxvk/dxvk_descriptor_pool.h
src/dxvk/dxvk_device.cpp
src/dxvk/dxvk_device_info.cpp
src/dxvk/dxvk_device_info.h
src/dxvk/dxvk_graphics.cpp
src/dxvk/dxvk_shader.cpp
src/dxvk/hud/dxvk_hud_item.cpp
src/dxvk/hud/dxvk_hud_item.h

TL;DR `maintenance6` and `depthClipEnable` features are now a hard requirement; everything that can even remotely run D3D content should already support the latter anyway, and dxbc-spirv no longer implements any of the ancient and untested workarounds to deal with the feature not being present.
This also greatly simplifies the legacy descriptor set allocation and turns `VkDescriptorPool` objects into linear allocators that are swapped and reset every couple of frames; reasoning being here that the old code was incredibly hard to reason about *and* problematic with tooling, validation layers frequently got confused because we'd reuse descriptor sets without resetting the pool first, etc.
This **will** come at the cost of some CPU performance, but all relevant Linux drivers have …

Require some extensions and simplify legacy binding model

---

src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_cursor.cpp
src/d3d9/d3d9_cursor.h
src/d3d9/d3d9_device.cpp

While looking at some cursor related problems, I took the liberty to clean up a lot of our cursor code to:
- fix broken sub 32x32 cursor bitmap size use (thankfully nobody is resorting to them, but now they'll be handled with software cursors in fullscreen, as was the intention in d3d9)
- make use of helper methods for state tracking so that hw/sw specific stuff is more obvious
- handle sw/hw cursor transitions within the same frame (there used to be a one-frame lag between the two, but now we consider the sw cursor as inactive once it has been queued for hiding on the next call to Present())
- better corner case handling, so that we have potentially less issues with apps dual using win32 and d3d cursors
Did a bit of testing and it seems to be behaving itself properly.

[d3d9] Cleanup of hw/sw cursor logic

---

src/d3d8/d3d8_device.cpp
src/d3d8/d3d8_interface.cpp
src/d3d8/d3d8_main.cpp
src/d3d9/d3d9_adapter.cpp
src/d3d9/d3d9_device.cpp

Note to self: don't validate vendor hack tests on ancient cards that don't actually support those vendor hacks. Looks like modern cards expose all supported sample counts with NULL format as well.

[d3d9] Advertise multisample NULL format checks

---

src/d3d9/d3d9_caps.h
src/d3d9/d3d9_device.cpp

Should fix #4803. @CookiePLMonster If you happen to still have that broken patch version around, would appreciate if you can confirm things work and look fine with this PR.
Native d3d9, unfortunately, does not validate either NumVertices, nor PrimitiveCount in any way, however it does appear to take into account the NumVertices value to fast skip calls.
Based on observed behavior on Windows XP:
`DrawPrimitive(D3DPT_TRIANGLELIST, 0, 8388608);` -> hard locks the OS
`DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, 5000, 0, 8388608);` -> hard locks the OS and crashes the GPU
`DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, 8, 0, 8388608);` -> works just fine (with the same valid index/vertex buffers)
`DrawIndexedPrimitive(D3DPT_TRIANGLELIST, 0, 0, 0, 0, 8388608);` -> also works just fine and …

[d3d9] Fast skip DrawIndexedPrimitive(UP) calls with 0 NumVertices

---

src/util/config/config.cpp

Should fix #5235 based on my testing.

[util] Disable direct buffer mapping for Lego Racers 2
